-- DanangTrip Real Data Seeder: Tags & Amenities (100 rows each)
-- FILE: 02_tags_amenities.sql

-- 1. TAGS (Target 100)
INSERT INTO tags (id, name, slug, type, created_at, updated_at) VALUES
(1, 'Gần biển', 'gan-bien', 'location', 'active', NOW(), NOW()),
(2, 'Trung tâm thành phố', 'trung-tam-thanh-pho', 'location', 'active', NOW(), NOW()),
(3, 'View sông', 'view-song', 'location', 'active', NOW(), NOW()),
(4, 'Yên tĩnh', 'yen-tinh', 'atmosphere', 'active', NOW(), NOW()),
(5, 'Sôi động', 'soi-dong', 'atmosphere', 'active', NOW(), NOW()),
(6, 'Sang trọng', 'sang-trong', 'style', 'active', NOW(), NOW()),
(7, 'Bình dân', 'binh-dan', 'style', 'active', NOW(), NOW()),
(8, 'Hiện đại', 'hien-dai', 'style',    'active', NOW(), NOW()),
(9, 'Cổ điển', 'co-dien', 'style', 'active', NOW(), NOW()),
(10, 'Lãng mạn', 'lang-man', 'atmosphere', 'active', NOW(), NOW()),
(11, 'Gia đình', 'gia-dinh', 'audience', 'active', NOW(), NOW()),
(12, 'Cặp đôi', 'cap-doi', 'audience', 'active', NOW(), NOW()),
(13, 'Nhóm bạn', 'nhom-ban', 'audience', 'active', NOW(), NOW()),
(14, 'Công tác', 'cong-tac', 'audience', 'active', NOW(), NOW()),
(15, 'Giá rẻ', 'gia-re', 'price', 'active', NOW(), NOW()),
(16, 'Cao cấp', 'cao-cap', 'price', 'active', NOW(), NOW()),
(17, 'Ẩm thực biển', 'am-thuc-bien', 'food', 'active', NOW(), NOW()),
(18, 'Món ăn đặc sản', 'mon-an-dac-san', 'food', 'active', NOW(), NOW()),
(19, 'Check-in đẹp', 'check-in-dep', 'feature', 'active', NOW(), NOW()),
(20, 'View đẹp', 'view-dep', 'feature', 'active', NOW(), NOW()),
(21, 'Thân thiện môi trường', 'eco-friendly', 'style', 'active', NOW(), NOW()),
(22, 'Văn hóa bản địa', 'local-culture', 'theme', 'active', NOW(), NOW()),
(23, 'Lịch sử', 'history', 'theme', 'active', NOW(), NOW()),
(24, 'Nghệ thuật', 'art', 'theme', 'active', NOW(), NOW()),
(25, 'Khám phá', 'adventure', 'theme', 'active', NOW(), NOW()),
(26, 'Nghỉ dưỡng', 'relaxation', 'theme', 'active', NOW(), NOW()),
(27, 'Mua sắm', 'shopping', 'theme', 'active', NOW(), NOW()),
(28, 'Giải trí', 'entertainment', 'theme', 'active', NOW(), NOW()),
(29, 'Vui chơi trẻ em', 'kids-friendly', 'audience', 'active', NOW(), NOW()),
(30, 'Thú cưng', 'pet-friendly', 'feature', 'active', NOW(), NOW()),
-- Adding 70 more tags to reach 100
(31, 'Outdoor seating', 'outdoor-seating', 'feature', 'active', NOW(), NOW()),
(32, 'Indoor seating', 'indoor-seating', 'feature', 'active', NOW(), NOW()),
(33, 'Phòng riêng', 'private-room', 'feature', 'active', NOW(), NOW()),
(34, 'Wifi mạnh', 'strong-wifi', 'feature', 'active', NOW(), NOW()),
(35, 'Chỗ đậu xe', 'parking', 'feature', 'active', NOW(), NOW()),
(36, 'Thanh toán thẻ', 'card-payment', 'feature', 'active', NOW(), NOW()),
(37, 'Mở cửa 24/7', 'open-247', 'feature', 'active', NOW(), NOW()),
(38, 'Giao hàng tận nơi', 'delivery', 'feature', 'active', NOW(), NOW()),
(39, 'Mua mang về', 'takeaway', 'feature', 'active', NOW(), NOW()),
(40, 'Đặt bàn trước', 'reservation', 'feature', 'active', NOW(), NOW()),
(41, 'Nhạc sống', 'live-music', 'atmosphere', 'active', NOW(), NOW()),
(42, 'DJ show', 'dj-show', 'atmosphere', 'active', NOW(), NOW()),
(43, 'View biển', 'ocean-view', 'location', 'active', NOW(), NOW()),
(44, 'Gần sân bay', 'near-airport', 'location', 'active', NOW(), NOW()),
(45, 'Gần ga tàu', 'near-station', 'location', 'active', NOW(), NOW()),
(46, 'Gần bến xe', 'near-bus-stop', 'location', 'active', NOW(), NOW()),
(47, 'Gần chợ', 'near-market', 'location', 'active', NOW(), NOW()),
(48, 'Vùng ngoại ô', 'suburban', 'location', 'active', NOW(), NOW()),
(49, 'Khu du lịch', 'tourist-area', 'location', 'active', NOW(), NOW()),
(50, 'Khu dân cư', 'residential-area', 'location', 'active', NOW(), NOW()),
(51, 'Sống ảo', 'instagrammable', 'style', 'active', NOW(), NOW()),
(52, 'Vintage', 'vintage-style', 'style', 'active', NOW(), NOW()),
(53, 'Indochine', 'indochine-style', 'style', 'active', NOW(), NOW()),
(54, 'Minimalist', 'minimalist-style', 'style', 'active', NOW(), NOW()),
(55, 'Industrial', 'industrial-style', 'style', 'active', NOW(), NOW()),
(56, 'Tropical', 'tropical-style', 'style', 'active', NOW(), NOW()),
(57, 'Bohemian', 'bohemian-style', 'style', 'active', NOW(), NOW()),
(58, 'Mộc mạc', 'rustic-style', 'style', 'active', NOW(), NOW()),
(59, 'Truyền thống', 'traditional-style', 'style', 'active', NOW(), NOW()),
(60, 'Sáng tạo', 'creative-style', 'style', 'active', NOW(), NOW()),
(61, 'Ăn sáng', 'breakfast', 'food', 'active', NOW(), NOW()),
(62, 'Ăn trưa', 'lunch', 'food', 'active', NOW(), NOW()),
(63, 'Ăn tối', 'dinner', 'food', 'active', NOW(), NOW()),
(64, 'Ăn đêm', 'late-night-food', 'food', 'active', NOW(), NOW()),
(65, 'Đồ uống có cồn', 'alcohol', 'food', 'active', NOW(), NOW()),
(66, 'Rượu vang', 'wine', 'food', 'active', NOW(), NOW()),
(67, 'Bia thủ công', 'craft-beer', 'food', 'active', NOW(), NOW()),
(68, 'Nước trái cây', 'juice-smoothie', 'food', 'active', NOW(), NOW()),
(69, 'Trà chiều', 'afternoon-tea', 'food', 'active', NOW(), NOW()),
(70, 'Tráng miệng', 'dessert', 'food', 'active', NOW(), NOW()),
(71, 'Sức khỏe', 'health', 'wellness', 'active', NOW(), NOW()),
(72, 'Trị liệu', 'therapy', 'wellness', 'active', NOW(), NOW()),
(73, 'Thư giãn', 'relaxation-well', 'wellness', 'active', NOW(), NOW()),
(74, 'Làm đẹp', 'beauty-care', 'wellness', 'active', NOW(), NOW()),
(75, 'Tập luyện', 'workout', 'wellness', 'active', NOW(), NOW()),
(76, 'Học tập', 'learning', 'education', 'active', NOW(), NOW()),
(77, 'Kỹ năng', 'skills', 'education', 'active', NOW(), NOW()),
(78, 'Ngoại ngữ', 'languages', 'education', 'active', NOW(), NOW()),
(79, 'Phát triển bản thân', 'self-development', 'education', 'active', NOW(), NOW()),
(80, 'Hướng nghiệp', 'career-guidance', 'education', 'active', NOW(), NOW()),
(81, 'Tech & Gadgets', 'tech-gadgets', 'shopping', 'active', NOW(), NOW()),
(82, 'Quần áo', 'clothing', 'shopping', 'active', NOW(), NOW()),
(83, 'Phụ kiện', 'accessories-shop', 'shopping', 'active', NOW(), NOW()),
(84, 'Quà tặng', 'gift-shop', 'shopping', 'active', NOW(), NOW()),
(85, 'Gia dụng', 'home-appliances', 'shopping', 'active', NOW(), NOW()),
(86, 'Xe máy', 'motorbike', 'transport', 'active', NOW(), NOW()),
(87, 'Ô tô', 'car', 'transport', 'active', NOW(), NOW()),
(88, 'Xe đạp', 'bicycle', 'transport', 'active', NOW(), NOW()),
(89, 'Đi bộ', 'walking', 'transport', 'active', NOW(), NOW()),
(90, 'Phương tiện công cộng', 'public-transport', 'transport', 'active', NOW(), NOW()),
(91, 'Sự kiện', 'events', 'business', 'active', NOW(), NOW()),
(92, 'Hội thảo', 'seminar', 'business', 'active', NOW(), NOW()),
(93, 'Giao thương', 'trade', 'business', 'active', NOW(), NOW()),
(94, 'Khởi nghiệp', 'startup', 'business', 'active', NOW(), NOW()),
(95, 'Đầu tư', 'investment', 'business', 'active', NOW(), NOW()),
(96, 'Cộng đồng', 'community', 'social', 'active', NOW(), NOW()),
(97, 'Thiện nguyện', 'charity', 'social', 'active', NOW(), NOW()),
(98, 'Kết nối', 'networking', 'social', 'active', NOW(), NOW()),
(99, 'Bền vững', 'sustainability', 'social', 'active', NOW(), NOW()),
(100, 'Đổi mới', 'innovation', 'social', 'active', NOW(), NOW());

-- 2. AMENITIES (Target 100)
INSERT INTO amenities (id, name, icon, category, created_at, updated_at) VALUES
(1, 'Wifi miễn phí', 'free-wifi', 'wifi', 'active', NOW(), NOW()),
(2, 'Hồ bơi', 'swimming-pool', 'pool', 'active', NOW(), NOW()),
(3, 'Chỗ đậu xe miễn phí', 'free-parking', 'parking', 'active', NOW(), NOW()),
(4, 'Phòng Gym', 'gym-fitness', 'fitness', 'active', NOW(), NOW()),
(5, 'Spa', 'spa-wellness', 'spa', 'active', NOW(), NOW()),
(6, 'Nhà hàng', 'on-site-restaurant', 'restaurant', 'active', NOW(), NOW()),
(7, 'Bar', 'on-site-bar', 'bar', 'active', NOW(), NOW()),
(8, 'Điều hòa nhiệt độ', 'air-conditioning', 'ac', 'active', NOW(), NOW()),
(9, 'Tivi', 'television', 'tv', 'active', NOW(), NOW()),
(10, 'Tủ lạnh mini', 'mini-bar', 'fridge', 'active', NOW(), NOW()),
(11, 'Máy pha cà phê', 'coffee-maker', 'coffee', 'active', NOW(), NOW()),
(12, 'Ban công', 'balcony', 'outdoor', 'active', NOW(), NOW()),
(13, 'Bàn làm việc', 'work-desk', 'desk', 'active', NOW(), NOW()),
(14, 'Két sắt', 'safety-box', 'safe', 'active', NOW(), NOW()),
(15, 'Máy sấy tóc', 'hair-dryer', 'dryer', 'active', NOW(), NOW()),
(16, 'Dịch vụ phòng 24/7', 'room-service-247', 'bell', 'active', NOW(), NOW()),
(17, 'Dịch vụ giặt là', 'laundry-service', 'washing', 'active', NOW(), NOW()),
(18, 'Đưa đón sân bay', 'airport-shuttle', 'shuttle', 'active', NOW(), NOW()),
(19, 'Lễ tân 24h', 'reception-24h', 'user', 'active', NOW(), NOW()),
(20, 'Thang máy', 'elevator', 'arrow-up', 'active', NOW(), NOW()),
(21, 'Phòng họp/Hội nghị', 'meeting-room', 'users', 'active', NOW(), NOW()),
(22, 'Sân vườn', 'garden', 'leaf', 'active', NOW(), NOW()),
(23, 'Khu vui chơi trẻ em', 'kids-club', 'baby', 'active', NOW(), NOW()),
(24, 'Cho phép thú cưng', 'pets-allowed', 'dog', 'active', NOW(), NOW()),
(25, 'Bãi biển riêng', 'private-beach', 'sun', 'active', NOW(), NOW()),
(26, 'Phòng không hút thuốc', 'non-smoking-room', 'smoke-free', 'active', NOW(), NOW()),
(27, 'Bồn tắm', 'bathtub', 'bath', 'active', NOW(), NOW()),
(28, 'Vòi hoa sen', 'shower', 'water', 'active', NOW(), NOW()),
(29, 'Áo choàng tắm', 'bathrobe', 'shirt', 'active', NOW(), NOW()),
(30, 'Dép đi trong phòng', 'slippers', 'foot', 'active', NOW(), NOW()),
-- Adding 70 more amenities to reach 100
(31, 'Ấm đun nước điện', 'electric-kettle', 'bolt', 'active', NOW(), NOW()),
(32, 'Bàn là & Cầu là', 'iron-board', 'iron', 'active', NOW(), NOW()),
(33, 'Nước đóng chai miễn phí', 'free-bottled-water', 'bottle', 'active', NOW(), NOW()),
(34, 'Dụng cụ nhà bếp', 'kitchenware', 'pot', 'active', NOW(), NOW()),
(35, 'Lò vi sóng', 'microwave', 'oven', 'active', NOW(), NOW()),
(36, 'Bếp nấu', 'stovetop', 'flame', 'active', NOW(), NOW()),
(37, 'Bàn ăn', 'dining-table', 'table', 'active', NOW(), NOW()),
(38, 'Ghế sofa', 'sofa', 'couch', 'active', NOW(), NOW()),
(39, 'Tủ quần áo', 'wardrobe', 'cabinet', 'active', NOW(), NOW()),
(40, 'Gương soi toàn thân', 'full-length-mirror', 'user', 'active', NOW(), NOW()),
(41, 'Đèn ngủ', 'night-lamp', 'light', 'active', NOW(), NOW()),
(42, 'Rèm cản sáng', 'blackout-curtains', 'window', 'active', NOW(), NOW()),
(43, 'Hệ thống báo cháy', 'fire-alarm', 'bell', 'active', NOW(), NOW()),
(44, 'Hệ thống phun nước tự động', 'sprinkler-system', 'water', 'active', NOW(), NOW()),
(45, 'Khóa cửa thông minh/Thẻ từ', 'smart-lock', 'key', 'active', NOW(), NOW()),
(46, 'Điện thoại nội bộ', 'intercom', 'phone', 'active', NOW(), NOW()),
(47, 'Ổ cắm USB', 'usb-outlet', 'usb', 'active', NOW(), NOW()),
(48, 'Sạc không dây', 'wireless-charging', 'bolt', 'active', NOW(), NOW()),
(49, 'Kênh truyền hình cáp', 'cable-tv', 'tv', 'active', NOW(), NOW()),
(50, 'Netflix/Smart TV', 'smart-tv', 'monitor', 'active', NOW(), NOW()),
(51, 'Báo chí hàng ngày', 'daily-newspaper', 'file-text', 'active', NOW(), NOW()),
(52, 'Bản đồ du lịch', 'tourist-map', 'map', 'active', NOW(), NOW()),
(53, 'Hỗ trợ đặt tour', 'tour-desk', 'globe', 'active', NOW(), NOW()),
(54, 'Đổi tiền tệ tại quầy', 'currency-exchange-desk', 'dollar', 'active', NOW(), NOW()),
(55, 'Dịch vụ gửi đồ', 'luggage-storage', 'briefcase', 'active', NOW(), NOW()),
(56, 'Dịch vụ trông xe hộ (Valet)', 'valet-parking', 'key', 'active', NOW(), NOW()),
(57, 'Trạm sạc xe điện', 'ev-charging', 'bolt', 'active', NOW(), NOW()),
(58, 'Cho thuê xe đạp', 'bicycle-rental', 'bike', 'active', NOW(), NOW()),
(59, 'Cho thuê xe máy', 'motorbike-rental-amenity', 'motorcycle', 'active', NOW(), NOW()),
(60, 'Dịch vụ thư ký', 'secretarial-service', 'file', 'active', NOW(), NOW()),
(61, 'Trung tâm dịch vụ khách hàng', 'business-center', 'laptop', 'active', NOW(), NOW()),
(62, 'Máy photocopy & In ấn', 'photocopy-print', 'printer', 'active', NOW(), NOW()),
(63, 'Wifi tốc độ cao', 'high-speed-wifi', 'zap', 'active', NOW(), NOW()),
(64, 'Bữa sáng miễn phí', 'free-breakfast', 'coffee', 'active', NOW(), NOW()),
(65, 'Bữa sáng buffet', 'buffet-breakfast', 'restaurant', 'active', NOW(), NOW()),
(66, 'Dịch vụ dọn phòng hàng ngày', 'daily-housekeeping', 'clean', 'active', NOW(), NOW()),
(67, 'Dịch vụ đánh giày', 'shoe-shine', 'star', 'active', NOW(), NOW()),
(68, 'Dịch vụ may đo/Sửa đồ', 'tailoring-service', 'scissors', 'active', NOW(), NOW()),
(69, 'Phòng xông hơi khô (Sauna)', 'sauna', 'cloud', 'active', NOW(), NOW()),
(70, 'Phòng xông hơi ướt (Steam)', 'steam-room', 'droplet', 'active', NOW(), NOW()),
(71, 'Bể sục Jacuzzi', 'jacuzzi', 'waves', 'active', NOW(), NOW()),
(72, 'Salon làm tóc', 'hair-salon', 'scissors', 'active', NOW(), NOW()),
(73, 'Tiệm làm móng (Nail)', 'nail-salon', 'pen', 'active', NOW(), NOW()),
(74, 'Cửa hàng tiện lợi trong resort', 'resort-shop', 'shopping-bag', 'active', NOW(), NOW()),
(75, 'Máy rút tiền ATM', 'atm-machine', 'dollar', 'active', NOW(), NOW()),
(76, 'Khu vực hút thuốc riêng', 'smoking-area', 'smoke', 'active', NOW(), NOW()),
(77, 'Camera an ninh 24/7', 'cctv', 'eye', 'active', NOW(), NOW()),
(78, 'Bảo vệ chuyên nghiệp', 'professional-security', 'shield', 'active', NOW(), NOW()),
(79, 'Lối đi cho người khuyết tật', 'wheelchair-access', 'wheelchair', 'active', NOW(), NOW()),
(80, 'Thang máy ưu tiên', 'priority-elevator', 'arrow-up-circle', 'active', NOW(), NOW()),
(81, 'Ghế cao cho trẻ em', 'high-chair', 'user-check', 'active', NOW(), NOW()),
(82, 'Nôi em bé (Crib)', 'crib', 'home', 'active', NOW(), NOW()),
(83, 'Dịch vụ bảo mẫu', 'babysitting-service', 'users', 'active', NOW(), NOW()),
(84, 'Khu vực BBQ ngoài trời', 'bbq-area', 'flame', 'active', NOW(), NOW()),
(85, 'Sân hiên phơi nắng', 'sun-terrace', 'sun', 'active', NOW(), NOW()),
(86, 'Ghế tắm nắng (Sunbed)', 'sunbed', 'armchair', 'active', NOW(), NOW()),
(87, 'Ô che nắng biển', 'beach-umbrella', 'umbrella', 'active', NOW(), NOW()),
(88, 'Khăn tắm biển miễn phí', 'free-beach-towels', 'towel', 'active', NOW(), NOW()),
(89, 'Thiết bị tập thể dục ngoài trời', 'outdoor-gym', 'activity', 'active', NOW(), NOW()),
(90, 'Thư viện trong nhà', 'indoor-library', 'book-open', 'active', NOW(), NOW()),
(91, 'Phòng chơi game/Bida', 'games-room', 'play', 'active', NOW(), NOW()),
(92, 'Dàn Karaoke', 'karaoke-system', 'mic', 'active', NOW(), NOW()),
(93, 'Rạp chiếu phim mini', 'mini-cinema', 'film', 'active', NOW(), NOW()),
(94, 'Máy lọc nước', 'water-purifier', 'droplet', 'active', NOW(), NOW()),
(95, 'Máy lọc không khí', 'air-purifier', 'wind', 'active', NOW(), NOW()),
(96, 'Đệm cao cấp/Memory foam', 'premium-bedding', 'bed', 'active', NOW(), NOW()),
(97, 'Lựa chọn gối (Pillow menu)', 'pillow-menu', 'archive', 'active', NOW(), NOW()),
(98, 'Dịch vụ đánh thức (Wake-up call)', 'wake-up-call', 'clock', 'active', NOW(), NOW()),
(99, 'Hộp sơ cứu (First aid kit)', 'first-aid', 'plus', 'active', NOW(), NOW()),
(100, 'Máy khử khuẩn tay', 'hand-sanitizer', 'sparkles', 'active', NOW(), NOW());
