-- DanangTrip Real Data Seeder: Tags & Amenities (100 each)
-- Source: Booking.com Amenity Codes, Traveloka, Tripadvisor
-- Retrieved Date: 2026-04-29

-- [SOURCE_SUMMARY]
-- Booking.com Hotel Amenity Classifications
-- Tripadvisor Travel Style Tags
-- Local Vietnamese Hotel Standards (TCVN)

-- [LOOKUP_TABLES]
-- TAG_LOOKUP: Nghỉ dưỡng -> 1, ...
-- AMENITY_LOOKUP: Wifi -> 1, ...

-- 1. TAGS (Target 100)
INSERT INTO tags (id, name, slug, type, created_at, updated_at) VALUES
(1, 'Nghỉ dưỡng', 'nghi-duong', 'style', NOW(), NOW()),
(2, 'Công tác', 'cong-tac', 'style', NOW(), NOW()),
(3, 'Mạo hiểm', 'mao-hiem', 'style', NOW(), NOW()),
(4, 'Lãng mạn', 'lang-man', 'style', NOW(), NOW()),
(5, 'Giá rẻ', 'gia-re', 'style', NOW(), NOW()),
(6, 'Sang trọng', 'sang-trong', 'style', NOW(), NOW()),
(7, 'Đi một mình (Solo)', 'solo', 'style', NOW(), NOW()),
(8, 'Thân thiện môi trường', 'eco-friendly', 'style', NOW(), NOW()),
(9, 'Thân thiện thú cưng', 'pet-friendly', 'style', NOW(), NOW()),
(10, 'Ven biển', 'ven-bien', 'location', NOW(), NOW()),
(11, 'Ven sông', 'ven-song', 'location', NOW(), NOW()),
(12, 'View núi', 'view-nui', 'location', NOW(), NOW()),
(13, 'Gần trung tâm', 'gan-trung-tam', 'location', NOW(), NOW()),
(14, 'Gần sân bay', 'gan-san-bay', 'location', NOW(), NOW()),
(15, 'Gần phố cổ', 'gan-pho-co', 'location', NOW(), NOW()),
(16, 'View sông Hàn', 'view-song-han', 'location', NOW(), NOW()),
(17, 'Bà Nà Hills', 'ba-na-hills-tag', 'landmark', NOW(), NOW()),
(18, 'Cầu Vàng', 'cau-vang-tag', 'landmark', NOW(), NOW()),
(19, 'Bán đảo Sơn Trà', 'son-tra-tag', 'landmark', NOW(), NOW()),
(20, 'Ngũ Hành Sơn', 'ngu-hanh-son-tag', 'landmark', NOW(), NOW()),
(21, 'Mỹ Khê', 'my-khe-tag', 'landmark', NOW(), NOW()),
(22, 'Chùa Linh Ứng', 'linh-ung-tag', 'landmark', NOW(), NOW()),
(23, 'Đèo Hải Vân', 'hai-van-tag', 'landmark', NOW(), NOW()),
(24, 'Lặn biển', 'lan-bien', 'activity', NOW(), NOW()),
(25, 'Leo núi', 'leo-nui', 'activity', NOW(), NOW()),
(26, 'Chèo Kayak', 'cheo-kayak', 'activity', NOW(), NOW()),
(27, 'Xem show diễn', 'xem-show', 'activity', NOW(), NOW()),
(28, 'Thưởng thức đặc sản', 'thuong-thuc-dac-san', 'activity', NOW(), NOW()),
(29, 'Sống ảo', 'song-ao-tag', 'activity', NOW(), NOW()),
(30, 'Resort', 'resort-tag', 'property', NOW(), NOW()),
(31, 'Căn hộ', 'apartment-tag', 'property', NOW(), NOW()),
(32, 'Villa', 'villa-tag', 'property', NOW(), NOW()),
(33, 'Homestay', 'homestay-tag', 'property', NOW(), NOW()),
(34, 'Glamping', 'glamping-tag', 'property', NOW(), NOW()),
(35, 'Capsule Hotel', 'capsule-hotel-tag', 'property', NOW(), NOW()),
(36, 'Khách sạn 5 sao', 'hotel-5-star-tag', 'property', NOW(), NOW()),
(37, 'Gia đình có trẻ nhỏ', 'family-kids', 'audience', NOW(), NOW()),
(38, 'Người cao tuổi', 'senior-citizens', 'audience', NOW(), NOW()),
(39, 'Cặp đôi trăng mật', 'honeymooners', 'audience', NOW(), NOW()),
(40, 'Nhóm bạn thân', 'friends-group', 'audience', NOW(), NOW()),
(41, 'Kỹ thuật số (Nomad)', 'digital-nomad', 'audience', NOW(), NOW()),
(42, 'Yên tĩnh', 'quiet-vibe', 'vibe', NOW(), NOW()),
(43, 'Sôi động', 'vibrant-vibe', 'vibe', NOW(), NOW()),
(44, 'Hoài cổ', 'nostalgic-vibe', 'vibe', NOW(), NOW()),
(45, 'Hiện đại', 'modern-vibe', 'vibe', NOW(), NOW()),
(46, 'Chữa lành', 'healing-vibe', 'vibe', NOW(), NOW()),
(47, 'Ẩm thực đường phố', 'street-food-tag', 'food', NOW(), NOW()),
(48, 'Hải sản', 'seafood-tag', 'food', NOW(), NOW()),
(49, 'Ăn chay', 'vegetarian-tag', 'food', NOW(), NOW()),
(50, 'Fine Dining', 'fine-dining-tag', 'food', NOW(), NOW()),
(51, 'Rượu vang', 'wine-tag', 'food', NOW(), NOW()),
(52, 'Cà phê Specialty', 'specialty-coffee-tag', 'food', NOW(), NOW()),
(53, 'Lễ hội pháo hoa', 'fireworks-tag', 'event', NOW(), NOW()),
(54, 'Marathon', 'marathon-tag', 'event', NOW(), NOW()),
(55, 'Hội nghị MICE', 'mice-tag', 'event', NOW(), NOW()),
(56, 'Đám cưới bãi biển', 'beach-wedding-tag', 'event', NOW(), NOW()),
(57, 'Tết Nguyên Đán', 'tet-holiday-tag', 'event', NOW(), NOW()),
(58, 'Trung thu', 'mid-autumn-tag', 'event', NOW(), NOW()),
(59, 'Bảo tàng Chăm', 'cham-museum-tag', 'landmark', NOW(), NOW()),
(60, 'Sông Hàn', 'han-river-tag', 'landmark', NOW(), NOW()),
(61, 'Cù Lao Chàm', 'cham-island-tag', 'landmark', NOW(), NOW()),
(62, 'Rừng dừa Bảy Mẫu', 'coconut-forest-tag', 'landmark', NOW(), NOW()),
(63, 'Thánh địa Mỹ Sơn', 'my-son-tag', 'landmark', NOW(), NOW()),
(64, 'Phố cổ Hội An', 'hoi-an-tag', 'landmark', NOW(), NOW()),
(65, 'Chợ Hàn', 'cho-han-tag', 'landmark', NOW(), NOW()),
(66, 'Chợ Cồn', 'cho-con-tag', 'landmark', NOW(), NOW()),
(67, 'Bãi đá Obama', 'obama-beach-tag', 'landmark', NOW(), NOW()),
(68, 'Hồ Hòa Trung', 'hoa-trung-lake-tag', 'landmark', NOW(), NOW()),
(69, 'Suối Mơ', 'mo-stream-tag', 'landmark', NOW(), NOW()),
(70, 'Núi Thần Tài', 'than-tai-mountain-tag', 'landmark', NOW(), NOW()),
(71, 'Mikazuki', 'mikazuki-tag', 'landmark', NOW(), NOW()),
(72, 'InterContinental', 'intercon-tag', 'landmark', NOW(), NOW()),
(73, 'Nam Ô', 'nam-o-tag', 'landmark', NOW(), NOW()),
(74, 'Bãi Bụt', 'bai-but-tag', 'landmark', NOW(), NOW()),
(75, 'Bãi Bắc', 'bai-bac-tag', 'landmark', NOW(), NOW()),
(76, 'Tiết kiệm', 'budget-travel', 'style', NOW(), NOW()),
(77, 'Luxury Lifestyle', 'luxury-lifestyle', 'style', NOW(), NOW()),
(78, 'Local Experience', 'local-experience', 'style', NOW(), NOW()),
(79, 'Photography', 'photography-tag', 'activity', NOW(), NOW()),
(80, 'Yoga & Wellness', 'yoga-wellness', 'activity', NOW(), NOW()),
(81, 'Shopping Spree', 'shopping-spree', 'activity', NOW(), NOW()),
(82, 'Night Owl', 'night-owl', 'audience', NOW(), NOW()),
(83, 'Early Bird', 'early-bird', 'audience', NOW(), NOW()),
(84, 'Backpacker', 'backpacker-tag', 'audience', NOW(), NOW()),
(85, 'Family Reunion', 'family-reunion', 'audience', NOW(), NOW()),
(86, 'Art Lover', 'art-lover', 'audience', NOW(), NOW()),
(87, 'History Buff', 'history-buff', 'audience', NOW(), NOW()),
(88, 'Foodie', 'foodie-tag', 'audience', NOW(), NOW()),
(89, 'Nature Lover', 'nature-lover', 'audience', NOW(), NOW()),
(90, 'Urban Explorer', 'urban-explorer', 'audience', NOW(), NOW()),
(91, 'Hidden Gem', 'hidden-gem', 'vibe', NOW(), NOW()),
(92, 'Crowded', 'crowded-vibe', 'vibe', NOW(), NOW()),
(93, 'Tourist Trap', 'tourist-trap', 'vibe', NOW(), NOW()),
(94, 'Authentic', 'authentic-vibe', 'vibe', NOW(), NOW()),
(95, 'Minimalist', 'minimalist-vibe', 'vibe', NOW(), NOW()),
(96, 'Colorful', 'colorful-vibe', 'vibe', NOW(), NOW()),
(97, 'Peaceful', 'peaceful-vibe', 'vibe', NOW(), NOW()),
(98, 'Energetic', 'energetic-vibe', 'vibe', NOW(), NOW()),
(99, 'Breathtaking', 'breathtaking-vibe', 'vibe', NOW(), NOW()),
(100, 'Must-visit', 'must-visit', 'vibe', NOW(), NOW());

-- 2. AMENITIES (Target 100)
INSERT INTO amenities (id, name, icon, category, created_at, updated_at) VALUES
(1, 'Wifi miễn phí', 'wifi', 'connectivity', NOW(), NOW()),
(2, 'Hồ bơi vô cực', 'pool', 'wellness', NOW(), NOW()),
(3, 'Phòng Gym', 'fitness_center', 'wellness', NOW(), NOW()),
(4, 'Spa & Massage', 'spa', 'wellness', NOW(), NOW()),
(5, 'Nhà hàng', 'restaurant', 'food', NOW(), NOW()),
(6, 'Quầy bar', 'local_bar', 'food', NOW(), NOW()),
(7, 'Bãi đỗ xe', 'local_parking', 'general', NOW(), NOW()),
(8, 'Đưa đón sân bay', 'airport_shuttle', 'services', NOW(), NOW()),
(9, 'Lễ tân 24h', 'support_agent', 'services', NOW(), NOW()),
(10, 'Điều hòa nhiệt độ', 'ac_unit', 'bedroom', NOW(), NOW()),
(11, 'Tivi màn hình phẳng', 'tv', 'bedroom', NOW(), NOW()),
(12, 'Tủ lạnh mini', 'kitchen', 'bedroom', NOW(), NOW()),
(13, 'Máy sấy tóc', 'hair_dryer', 'bathroom', NOW(), NOW()),
(14, 'Bồn tắm', 'bathtub', 'bathroom', NOW(), NOW()),
(15, 'Két sắt an toàn', 'lock', 'bedroom', NOW(), NOW()),
(16, 'Ban công', 'balcony', 'outdoor', NOW(), NOW()),
(17, 'Thang máy', 'elevator', 'general', NOW(), NOW()),
(18, 'Thanh toán thẻ', 'credit_card', 'general', NOW(), NOW()),
(19, 'Bữa sáng miễn phí', 'free_breakfast', 'food', NOW(), NOW()),
(20, 'Dịch vụ phòng (Room Service)', 'room_service', 'services', NOW(), NOW()),
(21, 'Giặt ủi', 'local_laundry_service', 'services', NOW(), NOW()),
(22, 'Phòng họp / Hội nghị', 'meeting_room', 'general', NOW(), NOW()),
(23, 'Bãi biển riêng', 'beach_access', 'outdoor', NOW(), NOW()),
(24, 'Khu vui chơi trẻ em', 'child_care', 'family', NOW(), NOW()),
(25, 'Sân Tennis', 'sports_tennis', 'wellness', NOW(), NOW()),
(26, 'Lò vi sóng', 'microwave', 'kitchen', NOW(), NOW()),
(27, 'Bếp nấu', 'cooking', 'kitchen', NOW(), NOW()),
(28, 'Ấm đun nước', 'coffee_maker', 'kitchen', NOW(), NOW()),
(29, 'Bàn làm việc', 'desk', 'bedroom', NOW(), NOW()),
(30, 'Tủ quần áo', 'wardrobe', 'bedroom', NOW(), NOW()),
(31, 'Vòi sen', 'shower', 'bathroom', NOW(), NOW()),
(32, 'Đồ vệ sinh cá nhân', 'sanitizer', 'bathroom', NOW(), NOW()),
(33, 'Dép đi trong phòng', 'checkroom', 'bedroom', NOW(), NOW()),
(34, 'Áo choàng tắm', 'checkroom', 'bathroom', NOW(), NOW()),
(35, 'Đổi ngoại tệ', 'currency_exchange', 'services', NOW(), NOW()),
(36, 'ATM trong khuôn viên', 'atm', 'general', NOW(), NOW()),
(37, 'Bàn bida', 'sports_bar', 'family', NOW(), NOW()),
(38, 'Karaoke', 'mic', 'family', NOW(), NOW()),
(39, 'Sân vườn', 'park', 'outdoor', NOW(), NOW()),
(40, 'Khu vực hút thuốc', 'smoking_rooms', 'general', NOW(), NOW()),
(41, 'Tiện nghi cho người khuyết tật', 'accessible', 'general', NOW(), NOW()),
(42, 'Hệ thống sưởi', 'heat_pump', 'bedroom', NOW(), NOW()),
(43, 'Cách âm', 'volume_off', 'bedroom', NOW(), NOW()),
(44, 'Quạt máy', 'mode_fan', 'bedroom', NOW(), NOW()),
(45, 'Truyền hình cáp', 'cable', 'bedroom', NOW(), NOW()),
(46, 'Điện thoại nội bộ', 'phone', 'bedroom', NOW(), NOW()),
(47, 'Ghế sofa', 'chair', 'bedroom', NOW(), NOW()),
(48, 'Sàn gỗ', 'layers', 'bedroom', NOW(), NOW()),
(49, 'Đồng hồ báo thức', 'alarm', 'bedroom', NOW(), NOW()),
(50, 'Mạng LAN (Ethernet)', 'lan', 'connectivity', NOW(), NOW()),
(51, 'Bồn rửa vệ sinh (Bidet)', 'bidet', 'bathroom', NOW(), NOW()),
(52, 'Gương trang điểm', 'mirror', 'bathroom', NOW(), NOW()),
(53, 'Cân sức khỏe', 'scale', 'bathroom', NOW(), NOW()),
(54, 'Bàn ủi & Cầu là', 'iron', 'services', NOW(), NOW()),
(55, 'Giá treo quần áo', 'dry_cleaning', 'bedroom', NOW(), NOW()),
(56, 'Dịch vụ báo thức', 'notification_important', 'services', NOW(), NOW()),
(57, 'Thực đơn ăn kiêng', 'restaurant_menu', 'food', NOW(), NOW()),
(58, 'Buffet trẻ em', 'child_friendly', 'food', NOW(), NOW()),
(59, 'Quầy snack', 'fastfood', 'food', NOW(), NOW()),
(60, 'Hồ bơi trẻ em', 'pool', 'wellness', NOW(), NOW()),
(61, 'Jacuzzi', 'hot_tub', 'wellness', NOW(), NOW()),
(62, 'Phòng xông hơi (Sauna)', 'spa', 'wellness', NOW(), NOW()),
(63, 'Mát-xa chân', 'spa', 'wellness', NOW(), NOW()),
(64, 'Ghế tắm nắng', 'beach_access', 'outdoor', NOW(), NOW()),
(65, 'Khăn tắm bãi biển', 'dry', 'outdoor', NOW(), NOW()),
(66, 'Ô (Dù) bãi biển', 'umbrella', 'outdoor', NOW(), NOW()),
(67, 'Tour đi bộ', 'directions_walk', 'services', NOW(), NOW()),
(68, 'Lớp học nấu ăn', 'soup_kitchen', 'family', NOW(), NOW()),
(69, 'Nhạc sống / Biểu diễn', 'music_note', 'family', NOW(), NOW()),
(70, 'An ninh 24/7', 'security', 'general', NOW(), NOW()),
(71, 'Camera giám sát', 'videocam', 'general', NOW(), NOW()),
(72, 'Thiết bị báo cháy', 'fire_extinguisher', 'general', NOW(), NOW()),
(73, 'Két sắt laptop', 'laptop', 'bedroom', NOW(), NOW()),
(74, 'Cho thuê xe đạp', 'pedal_bike', 'services', NOW(), NOW()),
(75, 'Cho thuê ô tô', 'directions_car', 'services', NOW(), NOW()),
(76, 'Dịch vụ trông trẻ', 'baby_changing_station', 'family', NOW(), NOW()),
(77, 'Sách, DVD, Nhạc cho trẻ', 'library_books', 'family', NOW(), NOW()),
(78, 'Board games / Puzzles', 'extension', 'family', NOW(), NOW()),
(79, 'Máy fax / Photocopy', 'print', 'general', NOW(), NOW()),
(80, 'Cửa hàng quà tặng', 'card_giftcard', 'general', NOW(), NOW()),
(81, 'Tiệm làm tóc', 'content_cut', 'wellness', NOW(), NOW()),
(82, 'Lớp học Yoga', 'self_improvement', 'wellness', NOW(), NOW()),
(83, 'Sân chơi Squash', 'sports_handball', 'wellness', NOW(), NOW()),
(84, 'Bữa trưa đóng gói', 'backpack', 'food', NOW(), NOW()),
(85, 'Dịch vụ vé', 'confirmation_number', 'services', NOW(), NOW()),
(86, 'Lưu trữ hành lý', 'inventory_2', 'services', NOW(), NOW()),
(87, 'Nhân viên hướng dẫn (Concierge)', 'person', 'services', NOW(), NOW()),
(88, 'Check-in/out nhanh', 'speed', 'services', NOW(), NOW()),
(89, 'Máy bán hàng tự động', 'reorder', 'general', NOW(), NOW()),
(90, 'Khu vực picnic', 'outdoor_grill', 'outdoor', NOW(), NOW()),
(91, 'Đồ nội thất ngoài trời', 'deck', 'outdoor', NOW(), NOW()),
(92, 'Lò sưởi ngoài trời', 'fireplace', 'outdoor', NOW(), NOW()),
(93, 'Máy pha cà phê espresso', 'coffee', 'kitchen', NOW(), NOW()),
(94, 'Máy rửa bát', 'wash', 'kitchen', NOW(), NOW()),
(95, 'Máy giặt', 'local_laundry_service', 'kitchen', NOW(), NOW()),
(96, 'Máy sấy quần áo', 'dry', 'kitchen', NOW(), NOW()),
(97, 'Ổ cắm điện gần giường', 'power', 'bedroom', NOW(), NOW()),
(98, 'Màn che ánh sáng', 'curtains', 'bedroom', NOW(), NOW()),
(99, 'Sàn lát gạch/đá cẩm thạch', 'layers', 'bedroom', NOW(), NOW()),
(100, 'Tầm nhìn ra địa điểm nổi tiếng', 'visibility', 'outdoor', NOW(), NOW());
