-- DanangTrip Real Data Seeder: Tour & Blog Categories (100 rows each)
-- FILE: 03_tour_blog_categories.sql

-- 1. TOUR_CATEGORIES (Target 100)
INSERT INTO tour_categories (id, name, slug, description, icon, sort_order, status, created_at, updated_at) VALUES
(1, 'Tour Bà Nà Hills', 'tour-ba-na-hills', 'Khám phá đỉnh núi Chúa, Cầu Vàng và làng Pháp.', 'https://images.unsplash.com/photo-1590766948562-3f69bb15664a', 'active', NOW(), NOW()),
(2, 'Tour Phố Cổ Hội An', 'tour-hoi-an', 'Tìm về nét hoài cổ của thương cảng sầm uất.', 'https://images.unsplash.com/photo-1559592413-7ce75d0e40ec', 'active', NOW(), NOW()),
(3, 'Tour Cố Đô Huế', 'tour-hue', 'Hành trình di sản qua các lăng tẩm và cung điện.', 'https://images.unsplash.com/photo-1582650625119-3a31f8fa2699', 'active', NOW(), NOW()),
(4, 'Tour Biển & Đảo', 'tour-bien-dao', 'Lặn ngắm san hô tại Cù Lao Chàm, Bán đảo Sơn Trà.', 'https://images.unsplash.com/photo-1502680390469-be75c86b636f', 'active', NOW(), NOW()),
(5, 'Tour Khám Phá Thiên Nhiên', 'tour-thien-nhien', 'Trekking rừng Sơn Trà, suối khoáng nóng.', 'https://images.unsplash.com/photo-1544654803-b69110b39e3d', 'active', NOW(), NOW()),
(6, 'Tour Ẩm Thực', 'tour-am-thuc', 'Thưởng thức đặc sản đường phố và lớp học nấu ăn.', 'https://images.unsplash.com/photo-1562967914-6cbb77312935', 'active', NOW(), NOW()),
(7, 'Tour Mạo Hiểm', 'tour-mao-hiem', 'Leo núi, đu dây zipline, chèo thuyền kayak.', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470', 'active', NOW(), NOW()),
(8, 'Tour Nghỉ Dưỡng', 'tour-nghi-duong', 'Thư giãn tại các resort cao cấp và tắm khoáng.', 'https://images.unsplash.com/photo-1566073771259-6a8506099945', 'active', NOW(), NOW()),
(9, 'Tour Trong Ngày', 'tour-trong-ngay', 'Các tour khởi hành và kết thúc trong ngày.', NULL, 'active', NOW(), NOW()),
(10, 'Tour Dài Ngày (Xuyên Việt)', 'tour-dai-ngay', 'Hành trình khám phá nhiều tỉnh thành.', NULL, 'active', NOW(), NOW()),
-- Adding 90 more tour categories to reach 100
(11, 'Tour Ghép Đoàn', 'tour-ghep-doan', 'Tiết kiệm chi phí khi đi cùng nhóm khách khác.', NULL, 'active', NOW(), NOW()),
(12, 'Tour Riêng Cho Gia Đình', 'tour-gia-dinh', 'Lịch trình linh hoạt, không gian riêng tư.', NULL, 'active', NOW(), NOW()),
(13, 'Tour Trăng Mật', 'tour-trang-mat', 'Dành riêng cho các cặp đôi mới cưới.', NULL, 'active', NOW(), NOW()),
(14, 'Tour Nhiếp Ảnh', 'tour-nhiep-anh', 'Săn ảnh tại các điểm đẹp nhất miền Trung.', NULL, 'active', NOW(), NOW()),
(15, 'Tour Làng Nghề', 'tour-lang-nghe', 'Thăm làng đá Non Nước, làng gốm Thanh Hà.', NULL, 'active', NOW(), NOW()),
(16, 'Tour Tâm Linh', 'tour-tam-linh', 'Viếng chùa Linh Ứng, Thánh địa Mỹ Sơn.', NULL, 'active', NOW(), NOW()),
(17, 'Tour Giáo Dục (Study Tour)', 'tour-giao-duc', 'Kết hợp học tập và trải nghiệm thực tế.', NULL, 'active', NOW(), NOW()),
(18, 'Tour MICE (Sự kiện/Hội thảo)', 'tour-mice', 'Tổ chức sự kiện kết hợp nghỉ dưỡng công ty.', NULL, 'active', NOW(), NOW()),
(19, 'Tour Team Building', 'tour-team-building', 'Hoạt động gắn kết đội ngũ trên bãi biển.', NULL, 'active', NOW(), NOW()),
(20, 'Tour Luxury (Hạng Sang)', 'tour-luxury', 'Dịch vụ đẳng cấp nhất, xe sang, resort 5+.', NULL, 'active', NOW(), NOW()),
(21, 'Tour Bằng Xe Jeep', 'tour-xe-jeep', 'Trải nghiệm mạo hiểm trên đèo Hải Vân.', NULL, 'active', NOW(), NOW()),
(22, 'Tour Du Thuyền Sông Hàn', 'tour-du-thuyen', 'Ngắm cầu Rồng phun lửa từ trên sông.', NULL, 'active', NOW(), NOW()),
(23, 'Tour Trực Thăng Ngắm Cảnh', 'tour-truc-thang', 'Góc nhìn toàn cảnh Đà Nẵng từ trên cao.', NULL, 'active', NOW(), NOW()),
(24, 'Tour Đạp Xe Làng Quê', 'tour-dap-xe', 'Khám phá cuộc sống bình yên vùng ven Hội An.', NULL, 'active', NOW(), NOW()),
(25, 'Tour Chèo Thúng Rừng Dừa', 'tour-rung-dua', 'Trải nghiệm văn hóa sông nước Cẩm Thanh.', NULL, 'active', NOW(), NOW()),
(26, 'Tour Ngắm Hoàng Hôn', 'tour-hoang-hon', 'Thưởng thức trà chiều và ngắm mặt trời lặn.', NULL, 'active', NOW(), NOW()),
(27, 'Tour Bình Minh Trên Biển', 'tour-binh-minh', 'Đón ngày mới và xem kéo lưới của ngư dân.', NULL, 'active', NOW(), NOW()),
(28, 'Tour Chợ Đêm & Mua Sắm', 'tour-cho-dem', 'Khám phá chợ Cồn, chợ Hàn về đêm.', NULL, 'active', NOW(), NOW()),
(29, 'Tour Xe Máy Bản Địa', 'tour-xe-may', 'Đi sâu vào ngõ ngách cùng hướng dẫn viên bản địa.', NULL, 'active', NOW(), NOW()),
(30, 'Tour Golf Nghỉ Dưỡng', 'tour-golf', 'Chơi golf tại các sân đẳng cấp quốc tế.', NULL, 'active', NOW(), NOW()),
(31, 'Tour Chăm Sóc Sức Khỏe', 'tour-wellness', 'Yoga bãi biển và trị liệu thảo mộc.', NULL, 'active', NOW(), NOW()),
(32, 'Tour Khám Phá Hang Động', 'tour-hang-dong', 'Thăm động Phong Nha, Thiên Đường (Quảng Bình).', NULL, 'active', NOW(), NOW()),
(33, 'Tour Sinh Thái Gành Bàn', 'tour-ganh-ban', 'Lặn biển ngắm san hô hoang sơ.', NULL, 'active', NOW(), NOW()),
(34, 'Tour Đảo Lý Sơn (Quảng Ngãi)', 'tour-ly-son', 'Khám phá vương quốc tỏi và núi lửa.', NULL, 'active', NOW(), NOW()),
(35, 'Tour Quy Nhơn - Phú Yên', 'tour-quy-nhon', 'Con đường di sản và biển xanh.', NULL, 'active', NOW(), NOW()),
(36, 'Tour Tây Nguyên (Kon Tum/Gia Lai)', 'tour-tay-nguyen', 'Tìm về đại ngàn từ Đà Nẵng.', NULL, 'active', NOW(), NOW()),
(37, 'Tour Mùa Pháo Hoa (DIFF)', 'tour-phao-hoa', 'Vị trí xem pháo hoa đẹp nhất.', NULL, 'active', NOW(), NOW()),
(38, 'Tour Tết Nguyên Đán', 'tour-tet', 'Trải nghiệm tết cổ truyền miền Trung.', NULL, 'active', NOW(), NOW()),
(39, 'Tour Lễ 30/4 & 1/5', 'tour-le-304', 'Lịch trình đặc biệt cho kỳ nghỉ lễ.', NULL, 'active', NOW(), NOW()),
(40, 'Tour Mùa Hè Rực Rỡ', 'tour-mua-he', 'Các hoạt động biển sôi động nhất.', NULL, 'active', NOW(), NOW()),
(41, 'Tour Thu Vàng Miền Trung', 'tour-mua-thu', 'Cảm nhận tiết trời dịu mát của Huế và Hội An.', NULL, 'active', NOW(), NOW()),
(42, 'Tour Đông Ấm Áp', 'tour-mua-dong', 'Thưởng thức ẩm thực nóng hổi và phố vắng.', NULL, 'active', NOW(), NOW()),
(43, 'Tour Tình Nguyện', 'tour-tinh-nguyen', 'Kết hợp du lịch và hỗ trợ cộng đồng địa phương.', NULL, 'active', NOW(), NOW()),
(44, 'Tour Vẽ Tranh Ngoài Trời', 'tour-drawing', 'Ghi lại vẻ đẹp phố cổ qua nét vẽ.', NULL, 'active', NOW(), NOW()),
(45, 'Tour Thần Tài & Suối Khoáng', 'tour-suoi-khoang', 'Nghỉ dưỡng suối khoáng nóng Núi Thần Tài.', NULL, 'active', NOW(), NOW()),
(46, 'Tour Công Viên Nước Holand', 'tour-holand', 'Vui chơi tại khu phức hợp giải trí mới.', NULL, 'active', NOW(), NOW()),
(47, 'Tour Bảo Tàng 3D TrickEye', 'tour-3d-museum', 'Thế giới ảo ảnh đầy thú vị.', NULL, 'active', NOW(), NOW()),
(48, 'Tour Ngược Dòng Sông Thu Bồn', 'tour-song-thu-bon', 'Tìm hiểu văn hóa ven sông.', NULL, 'active', NOW(), NOW()),
(49, 'Tour Thăm Nhà Vườn Huế', 'tour-nha-vuon', 'Kiến trúc đặc sắc của giới quý tộc xưa.', NULL, 'active', NOW(), NOW()),
(50, 'Tour Cà Phê & Chuyện Kể', 'tour-story-cafe', 'Nghe những câu chuyện lịch sử bên tách cà phê.', NULL, 'active', NOW(), NOW()),
-- Synthetic categories 51-100 to meet volume
(51, 'Tour Chạy Bộ (Running Tour)', 'tour-running', 'Khám phá thành phố buổi sớm qua các cung đường chạy.', NULL, 'active', NOW(), NOW()),
(52, 'Tour Yoga Đón Bình Minh', 'tour-sunrise-yoga', 'Tái tạo năng lượng trên bãi biển Mỹ Khê.', NULL, 'active', NOW(), NOW()),
(53, 'Tour Workshop Thủ Công', 'tour-workshop', 'Học làm lồng đèn, làm gốm trong 1 buổi.', NULL, 'active', NOW(), NOW()),
(54, 'Tour Khám Phá Chợ Cá', 'tour-fish-market', 'Trải nghiệm nhịp sống ngư dân lúc 4h sáng.', NULL, 'active', NOW(), NOW()),
(55, 'Tour Tìm Hiểu Cao Lầu', 'tour-cao-lau', 'Đi sâu vào quy trình làm món đặc sản Hội An.', NULL, 'active', NOW(), NOW()),
(56, 'Tour Sân Vườn & Cây Cảnh', 'tour-garden', 'Thăm các khu vườn nghệ thuật tại Hòa Vang.', NULL, 'active', NOW(), NOW()),
(57, 'Tour Hành Trình Di Sản Miền Trung', 'tour-heritage-path', 'Chuỗi tour Huế - Đà Nẵng - Hội An - Mỹ Sơn.', NULL, 'active', NOW(), NOW()),
(58, 'Tour Xe Buýt 2 Tầng', 'tour-coco-bus', 'Ngắm nhìn thành phố từ xe buýt mui trần.', NULL, 'active', NOW(), NOW()),
(59, 'Tour Tàu Hỏa Đà Nẵng - Huế', 'tour-train-hue', 'Hành trình ngắm đèo Hải Vân đẹp nhất.', NULL, 'active', NOW(), NOW()),
(60, 'Tour Khám Phá Hồ Hòa Trung', 'tour-lake-camp', 'Cắm trại và chèo SUP tại hồ.', NULL, 'active', NOW(), NOW()),
(61, 'Tour Đỉnh Bàn Cờ', 'tour-ban-co', 'Lên đỉnh Sơn Trà chơi cờ cùng tiên ông.', NULL, 'active', NOW(), NOW()),
(62, 'Tour Cây Đa Ngàn Năm', 'tour-cay-da', 'Tìm hiểu hệ sinh thái rừng Sơn Trà.', NULL, 'active', NOW(), NOW()),
(63, 'Tour Ghềnh Bàng Trekking', 'tour-ghenh-bang', 'Chuyến đi bộ dọc bờ biển hoang sơ.', NULL, 'active', NOW(), NOW()),
(64, 'Tour Bãi Bụt - Bãi Rạng', 'tour-bai-but', 'Thưởng thức hải sản bên ghềnh đá.', NULL, 'active', NOW(), NOW()),
(65, 'Tour Trượt Thác Hòa Phú Thành', 'tour-truot-thac', 'Thử thách cảm giác mạnh trên suối.', NULL, 'active', NOW(), NOW()),
(66, 'Tour Mikazuki Water Park', 'tour-mikazuki', 'Công viên nước phong cách Nhật Bản.', NULL, 'active', NOW(), NOW()),
(67, 'Tour Helio Center', 'tour-helio', 'Thiên đường giải trí ban đêm.', NULL, 'active', NOW(), NOW()),
(68, 'Tour VinWonders Nam Hội An', 'tour-vinwonders', 'Khu vui chơi đẳng cấp quốc tế.', NULL, 'active', NOW(), NOW()),
(69, 'Tour Rừng Dừa Bảy Mẫu', 'tour-bay-mau', 'Chèo thúng và múa thúng đặc sắc.', NULL, 'active', NOW(), NOW()),
(70, 'Tour Làng Gốm Thanh Hà', 'tour-thanh-ha', 'Trải nghiệm tự tay làm gốm.', NULL, 'active', NOW(), NOW()),
(71, 'Tour Làng Rau Trà Quế', 'tour-tra-que', 'Một ngày làm nông dân thực thụ.', NULL, 'active', NOW(), NOW()),
(72, 'Tour Kim Bồng Mộc Nghệ', 'tour-kim-bong', 'Thăm làng nghề đóng tàu và chạm khắc gỗ.', NULL, 'active', NOW(), NOW()),
(73, 'Tour Làng Đúc Đồng Phước Kiều', 'tour-phuoc-kieu', 'Tìm hiểu nghệ thuật đúc đồng lâu đời.', NULL, 'active', NOW(), NOW()),
(74, 'Tour Hội Quán Phúc Kiến', 'tour-phuc-kien', 'Kiến trúc Trung Hoa đặc sắc tại Hội An.', NULL, 'active', NOW(), NOW()),
(75, 'Tour Chùa Cầu Hội An', 'tour-chua-cau', 'Biểu tượng lịch sử của phố cổ.', NULL, 'active', NOW(), NOW()),
(76, 'Tour Đại Nội Huế', 'tour-dai-noi', 'Khám phá hoàng cung triều Nguyễn.', NULL, 'active', NOW(), NOW()),
(77, 'Tour Lăng Khải Định', 'tour-khai-dinh', 'Kiến trúc giao thoa Đông - Tây.', NULL, 'active', NOW(), NOW()),
(78, 'Tour Lăng Minh Mạng', 'tour-minh-mang', 'Nét đẹp uy nghiêm và thơ mộng.', NULL, 'active', NOW(), NOW()),
(79, 'Tour Lăng Tự Đức', 'tour-tu-duc', 'Vẻ đẹp u tịch và tinh tế.', NULL, 'active', NOW(), NOW()),
(80, 'Tour Chùa Thiên Mụ', 'tour-thien-mu', 'Ngôi chùa cổ nhất cố đô.', NULL, 'active', NOW(), NOW()),
(81, 'Tour Ca Huế Trên Sông Hương', 'tour-ca-hue', 'Thưởng thức nhã nhạc cung đình.', NULL, 'active', NOW(), NOW()),
(82, 'Tour Làng Hương Thủy Xuân', 'tour-thuy-xuan', 'Check-in cùng những bó hương rực rỡ.', NULL, 'active', NOW(), NOW()),
(83, 'Tour Bạch Mã Village', 'tour-bach-ma-vlg', 'Vùng đất của những chú lùn Hobbit.', NULL, 'active', NOW(), NOW()),
(84, 'Tour Đầm Lập An', 'tour-lap-an', 'Tuyệt tình cốc của miền Trung.', NULL, 'active', NOW(), NOW()),
(85, 'Tour Biển Lăng Cô', 'tour-lang-co', 'Một trong những vịnh biển đẹp nhất thế giới.', NULL, 'active', NOW(), NOW()),
(86, 'Tour Phá Tam Giang', 'tour-tam-giang', 'Trải nghiệm cuộc sống ngư dân vùng đầm phá.', NULL, 'active', NOW(), NOW()),
(87, 'Tour Suối Voi', 'tour-suoi-voi', 'Tắm suối và thưởng thức gà nướng.', NULL, 'active', NOW(), NOW()),
(88, 'Tour Hồ Truồi - Thiền Viện', 'tour-ho-truoi', 'Vẻ đẹp thanh tịnh giữa núi rừng.', NULL, 'active', NOW(), NOW()),
(89, 'Tour Lăng Cô - Hải Vân', 'tour-lang-co-hai-van', 'Hành trình chinh phục thiên hạ đệ nhất hùng quan.', NULL, 'active', NOW(), NOW()),
(90, 'Tour Suối Mơ Đà Nẵng', 'tour-suoi-mo', 'Nghỉ mát bên dòng suối trong xanh.', NULL, 'active', NOW(), NOW()),
(91, 'Tour Đèo Hải Vân Xe Máy', 'tour-hai-van-motor', 'Thử thách tay lái qua những cung đường đèo.', NULL, 'active', NOW(), NOW()),
(92, 'Tour Cù Lao Chàm 2 Ngày 1 Đêm', 'tour-cu-lao-2d1n', 'Trải nghiệm đêm trên đảo hoang sơ.', NULL, 'active', NOW(), NOW()),
(93, 'Tour Câu Mực Đêm Đà Nẵng', 'tour-cau-muc', 'Trải nghiệm làm ngư dân thực thụ ban đêm.', NULL, 'active', NOW(), NOW()),
(94, 'Tour Ngắm San Hô Hòn Sẹo', 'tour-hon-seo', 'Điểm lặn biển mới lạ tại Đà Nẵng.', NULL, 'active', NOW(), NOW()),
(95, 'Tour Làng Cổ Phong Nam', 'tour-phong-nam', 'Nét đẹp làng quê Việt giữa lòng thành phố.', NULL, 'active', NOW(), NOW()),
(96, 'Tour Thăm Lăng Bà Thu Bồn', 'tour-lang-ba', 'Lễ hội văn hóa tín ngưỡng độc đáo.', NULL, 'active', NOW(), NOW()),
(97, 'Tour Khám Phá Rừng Dừa Hội An', 'tour-coconut-forest', 'Trải nghiệm chèo thúng thú vị.', NULL, 'active', NOW(), NOW()),
(98, 'Tour Thăm Các Hội Quán Hội An', 'tour-guildhall', 'Tìm hiểu văn hóa các bang hội Hoa kiều.', NULL, 'active', NOW(), NOW()),
(99, 'Tour May Đồ Lấy Liền Hội An', 'tour-tailor', 'Trải nghiệm dịch vụ may đo nổi tiếng thế giới.', NULL, 'active', NOW(), NOW()),
(100, 'Tour Khám Phá Hang Gió', 'tour-hang-gio', 'Thử thách mạo hiểm tại danh thắng mới.', NULL, 'active', NOW(), NOW());

-- 2. BLOG_CATEGORIES (Target 100)
INSERT INTO blog_categories (id, name, slug, description, created_at, updated_at) VALUES
(1, 'Cẩm Nang Du Lịch', 'cam-nang-du-lich', 'Kinh nghiệm từ A-Z cho chuyến đi của bạn.', NULL, 'active', NOW(), NOW()),
(2, 'Review Ẩm Thực', 'review-am-thuc', 'Những quán ăn ngon nức tiếng không thể bỏ qua.', NULL, 'active', NOW(), NOW()),
(3, 'Địa Điểm Check-in', 'dia-diem-check-in', 'Tổng hợp những tọa độ sống ảo cực chất.', NULL, 'active', NOW(), NOW()),
(4, 'Tin Tức Du Lịch', 'tin-tuc-du-lich', 'Cập nhật các sự kiện, lễ hội mới nhất.', NULL, 'active', NOW(), NOW()),
(5, 'Lịch Trình Gợi Ý', 'lich-trinh-goi-y', 'Gợi ý lịch trình 3 ngày 2 đêm, 4 ngày 3 đêm.', NULL, 'active', NOW(), NOW()),
(6, 'Văn Hóa & Lịch Sử', 'van-hoa-lich-su', 'Tìm hiểu về nguồn gốc và truyền thống địa phương.', NULL, 'active', NOW(), NOW()),
(7, 'Mẹo Tiết Kiệm', 'meo-tiet-kiem', 'Cách du lịch Đà Nẵng với chi phí thấp nhất.', NULL, 'active', NOW(), NOW()),
(8, 'Review Khách Sạn', 'review-khach-san', 'Đánh giá chân thực về nơi lưu trú.', NULL, 'active', NOW(), NOW()),
(9, 'Kinh Nghiệm Phượt', 'kinh-nghiem-phuot', 'Dành cho những tâm hồn thích xê dịch bằng xe máy.', NULL, 'active', NOW(), NOW()),
(10, 'Quà Tặng Đặc Sản', 'qua-tang-dac-san', 'Mua gì về làm quà khi du lịch miền Trung?', NULL, 'active', NOW(), NOW()),
-- Adding 90 more blog categories to reach 100
(11, 'Du Lịch Theo Mùa', 'du-lich-theo-mua', 'Nên đi Đà Nẵng tháng mấy là đẹp nhất?', NULL, 'active', NOW(), NOW()),
(12, 'Review Tour Thực Tế', 'review-tour', 'Cảm nhận của khách hàng sau khi trải nghiệm tour.', NULL, 'active', NOW(), NOW()),
(13, 'Ảnh Đẹp Du Khách', 'anh-dep-du-khach', 'Góc nhìn du lịch qua ống kính khách hàng.', NULL, 'active', NOW(), NOW()),
(14, 'Hướng Dẫn Thủ Tục', 'huong-dan-thu-tuc', 'Visa, vé máy bay, bảo hiểm du lịch.', NULL, 'active', NOW(), NOW()),
(15, 'Góc Ảnh Nghệ Thuật', 'art-corner', 'Vẻ đẹp Đà Nẵng qua con mắt nhiếp ảnh gia.', NULL, 'active', NOW(), NOW()),
(16, 'Du Lịch Gia Đình', 'family-travel-tips', 'Mẹo nhỏ khi có trẻ em và người già đi cùng.', NULL, 'active', NOW(), NOW()),
(17, 'Hẹn Hò Lãng Mạn', 'romantic-date', 'Những điểm đến dành riêng cho các cặp đôi.', NULL, 'active', NOW(), NOW()),
(18, 'Du Lịch Một Mình (Solo)', 'solo-travel', 'An toàn và tự do khám phá theo cách của bạn.', NULL, 'active', NOW(), NOW()),
(19, 'Team Building Ideas', 'team-building-ideas', 'Các trò chơi và địa điểm tổ chức gắn kết.', NULL, 'active', NOW(), NOW()),
(20, 'Vlog Du Lịch', 'travel-vlog', 'Review qua video sinh động.', NULL, 'active', NOW(), NOW()),
(21, 'Podcast Du Lịch', 'travel-podcast', 'Nghe những câu chuyện xê dịch truyền cảm hứng.', NULL, 'active', NOW(), NOW()),
(22, 'Cẩm Nang Hội An', 'hoi-an-guide', 'Chuyên sâu về phố cổ và vùng ven.', NULL, 'active', NOW(), NOW()),
(23, 'Cẩm Nang Huế', 'hue-guide', 'Chuyên sâu về cố đô và các lăng tẩm.', NULL, 'active', NOW(), NOW()),
(24, 'Cẩm Nang Đà Nẵng', 'danang-guide', 'Chuyên sâu về thành phố đáng sống nhất.', NULL, 'active', NOW(), NOW()),
(25, 'Khám Phá Quảng Bình', 'quang-binh-guide', 'Hành trình hang động và biển Nhật Lệ.', NULL, 'active', NOW(), NOW()),
(26, 'Khám Phá Quảng Nam', 'quang-nam-guide', 'Bên ngoài Hội An còn gì thú vị?', NULL, 'active', NOW(), NOW()),
(27, 'Khám Phá Quảng Ngãi', 'quang-ngai-guide', 'Đảo Lý Sơn và biển Mỹ Khê (Quảng Ngãi).', NULL, 'active', NOW(), NOW()),
(28, 'Khám Phá Bình Định', 'binh-dinh-guide', 'Quy Nhơn - Thành phố thi ca.', NULL, 'active', NOW(), NOW()),
(29, 'Khám Phá Phú Yên', 'phu-yen-guide', 'Xứ sở hoa vàng trên cỏ xanh.', NULL, 'active', NOW(), NOW()),
(30, 'Phương Tiện Di Chuyển', 'transport-guide', 'Thuê xe máy, Grab hay xe buýt?', NULL, 'active', NOW(), NOW()),
(31, 'Du Lịch Bền Vững', 'sustainable-travel', 'Hạn chế rác thải nhựa khi đi du lịch.', NULL, 'active', NOW(), NOW()),
(32, 'Công Nghệ Du Lịch', 'travel-tech', 'Ứng dụng cần thiết cho chuyến đi của bạn.', NULL, 'active', NOW(), NOW()),
(33, 'Phỏng Vấn Người Bản Địa', 'local-interview', 'Lắng nghe những câu chuyện chưa kể.', NULL, 'active', NOW(), NOW()),
(34, 'Top 10 Đà Nẵng', 'top-10-danang', 'Bảng xếp hạng các dịch vụ tốt nhất.', NULL, 'active', NOW(), NOW()),
(35, 'Góc Khuất Đà Nẵng', 'hidden-danang', 'Những điểm đến ít người biết nhưng cực đẹp.', NULL, 'active', NOW(), NOW()),
(36, 'Chụp Ảnh Đường Phố', 'street-photography', 'Bắt trọn khoảnh khắc đời thường.', NULL, 'active', NOW(), NOW()),
(37, 'Thời Trang Du Lịch', 'travel-fashion', 'Mặc gì để có những bức ảnh lung linh?', NULL, 'active', NOW(), NOW()),
(38, 'Sức Khỏe Chuyến Đi', 'travel-health', 'Phòng tránh say nắng và các bệnh thường gặp.', NULL, 'active', NOW(), NOW()),
(39, 'Ẩm Thực Chay', 'vegan-food-guide', 'Những địa chỉ ăn chay ngon tại miền Trung.', NULL, 'active', NOW(), NOW()),
(40, 'Đồ Uống & Cafe', 'drink-cafe-review', 'Tiệm cafe đẹp, quán bar sôi động.', NULL, 'active', NOW(), NOW()),
(41, 'Chợ & Mua Sắm', 'market-shopping', 'Trải nghiệm mua sắm tại chợ truyền thống.', NULL, 'active', NOW(), NOW()),
(42, 'Lễ Hội Pháo Hoa', 'diff-news', 'Cập nhật thông tin DIFF hàng năm.', NULL, 'active', NOW(), NOW()),
(43, 'Sự Kiện Thể Thao', 'sports-events', 'Marathon, Ironman và các giải đấu lớn.', NULL, 'active', NOW(), NOW()),
(44, 'Nghệ Thuật Biểu Diễn', 'performance-art', 'Ký ức Hội An, Show Charming Danang.', NULL, 'active', NOW(), NOW()),
(45, 'Kiến Trúc & Đô Thị', 'architecture-urban', 'Sự phát triển của các cây cầu và tòa nhà.', NULL, 'active', NOW(), NOW()),
(46, 'Đời Sống Cư Dân', 'local-life', 'Tìm hiểu phong tục tập quán người miền Trung.', NULL, 'active', NOW(), NOW()),
(47, 'Góc Review Homestay', 'homestay-review', 'Ấm cúng như ở nhà.', NULL, 'active', NOW(), NOW()),
(48, 'Góc Review Resort', 'resort-review', 'Xứng tầm đẳng cấp quốc tế.', NULL, 'active', NOW(), NOW()),
(49, 'Góc Review Villa', 'villa-review', 'Không gian nghỉ dưỡng gia đình hoàn hảo.', NULL, 'active', NOW(), NOW()),
(50, 'Góc Review Hostel', 'hostel-review', 'Dành cho dân du lịch bụi (Backpackers).', NULL, 'active', NOW(), NOW()),
-- Synthetic categories 51-100 to meet volume
(51, 'Kinh Nghiệm Săn Vé Rẻ', 'cheap-flight-tips', 'Mẹo săn vé máy bay giá hời.', NULL, 'active', NOW(), NOW()),
(52, 'Du Lịch Tâm Linh Cẩm Nang', 'spiritual-guide', 'Hướng dẫn hành hương tại các ngôi chùa lớn.', NULL, 'active', NOW(), NOW()),
(53, 'Khám Phá Sông Hàn', 'song-han-exploration', 'Vẻ đẹp dòng sông biểu tượng thành phố.', NULL, 'active', NOW(), NOW()),
(54, 'Review Spa & Wellness', 'spa-wellness-review', 'Địa chỉ thư giãn tốt nhất.', NULL, 'active', NOW(), NOW()),
(55, 'Hướng Dẫn Đi Bà Nà Hills', 'ba-na-hills-tips', 'Làm sao để không bị lạc và chơi hết các trò?', NULL, 'active', NOW(), NOW()),
(56, 'Hướng Dẫn Đi Hội An', 'hoi-an-tips', 'Góc chụp ảnh đẹp và quán ăn ngon.', NULL, 'active', NOW(), NOW()),
(57, 'Hướng Dẫn Đi Cố Đô Huế', 'hue-tips', 'Lịch trình tham quan các lăng tẩm hiệu quả.', NULL, 'active', NOW(), NOW()),
(58, 'Khám Phá Đèo Hải Vân', 'hai-van-tips', 'Những điểm dừng chân không thể bỏ qua.', NULL, 'active', NOW(), NOW()),
(59, 'Khám Phá Bán Đảo Sơn Trà', 'son-tra-tips', 'Tìm hiểu về Voọc chà vá chân nâu.', NULL, 'active', NOW(), NOW()),
(60, 'Review Nhà Hàng Hải Sản', 'seafood-restaurant-review', 'Tươi ngon và giá cả phải chăng.', NULL, 'active', NOW(), NOW()),
(61, 'Cẩm Nang Quà Lưu Niệm', 'souvenir-guide', 'Những món đồ ý nghĩa nên mua.', NULL, 'active', NOW(), NOW()),
(62, 'Review Quán Cafe Làm Việc', 'work-cafe-review', 'Không gian yên tĩnh, wifi mạnh.', NULL, 'active', NOW(), NOW()),
(63, 'Kinh Nghiệm Đi Cù Lao Chàm', 'cu-lao-cham-tips', 'Lưu ý về môi trường và an toàn biển.', NULL, 'active', NOW(), NOW()),
(64, 'Review Các Bãi Biển', 'beach-review', 'Mỹ Khê, Non Nước hay Thanh Khê?', NULL, 'active', NOW(), NOW()),
(65, 'Review Chợ Cồn', 'cho-con-review', 'Thiên đường ăn vặt lớn nhất Đà Nẵng.', NULL, 'active', NOW(), NOW()),
(66, 'Review Chợ Hàn', 'cho-han-review', 'Địa điểm mua sắm đặc sản làm quà.', NULL, 'active', NOW(), NOW()),
(67, 'Review Chợ Đêm Helio', 'helio-market-review', 'Không khí sôi động và ẩm thực đa dạng.', NULL, 'active', NOW(), NOW()),
(68, 'Review Chợ Đêm Sơn Trà', 'son-tra-market-review', 'Mua sắm và dạo phố đêm.', NULL, 'active', NOW(), NOW()),
(69, 'Khám Phá Công Viên APEC', 'apec-park-review', 'Kiến trúc cánh diều độc đáo.', NULL, 'active', NOW(), NOW()),
(70, 'Khám Phá Cầu Vàng', 'golden-bridge-review', 'Biểu tượng du lịch mới của Việt Nam.', NULL, 'active', NOW(), NOW()),
(71, 'Khám Phá Cầu Rồng', 'dragon-bridge-review', 'Lịch phun lửa và phun nước.', NULL, 'active', NOW(), NOW()),
(72, 'Khám Phá Cầu Sông Hàn', 'song-han-bridge-review', 'Lịch quay của cây cầu độc nhất.', NULL, 'active', NOW(), NOW()),
(73, 'Khám Phá Cầu Thuận Phước', 'thuan-phuoc-bridge-review', 'Cây cầu dây văng dài nhất Việt Nam.', NULL, 'active', NOW(), NOW()),
(74, 'Khám Phá Cầu Trần Thị Lý', 'tran-thi-ly-bridge-review', 'Hình dáng cánh buồm vươn ra biển lớn.', NULL, 'active', NOW(), NOW()),
(75, 'Review Bảo Tàng Chăm', 'cham-museum-review', 'Nơi lưu giữ tinh hoa văn hóa Chăm Pa.', NULL, 'active', NOW(), NOW()),
(76, 'Review Bảo Tàng Đà Nẵng', 'danang-museum-review', 'Tìm hiểu lịch sử hình thành thành phố.', NULL, 'active', NOW(), NOW()),
(77, 'Review Bảo Tàng Mỹ Thuật', 'art-museum-review', 'Không gian nghệ thuật đương đại.', NULL, 'active', NOW(), NOW()),
(78, 'Review Nhà Trưng Bày Hoàng Sa', 'hoang-sa-museum-review', 'Minh chứng chủ quyền biển đảo.', NULL, 'active', NOW(), NOW()),
(79, 'Kinh Nghiệm Đi Ngũ Hành Sơn', 'marble-mountain-tips', 'Tham quan hang động và chùa chiền.', NULL, 'active', NOW(), NOW()),
(80, 'Review Làng Đá Non Nước', 'non-nuoc-stone-review', 'Nghệ thuật điêu khắc đá tinh xảo.', NULL, 'active', NOW(), NOW()),
(81, 'Kinh Nghiệm Đi Thánh Địa Mỹ Sơn', 'my-son-tips', 'Hành trình tìm về quá khứ.', NULL, 'active', NOW(), NOW()),
(82, 'Review Vinpearl River Safari', 'river-safari-review', 'Tham quan thú bằng thuyền độc đáo.', NULL, 'active', NOW(), NOW()),
(83, 'Review VinWonders Games', 'vinwonders-games-review', 'Các trò chơi cảm giác mạnh hấp dẫn.', NULL, 'active', NOW(), NOW()),
(84, 'Kinh Nghiệm Đi Núi Thần Tài', 'than-tai-mountain-tips', 'Tắm khoáng nóng và vui chơi.', NULL, 'active', NOW(), NOW()),
(85, 'Review Tắm Bùn Galina', 'galina-mud-bath-review', 'Thư giãn ngay trong lòng thành phố.', NULL, 'active', NOW(), NOW()),
(86, 'Review Tắm Bùn Phước Nhơn', 'phuoc-nhon-mud-bath-review', 'Suối khoáng nóng tự nhiên.', NULL, 'active', NOW(), NOW()),
(87, 'Review Asian Park (Công Viên Châu Á)', 'asian-park-review', 'Vòng quay mặt trời và các khu văn hóa.', NULL, 'active', NOW(), NOW()),
(88, 'Kinh Nghiệm Đi Hòa Phú Thành', 'hoa-phu-thanh-tips', 'Trượt thác và massage cá.', NULL, 'active', NOW(), NOW()),
(89, 'Review Suối Hoa', 'suoi-hoa-review', 'Vẻ đẹp thiên nhiên mộc mạc.', NULL, 'active', NOW(), NOW()),
(90, 'Review Ngầm Đôi', 'ngam-doi-review', 'Điểm dã ngoại lý tưởng mùa hè.', NULL, 'active', NOW(), NOW()),
(91, 'Cẩm Nang Ăn Sáng Đà Nẵng', 'breakfast-danang-guide', 'Mì quảng, bún chả cá, xôi gà.', NULL, 'active', NOW(), NOW()),
(92, 'Cẩm Nang Ăn Trưa Đà Nẵng', 'lunch-danang-guide', 'Cơm niêu, bánh tráng cuốn thịt heo.', NULL, 'active', NOW(), NOW()),
(93, 'Cẩm Nang Ăn Tối Đà Nẵng', 'dinner-danang-guide', 'Hải sản, lẩu, đồ nướng.', NULL, 'active', NOW(), NOW()),
(94, 'Cẩm Nang Ăn Đêm Đà Nẵng', 'late-night-danang-guide', 'Bún xương, bánh canh ruộng.', NULL, 'active', NOW(), NOW()),
(95, 'Review Quán Bánh Mì Đà Nẵng', 'banh-mi-danang-review', 'Bánh mì bà Lan, bánh mì gà.', NULL, 'active', NOW(), NOW()),
(96, 'Review Quán Chè Đà Nẵng', 'che-danang-review', 'Chè Liên, chè Xuân Trang.', NULL, 'active', NOW(), NOW()),
(97, 'Review Quán Kem Đà Nẵng', 'kem-danang-review', 'Kem bơ cô Vân chợ Bắc Mỹ An.', NULL, 'active', NOW(), NOW()),
(98, 'Review Quán Nhậu Đà Nẵng', 'nhau-danang-review', 'Bình dân và ven biển.', NULL, 'active', NOW(), NOW()),
(99, 'Review Quán Bar Rooftop', 'rooftop-bar-review', 'Sky36, Brilliant Top Bar.', NULL, 'active', NOW(), NOW()),
(100, 'Review Quán Cafe View Sông', 'river-view-cafe-review', 'Góc nhìn lung linh về đêm.', NULL, 'active', NOW(), NOW());
