-- DanangTrip Real Data Seeder: Tour & Blog Categories (100 each)
-- Source: Viator, G Adventures, Nomadic Matt, The Blonde Abroad
-- Retrieved Date: 2026-04-29

-- [SOURCE_SUMMARY]
-- Viator (Tripadvisor) Category Taxonomy
-- G Adventures / Intrepid Travel Trip Styles
-- Nomadic Matt / The Blonde Abroad Blog Categories

-- [LOOKUP_TABLES]
-- TOUR_CATEGORY_LOOKUP: Nghỉ dưỡng -> 1, ...
-- BLOG_CATEGORY_LOOKUP: Điểm đến -> 1, ...

-- 1. TOUR_CATEGORIES (Target 100)
INSERT INTO tour_categories (id, name, slug, description, icon, sort_order, status, created_at, updated_at) VALUES
(1, 'Nghỉ dưỡng & Bãi biển', 'nghi-duong-bai-bien', 'Thư giãn tại các bãi biển đẹp và resort cao cấp.', 'beach_access', 1, 'active', NOW(), NOW()),
(2, 'Văn hóa & Lịch sử', 'van-hoa-lich-su', 'Khám phá các di sản, bảo tàng và di tích lịch sử.', 'history', 2, 'active', NOW(), NOW()),
(3, 'Ẩm thực & Đồ uống', 'am-thuc-do-uong', 'Trải nghiệm ẩm thực địa phương, lớp học nấu ăn và tour nếm rượu.', 'restaurant', 3, 'active', NOW(), NOW()),
(4, 'Mạo hiểm & Hoạt động ngoài trời', 'mao-hiem-ngoai-troi', 'Leo núi, chèo thuyền, vượt thác và các hoạt động cảm giác mạnh.', 'hiking', 4, 'active', NOW(), NOW()),
(5, 'Sinh thái & Thiên nhiên', 'sinh-thai-thien-nhien', 'Khám phá vườn quốc gia, bảo tồn động vật hoang dã.', 'eco', 5, 'active', NOW(), NOW()),
(6, 'Tâm linh & Hành hương', 'tam-linh-hanh-huong', 'Thăm viếng các ngôi chùa, nhà thờ và vùng đất thánh.', 'temple_hindu', 6, 'active', NOW(), NOW()),
(7, 'Chữa lành & Sức khỏe (Wellness)', 'wellness-healing', 'Yoga, thiền, spa và trị liệu phục hồi sức khỏe.', 'spa', 7, 'active', NOW(), NOW()),
(8, 'MICE & Sự kiện', 'mice-event', 'Du lịch kết hợp hội nghị, hội thảo và khen thưởng doanh nghiệp.', 'groups', 8, 'active', NOW(), NOW()),
(9, 'Nhiếp ảnh (Photography)', 'photography-tour', 'Lịch trình thiết kế riêng cho những người đam mê nhiếp ảnh.', 'camera_alt', 9, 'active', NOW(), NOW()),
(10, 'Tình nguyện (Voluntourism)', 'voluntourism', 'Kết hợp tham quan với các hoạt động hỗ trợ cộng đồng.', 'volunteer_activism', 10, 'active', NOW(), NOW()),
(11, 'Du lịch Tối (Dark Tourism)', 'dark-tourism', 'Thăm các địa điểm liên quan đến thảm họa hoặc sự kiện lịch sử bi thương.', 'visibility_off', 11, 'active', NOW(), NOW()),
(12, 'Cho người cao tuổi (Senior)', 'senior-tour', 'Lịch trình chậm rãi, dịch vụ hỗ trợ tối đa cho người lớn tuổi.', 'elderly', 12, 'active', NOW(), NOW()),
(13, 'Tiếp cận (Accessible)', 'accessible-tour', 'Thiết kế cho người khuyết tật với cơ sở vật chất hỗ trợ.', 'accessible', 13, 'active', NOW(), NOW()),
(14, 'Nữ độc hành (Solo Female)', 'solo-female-travel', 'An toàn và trải nghiệm dành riêng cho phụ nữ đi một mình.', 'woman', 14, 'active', NOW(), NOW()),
(15, 'Yoga Retreat', 'yoga-retreat', 'Tập trung rèn luyện thân thể và tâm trí tại không gian yên tĩnh.', 'self_improvement', 15, 'active', NOW(), NOW()),
(16, 'Nếm rượu vang (Wine Tasting)', 'wine-tasting', 'Tham quan hầm rượu và vườn nho.', 'wine_bar', 16, 'active', NOW(), NOW()),
(17, 'Sang trọng (Luxury)', 'luxury-travel-tour', 'Dịch vụ 5 sao, phi cơ riêng và cá nhân hóa tối đa.', 'diamond', 17, 'active', NOW(), NOW()),
(18, 'Tiết kiệm (Budget/Backpacker)', 'budget-backpacker', 'Trải nghiệm du lịch với chi phí tối thiểu.', 'savings', 18, 'active', NOW(), NOW()),
(19, 'Quan sát động vật hoang dã', 'wildlife-watching', 'Xem động vật trong môi trường tự nhiên (Safari).', 'pets', 19, 'active', NOW(), NOW()),
(20, 'Trekking & Hiking', 'trekking-hiking', 'Khám phá cung đường rừng núi bằng đường bộ.', 'terrain', 20, 'active', NOW(), NOW()),
(21, 'Đạp xe (Cycling)', 'cycling-tour', 'Khám phá các cung đường bằng xe đạp.', 'pedal_bike', 21, 'active', NOW(), NOW()),
(22, 'Du thuyền (Cruise)', 'cruise-tour', 'Nghỉ dưỡng trên tàu thủy sang trọng.', 'directions_boat', 22, 'active', NOW(), NOW()),
(23, 'Đường sắt (Rail Travel)', 'rail-travel', 'Trải nghiệm du lịch bằng tàu hỏa xuyên quốc gia.', 'train', 23, 'active', NOW(), NOW()),
(24, 'Tour 18-35s', 'youth-tour', 'Thiết kế cho giới trẻ với hoạt động sôi nổi.', 'celebration', 24, 'active', NOW(), NOW()),
(25, 'Safari', 'safari-tour', 'Thăm các khu bảo tồn thiên nhiên hoang dã.', 'agriculture', 25, 'active', NOW(), NOW()),
(26, 'Thể thao mùa đông', 'winter-sports', 'Trượt tuyết, leo núi băng.', 'ac_unit', 26, 'active', NOW(), NOW()),
(27, 'Lặn biển (Diving)', 'diving-tour', 'Khám phá thế giới dưới lòng đại dương.', 'scuba_diving', 27, 'active', NOW(), NOW()),
(28, 'Học thuật & Giáo dục', 'educational-tour', 'Du lịch kết hợp học tập và nghiên cứu.', 'school', 28, 'active', NOW(), NOW()),
(29, 'Hàng không (Air Travel)', 'air-tour', 'Tham quan bằng trực thăng, khinh khí cầu.', 'flight', 29, 'active', NOW(), NOW()),
(30, 'Phượt xe máy', 'motorbike-tour', 'Trải nghiệm cung đường bằng xe máy.', 'motorcycle', 30, 'active', NOW(), NOW()),
(31, 'Du lịch theo đoàn (Group)', 'group-tour', 'Lịch trình cố định, khởi hành theo lịch.', 'groups', 31, 'active', NOW(), NOW()),
(32, 'Du lịch cá nhân (Private)', 'private-tour', 'Thiết kế riêng theo yêu cầu cá nhân hoặc gia đình.', 'person', 32, 'active', NOW(), NOW()),
(33, 'Trăng mật (Honeymoon)', 'honeymoon-tour', 'Dành riêng cho các cặp đôi mới cưới.', 'favorite', 33, 'active', NOW(), NOW()),
(34, 'Gia đình (Family)', 'family-tour', 'Lịch trình phù hợp cho nhiều thế hệ.', 'family_restroom', 34, 'active', NOW(), NOW()),
(35, 'Cắm trại (Camping)', 'camping-tour', 'Ngủ lều và sinh hoạt ngoài trời.', 'tent', 35, 'active', NOW(), NOW()),
(36, 'Du lịch Thành phố (City Break)', 'city-break', 'Khám phá ngắn ngày tại các đô thị lớn.', 'apartment', 36, 'active', NOW(), NOW()),
(37, 'Thám hiểm Hang động', 'caving-tour', 'Khám phá các hệ thống hang động kỳ vĩ.', 'vignette', 37, 'active', NOW(), NOW()),
(38, 'Chèo Kayak / SUP', 'paddling-tour', 'Hoạt động thể thao trên mặt nước.', 'kayaking', 38, 'active', NOW(), NOW()),
(39, 'Câu cá (Fishing)', 'fishing-tour', 'Trải nghiệm câu cá giải trí.', 'phishing', 39, 'active', NOW(), NOW()),
(40, 'Lướt ván (Surfing)', 'surfing-tour', 'Chinh phục những con sóng.', 'surfing', 40, 'active', NOW(), NOW()),
(41, 'Golf Tour', 'golf-tour', 'Kết hợp du lịch với chơi Golf chuyên nghiệp.', 'sports_golf', 41, 'active', NOW(), NOW()),
(42, 'Xem chim (Bird Watching)', 'bird-watching', 'Dành cho những người yêu thích điểu học.', 'flutter_dash', 42, 'active', NOW(), NOW()),
(43, 'Du lịch Thiên văn', 'astronomy-tour', 'Ngắm sao và các hiện tượng vũ trụ.', 'auto_awesome', 43, 'active', NOW(), NOW()),
(44, 'Tour thực tế ảo (VR)', 'vr-tour', 'Trải nghiệm du lịch qua công nghệ số.', 'view_in_ar', 44, 'active', NOW(), NOW()),
(45, 'Du lịch Nông nghiệp (Agritourism)', 'agritourism', 'Tham quan trang trại và trải nghiệm làm nông.', 'agriculture', 45, 'active', NOW(), NOW()),
(46, 'Nghệ thuật & Sáng tạo', 'creative-tour', 'Tham gia các lớp vẽ, làm đồ thủ công.', 'palette', 46, 'active', NOW(), NOW()),
(47, 'Tour Mua sắm (Shopping)', 'shopping-tour', 'Ghé thăm các trung tâm thương mại và chợ nổi tiếng.', 'shopping_bag', 47, 'active', NOW(), NOW()),
(48, 'Du lịch Marathon / Thể thao', 'sports-event-tour', 'Tham dự các giải chạy hoặc trận đấu lớn.', 'run_circle', 48, 'active', NOW(), NOW()),
(49, 'Tour Bí ẩn (Mystery Tour)', 'mystery-tour', 'Điểm đến được giữ bí mật đến phút chót.', 'help', 49, 'active', NOW(), NOW()),
(50, 'Thám hiểm Bắc/Nam Cực', 'polar-expedition', 'Hành trình đến những vùng đất lạnh giá nhất.', 'ac_unit', 50, 'active', NOW(), NOW()),
(51, 'Tour Cà phê', 'coffee-tour', 'Tìm hiểu quy trình từ trang trại đến tách cà phê.', 'coffee', 51, 'active', NOW(), NOW()),
(52, 'Du lịch Bền vững', 'sustainable-tour', 'Giảm thiểu tác động môi trường khi di chuyển.', 'recycling', 52, 'active', NOW(), NOW()),
(53, 'Học ngoại ngữ tại nước ngoài', 'language-learning-tour', 'Kết hợp học tiếng với giao lưu văn hóa.', 'translate', 53, 'active', NOW(), NOW()),
(54, 'Tour Kiến trúc', 'architecture-tour', 'Tìm hiểu các phong cách thiết kế độc đáo.', 'architecture', 54, 'active', NOW(), NOW()),
(55, 'Hành trình xuyên Việt', 'trans-vietnam', 'Khám phá trọn vẹn dải đất hình chữ S.', 'map', 55, 'active', NOW(), NOW()),
(56, 'Tour di sản UNESCO', 'unesco-heritage-tour', 'Chuyên sâu các điểm đến được UNESCO công nhận.', 'account_balance', 56, 'active', NOW(), NOW()),
(57, 'Du lịch bằng xe tự lái (Road Trip)', 'road-trip', 'Tự do di chuyển trên các cung đường đẹp.', 'directions_car', 57, 'active', NOW(), NOW()),
(58, 'Tour Ngắm Pháo hoa', 'fireworks-tour', 'Xem các màn trình diễn ánh sáng đặc sắc.', 'celebration', 58, 'active', NOW(), NOW()),
(59, 'Du lịch sông nước (River Cruise)', 'river-cruise', 'Khám phá cuộc sống ven sông.', 'sailing', 59, 'active', NOW(), NOW()),
(60, 'Tour tìm hiểu chiến trường xưa', 'battlefield-tour', 'Dành cho những người muốn tìm hiểu về quân sự.', 'military_tech', 60, 'active', NOW(), NOW()),
(61, 'Du lịch Wellness & Detox', 'wellness-detox', 'Thanh lọc cơ thể và cân bằng tâm trí.', 'self_improvement', 61, 'active', NOW(), NOW()),
(62, 'Tour dạy nấu ăn chuyên sâu', 'cooking-masterclass', 'Học cùng các đầu bếp chuyên nghiệp.', 'soup_kitchen', 62, 'active', NOW(), NOW()),
(63, 'Tour săn cực quang', 'aurora-hunting', 'Trải nghiệm hiện tượng ánh sáng kỳ thú.', 'flare', 63, 'active', NOW(), NOW()),
(64, 'Du lịch Đảo (Island Hopping)', 'island-hopping', 'Di chuyển giữa các hòn đảo trong một hành trình.', 'beach_access', 64, 'active', NOW(), NOW()),
(65, 'Tour lễ hội truyền thống', 'traditional-festival-tour', 'Tham dự các lễ hội bản địa đặc sắc.', 'festival', 65, 'active', NOW(), NOW()),
(66, 'Du lịch theo mùa (Hoa nở/Lá vàng)', 'seasonal-tour', 'Ngắm hoa anh đào, hoa tam giác mạch, lá đỏ.', 'park', 66, 'active', NOW(), NOW()),
(67, 'Tour khám phá Sa mạc', 'desert-safari', 'Trải nghiệm trên cát và đêm sa mạc.', 'wb_sunny', 67, 'active', NOW(), NOW()),
(68, 'Du lịch chậm (Slow Travel)', 'slow-travel', 'Dành nhiều thời gian hơn để cảm nhận một nơi.', 'potted_plant', 68, 'active', NOW(), NOW()),
(69, 'Tour Di sản ẩm thực', 'food-heritage-tour', 'Tìm về nguồn gốc các món ăn cổ truyền.', 'restaurant_menu', 69, 'active', NOW(), NOW()),
(70, 'Du lịch bằng xe Caravan', 'caravan-tour', 'Đoàn xe tự lái cùng di chuyển xuyên quốc gia.', 'rv_hookup', 70, 'active', NOW(), NOW()),
(71, 'Tour thiện nguyện dạy học', 'teaching-volunteer-tour', 'Hỗ trợ giáo dục tại vùng cao/vùng xa.', 'school', 71, 'active', NOW(), NOW()),
(72, 'Du lịch tâm linh & Thiền định', 'meditation-spiritual', 'Tập trung vào sự tĩnh lặng nội tâm.', 'spa', 72, 'active', NOW(), NOW()),
(73, 'Tour đường phố (Walking Street Food)', 'street-food-walking', 'Khám phá các ngõ ngách và món ăn vỉa hè.', 'directions_run', 73, 'active', NOW(), NOW()),
(74, 'Du lịch di sản công nghiệp', 'industrial-heritage', 'Thăm các nhà máy, hầm mỏ cũ đã chuyển đổi.', 'factory', 74, 'active', NOW(), NOW()),
(75, 'Tour bảo tồn san hô', 'coral-conservation-tour', 'Tham gia hoạt động trồng và bảo vệ san hô.', 'scuba_diving', 75, 'active', NOW(), NOW()),
(76, 'Du lịch bằng khí cầu', 'hot-air-balloon-tour', 'Tầm nhìn tuyệt đẹp từ trên cao.', 'air', 76, 'active', NOW(), NOW()),
(77, 'Tour theo dấu chân phim ảnh', 'film-location-tour', 'Ghé thăm các bối cảnh phim nổi tiếng.', 'movie', 77, 'active', NOW(), NOW()),
(78, 'Du lịch kết hợp làm đẹp', 'medical-beauty-tourism', 'Thẩm mỹ và chăm sóc sắc đẹp tại nước ngoài.', 'content_cut', 78, 'active', NOW(), NOW()),
(79, 'Tour trà đạo quốc tế', 'international-tea-tour', 'Khám phá văn hóa trà tại Nhật, Trung, Việt.', 'emoji_food_beverage', 79, 'active', NOW(), NOW()),
(80, 'Du lịch không rác thải', 'zero-waste-travel', 'Trải nghiệm du lịch 100% thân thiện môi trường.', 'recycling', 80, 'active', NOW(), NOW()),
(81, 'Tour xe Jeep thám hiểm', 'jeep-expedition', 'Chinh phục các địa hình khó bằng xe Jeep.', 'directions_car', 81, 'active', NOW(), NOW()),
(82, 'Du lịch vùng cao (Highland)', 'highland-tour', 'Khám phá núi rừng và các dân tộc thiểu số.', 'terrain', 82, 'active', NOW(), NOW()),
(83, 'Tour săn ảnh động vật đêm', 'night-wildlife-tour', 'Sử dụng thiết bị chuyên dụng quan sát về đêm.', 'visibility', 83, 'active', NOW(), NOW()),
(84, 'Du lịch sông băng (Glacier)', 'glacier-tour', 'Khám phá những khối băng khổng lồ.', 'ac_unit', 84, 'active', NOW(), NOW()),
(85, 'Tour lặn ngắm xác tàu đắm', 'shipwreck-diving', 'Dành cho những thợ lặn chuyên nghiệp.', 'scuba_diving', 85, 'active', NOW(), NOW()),
(86, 'Du lịch vùng núi lửa', 'volcano-tour', 'Thăm các ngọn núi lửa còn hoặc đã tắt.', 'fireplace', 86, 'active', NOW(), NOW()),
(87, 'Tour thám hiểm rừng nhiệt đới', 'jungle-expedition', 'Sinh tồn và khám phá đa dạng sinh học.', 'forest', 87, 'active', NOW(), NOW()),
(88, 'Du lịch kết hợp chơi Poker/Casino', 'casino-tourism', 'Giải trí tại các sòng bài nổi tiếng.', 'casino', 88, 'active', NOW(), NOW()),
(89, 'Tour học làm gốm / Thủ công', 'pottery-craft-tour', 'Trải nghiệm các làng nghề truyền thống.', 'handyman', 89, 'active', NOW(), NOW()),
(90, 'Du lịch thưởng thức phô mai', 'cheese-tasting-tour', 'Phổ biến tại các nước Châu Âu.', 'bakery_dining', 90, 'active', NOW(), NOW()),
(91, 'Tour đi bộ ban đêm (Night Walk)', 'night-walking-tour', 'Cảm nhận vẻ đẹp thành phố khi lên đèn.', 'nightlight', 91, 'active', NOW(), NOW()),
(92, 'Du lịch bằng xe lôi / Tuk-tuk', 'tuk-tuk-experience', 'Văn hóa di chuyển đặc trưng Đông Nam Á.', 'directions_run', 92, 'active', NOW(), NOW()),
(93, 'Tour thăm các vườn bách thảo', 'botanical-garden-tour', 'Dành cho những người yêu thực vật.', 'eco', 93, 'active', NOW(), NOW()),
(94, 'Du lịch trải nghiệm cuộc sống bộ lạc', 'tribal-experience', 'Sống cùng và học hỏi từ các bộ lạc nguyên sơ.', 'groups', 94, 'active', NOW(), NOW()),
(95, 'Tour lặn cùng cá mập', 'shark-diving', 'Trải nghiệm cảm giác mạnh dưới đại dương.', 'scuba_diving', 95, 'active', NOW(), NOW()),
(96, 'Du lịch bằng trực thăng ngắm cảnh', 'helicopter-sightseeing', 'Trải nghiệm xa xỉ với góc nhìn 360 độ.', 'flight', 96, 'active', NOW(), NOW()),
(97, 'Tour khám phá di sản âm nhạc', 'music-heritage-tour', 'Ghé thăm quê hương các huyền thoại âm nhạc.', 'music_note', 97, 'active', NOW(), NOW()),
(98, 'Du lịch kết hợp học Yoga nổi (SUP Yoga)', 'sup-yoga-tour', 'Thử thách thăng bằng trên mặt nước.', 'self_improvement', 98, 'active', NOW(), NOW()),
(99, 'Tour ngắm cá voi / cá heo', 'whale-watching', 'Quan sát các loài động vật biển khổng lồ.', 'water', 99, 'active', NOW(), NOW()),
(100, 'Tour khám phá ngầm đô thị', 'urban-underground', 'Thăm hệ thống tàu điện, hầm ngầm cổ.', 'subway', 100, 'active', NOW(), NOW());

-- 2. BLOG_CATEGORIES (Target 100)
INSERT INTO blog_categories (id, name, slug, description, created_at, updated_at) VALUES
(1, 'Điểm đến thế giới', 'diem-den-the-gioi', 'Thông tin chi tiết về các quốc gia và thành phố.', NOW(), NOW()),
(2, 'Kinh nghiệm du lịch', 'kinh-nghiem-du-lich-blog', 'Các mẹo hữu ích để chuyến đi suôn sẻ hơn.', NOW(), NOW()),
(3, 'Quản lý ngân sách', 'quan-ly-ngan-sach', 'Cách tiết kiệm tiền và chi tiêu thông minh.', NOW(), NOW()),
(4, 'Du lịch độc hành', 'du-lich-doc-hanh', 'Cảm hứng cho những người thích đi một mình.', NOW(), NOW()),
(5, 'Du mục kỹ thuật số', 'digital-nomad-blog', 'Lối sống làm việc từ xa khi đang di chuyển.', NOW(), NOW()),
(6, 'Cuộc sống định cư (Expat)', 'expat-life', 'Kinh nghiệm sống và làm việc tại nước ngoài.', NOW(), NOW()),
(7, 'Học ngôn ngữ', 'hoc-ngon-ngu', 'Bí quyết giao tiếp cơ bản với người bản địa.', NOW(), NOW()),
(8, 'Du lịch bền vững', 'sustainable-travel-blog', 'Cách đi du lịch thân thiện với môi trường.', NOW(), NOW()),
(9, 'Đồ nghề du lịch', 'travel-gear-blog', 'Đánh giá vali, balo, máy ảnh và phụ kiện.', NOW(), NOW()),
(10, 'Danh sách đồ cần mang', 'packing-lists', 'Gợi ý trang phục cho từng loại chuyến đi.', NOW(), NOW()),
(11, 'Lịch trình gợi ý', 'itineraries-blog', 'Kế hoạch tham quan chi tiết theo ngày.', NOW(), NOW()),
(12, 'Ẩm thực & Đồ uống', 'food-drink-blog', 'Review quán ăn và đặc sản địa phương.', NOW(), NOW()),
(13, 'Văn hóa & Lịch sử', 'culture-history-blog', 'Kiến thức về con người và quá khứ vùng miền.', NOW(), NOW()),
(14, 'Du lịch mạo hiểm', 'adventure-travel-blog', 'Chia sẻ về các hoạt động ngoài trời thử thách.', NOW(), NOW()),
(15, 'Du lịch sang trọng', 'luxury-travel-blog', 'Review khách sạn và dịch vụ cao cấp.', NOW(), NOW()),
(16, 'Du lịch gia đình', 'family-travel-blog', 'Kinh nghiệm đi cùng con nhỏ và người già.', NOW(), NOW()),
(17, 'Nhiếp ảnh du lịch', 'travel-photography-blog', 'Cách chụp và chỉnh sửa ảnh đẹp.', NOW(), NOW()),
(18, 'Viết blog du lịch', 'travel-blogging-tips', 'Hướng dẫn xây dựng và phát triển blog.', NOW(), NOW()),
(19, 'Làm việc tại nước ngoài', 'working-abroad-blog', 'Cơ hội nghề nghiệp toàn cầu.', NOW(), NOW()),
(20, 'Hoạt động tình nguyện', 'volunteering-blog', 'Tìm hiểu các dự án thiện nguyện quốc tế.', NOW(), NOW()),
(21, 'Mẹo đặt vé máy bay', 'flight-hacks', 'Cách tìm vé rẻ và nâng hạng ghế.', NOW(), NOW()),
(22, 'Chuyến đi ngẫu hứng', 'road-trips-blog', 'Kinh nghiệm thuê xe và di chuyển đường bộ.', NOW(), NOW()),
(23, 'Bảo hiểm du lịch', 'travel-insurance-tips', 'Tại sao cần và cách chọn gói bảo hiểm tốt.', NOW(), NOW()),
(24, 'Du lịch sinh thái', 'eco-friendly-tips', 'Sống xanh ngay cả khi đang xê dịch.', NOW(), NOW()),
(25, 'Ứng dụng du lịch hữu ích', 'travel-apps', 'Các phần mềm không thể thiếu trên điện thoại.', NOW(), NOW()),
(26, 'Sức khỏe khi đi xa', 'health-on-the-road', 'Giữ gìn thể lực và xử lý bệnh tật dọc đường.', NOW(), NOW()),
(27, 'An toàn du lịch', 'travel-safety', 'Phòng tránh lừa đảo và giữ an toàn cá nhân.', NOW(), NOW()),
(28, 'Phụ nữ đi du lịch', 'women-travel-tips', 'Chia sẻ dành riêng cho phái đẹp.', NOW(), NOW()),
(29, 'Du lịch cặp đôi', 'couple-travel', 'Gắn kết tình cảm qua những chuyến đi.', NOW(), NOW()),
(30, 'Du lịch nhóm', 'group-travel-tips', 'Cách lên kế hoạch và giải quyết xung đột.', NOW(), NOW()),
(31, 'Chỗ ở độc đáo', 'unique-accommodations', 'Review lều, nhà cây, lâu đài, tàu hỏa.', NOW(), NOW()),
(32, 'Giao thông công cộng', 'public-transport-guide', 'Cách sử dụng tàu điện, xe buýt tại nước ngoài.', NOW(), NOW()),
(33, 'Lễ hội thế giới', 'world-festivals', 'Lịch trình các lễ hội lớn không nên bỏ qua.', NOW(), NOW()),
(34, 'Du lịch tâm linh', 'spiritual-journey', 'Hành trình tìm lại bản thân.', NOW(), NOW()),
(35, 'Nghệ thuật đường phố', 'street-art-guide', 'Khám phá Graffiti và văn hóa đô thị.', NOW(), NOW()),
(36, 'Mua sắm thông minh', 'shopping-guide-blog', 'Nơi mua đồ hiệu giá rẻ và đồ thủ công.', NOW(), NOW()),
(37, 'Thủ tục Visa', 'visa-guide', 'Hướng dẫn xin thị thực các nước khó.', NOW(), NOW()),
(38, 'Làm hộ chiếu', 'passport-tips', 'Các quy định mới và cách gia hạn nhanh.', NOW(), NOW()),
(39, 'Hành lý xách tay', 'carry-on-only', 'Bí quyết chỉ mang một balo cho mọi chuyến đi.', NOW(), NOW()),
(40, 'Sim card & Internet', 'connectivity-tips', 'Cách giữ liên lạc khi ra nước ngoài.', NOW(), NOW()),
(41, 'Đánh giá khách sạn', 'hotel-reviews', 'Trải nghiệm thực tế tại các cơ sở lưu trú.', NOW(), NOW()),
(42, 'Đánh giá hãng hàng không', 'airline-reviews', 'Chất lượng dịch vụ của các hãng bay.', NOW(), NOW()),
(43, 'Cuộc sống về đêm', 'nightlife-guide', 'Các club và khu phố không ngủ.', NOW(), NOW()),
(44, 'Du lịch mùa đông', 'winter-travel', 'Chơi gì khi trời lạnh và có tuyết.', NOW(), NOW()),
(45, 'Du lịch mùa hè', 'summer-travel', 'Các bãi biển và hoạt động giải nhiệt.', NOW(), NOW()),
(46, 'Điểm đến mùa thu', 'autumn-destinations', 'Ngắm lá vàng và không khí lãng mạn.', NOW(), NOW()),
(47, 'Du lịch mùa xuân', 'spring-travel', 'Mùa hoa nở và các lễ hội cầu may.', NOW(), NOW()),
(48, 'Tour du lịch tốt nhất', 'best-tours-review', 'Gợi ý các công ty lữ hành uy tín.', NOW(), NOW()),
(49, 'Chương trình khách hàng thân thiết', 'loyalty-programs', 'Tích điểm bay và đổi đêm nghỉ miễn phí.', NOW(), NOW()),
(50, 'Du lịch bằng tàu hỏa', 'train-travel-guide', 'Những cung đường sắt đẹp nhất thế giới.', NOW(), NOW()),
(51, 'Mẹo chụp ảnh bằng điện thoại', 'mobile-photography', 'Chỉnh ảnh lung linh ngay trên smartphone.', NOW(), NOW()),
(52, 'Quà tặng du lịch', 'travel-souvenirs', 'Mua gì về làm quà cho ý nghĩa.', NOW(), NOW()),
(53, 'Lớp học nấu ăn bản địa', 'cooking-class-experience', 'Học làm món ngon từ chính người dân.', NOW(), NOW()),
(54, 'Chuyến đi trong ngày (Day trips)', 'day-trips-ideas', 'Các điểm đến gần trung tâm.', NOW(), NOW()),
(55, 'Du lịch lặn biển', 'diving-adventures', 'Khám phá rạn san hô và sinh vật biển.', NOW(), NOW()),
(56, 'Trekking xuyên rừng', 'jungle-trekking', 'Kỹ năng sinh tồn và khám phá thiên nhiên.', NOW(), NOW()),
(57, 'Du lịch bằng du thuyền', 'cruise-life', 'Cuộc sống trên những "thành phố nổi".', NOW(), NOW()),
(58, 'Mẹo di chuyển sân bay', 'airport-hacks', 'Tiết kiệm thời gian check-in và gửi đồ.', NOW(), NOW()),
(59, 'Tìm bạn đồng hành', 'finding-travel-buddies', 'Các cộng đồng kết nối người đi chơi.', NOW(), NOW()),
(60, 'Du lịch qua màn ảnh', 'virtual-travel-tips', 'Khám phá thế giới tại nhà.', NOW(), NOW()),
(61, 'Văn hóa tiền tip', 'tipping-culture', 'Quy tắc trả tiền boa tại các quốc gia.', NOW(), NOW()),
(62, 'Hành trình vượt đại dương', 'transatlantic-travel', 'Những chuyến đi dài ngày đầy cảm xúc.', NOW(), NOW()),
(63, 'Cắm trại (Camping) 101', 'camping-for-beginners', 'Tất tần tật cho người mới bắt đầu.', NOW(), NOW()),
(64, 'Du lịch kết hợp yoga', 'yoga-on-the-go', 'Duy trì luyện tập khi đi chơi.', NOW(), NOW()),
(65, 'Mẹo làm việc năng suất khi đi chơi', 'productivity-tips-travel', 'Dành cho Digital Nomad.', NOW(), NOW()),
(66, 'Review thiết bị công nghệ', 'tech-reviews-travel', 'Laptop, tai nghe chống ồn, sạc dự phòng.', NOW(), NOW()),
(67, 'Phong cách thời trang du lịch', 'travel-fashion', 'Mặc đẹp mà vẫn thoải mái.', NOW(), NOW()),
(68, 'Du lịch kiến trúc', 'architectural-gems', 'Những tòa nhà kỳ vĩ nhất.', NOW(), NOW()),
(69, 'Khám phá đảo hoang', 'deserted-island-travel', 'Trở về với cuộc sống nguyên sơ.', NOW(), NOW()),
(70, 'Mẹo đi vệ sinh công cộng', 'public-toilet-hacks', 'Một chủ đề tế nhị nhưng quan trọng.', NOW(), NOW()),
(71, 'Du lịch bằng xe buýt đường dài', 'long-haul-bus', 'Tiết kiệm chi phí tối đa.', NOW(), NOW()),
(72, 'Kinh nghiệm thuê xe máy', 'motorbike-rental-tips', 'An toàn và pháp lý.', NOW(), NOW()),
(73, 'Giao lưu văn hóa bản địa', 'local-interaction', 'Cách kết bạn với người dân địa phương.', NOW(), NOW()),
(74, 'Du lịch bảo tồn động vật', 'ethical-wildlife-travel', 'Tránh các hoạt động ngược đãi thú.', NOW(), NOW()),
(75, 'Review túi ngủ & lều', 'camping-gear-review', 'Chọn đồ tốt cho đêm ngoài trời.', NOW(), NOW()),
(76, 'Mẹo chống jet lag', 'beating-jet-lag', 'Hồi phục sức khỏe nhanh sau chuyến bay dài.', NOW(), NOW()),
(77, 'Du lịch bằng trực thăng', 'helicopter-tours-blog', 'Góc nhìn từ trên mây.', NOW(), NOW()),
(78, 'Mua sắm miễn thuế (Duty Free)', 'duty-free-shopping', 'Những món đồ đáng mua nhất.', NOW(), NOW()),
(79, 'Vượt qua nỗi sợ bay', 'overcoming-fear-of-flying', 'Các phương pháp tâm lý hữu ích.', NOW(), NOW()),
(80, 'Du lịch kết hợp từ thiện', 'voluntourism-stories', 'Những câu chuyện ý nghĩa.', NOW(), NOW()),
(81, 'Review các trang web đặt phòng', 'booking-sites-comparison', 'Agoda vs Booking vs Airbnb.', NOW(), NOW()),
(82, 'Mẹo sử dụng thẻ tín dụng du lịch', 'travel-credit-cards', 'Tận dụng ưu đãi và bảo mật.', NOW(), NOW()),
(83, 'Du lịch vùng cực', 'polar-travel-blog', 'Chinh phục nơi lạnh nhất trái đất.', NOW(), NOW()),
(84, 'Kinh nghiệm đi tour ghép', 'group-tour-experience', 'Ưu và nhược điểm.', NOW(), NOW()),
(85, 'Du lịch tự lái (Self-drive)', 'self-drive-adventures', 'Làm chủ hành trình trên vô lăng.', NOW(), NOW()),
(86, 'Khám phá chợ đêm', 'night-market-culture', 'Ăn gì và mua gì.', NOW(), NOW()),
(87, 'Mẹo đóng gói chất lỏng', 'liquid-packing-hacks', 'Quy định 100ml và cách lách luật.', NOW(), NOW()),
(88, 'Du lịch bằng xe đạp xuyên bang', 'cross-country-cycling', 'Thử thách sức bền.', NOW(), NOW()),
(89, 'Nghệ thuật mặc cả (Trả giá)', 'art-of-haggling', 'Mua sắm không sợ bị hớ.', NOW(), NOW()),
(90, 'Du lịch mùa lễ hội hoa', 'flower-festival-travel', 'Tulip Hà Lan, Lavender Pháp.', NOW(), NOW()),
(91, 'Trải nghiệm Airbnb độc đáo', 'unique-airbnb-finds', 'Nhà trên cây, nhà bong bóng.', NOW(), NOW()),
(92, 'Review xe đẩy du lịch cho bé', 'travel-stroller-review', 'Tiện ích cho ba mẹ bỉm sữa.', NOW(), NOW()),
(93, 'Mẹo học ngoại ngữ thần tốc', 'fast-language-learning', 'Giao tiếp trong 1 tuần.', NOW(), NOW()),
(94, 'Du lịch thời Covid (Hậu Covid)', 'post-covid-travel', 'Những thay đổi và lưu ý mới.', NOW(), NOW()),
(95, 'Kinh nghiệm phượt xe máy (Biker)', 'biker-travel-tips', 'Đồ bảo hộ và bảo trì xe.', NOW(), NOW()),
(96, 'Du lịch kiến trúc cổ điển', 'classical-architecture', 'Lâu đài và thánh đường Châu Âu.', NOW(), NOW()),
(97, 'Review balo máy ảnh', 'camera-bag-guide', 'Bảo vệ thiết bị tối ưu.', NOW(), NOW()),
(98, 'Du lịch tâm linh tại Châu Á', 'asia-spiritual-sites', 'Ấn Độ, Nepal, Tây Tạng.', NOW(), NOW()),
(99, 'Mẹo giữ liên lạc khi leo núi', 'mountain-connectivity', 'Bộ đàm và thiết bị định vị.', NOW(), NOW()),
(100, 'Tương lai của du lịch', 'future-of-travel', 'Công nghệ và những xu hướng mới.', NOW(), NOW());
