-- DanangTrip Real Data Seeder: Blog Posts & Categories
-- Source: VnExpress Travel, iVIVU, Dulich9, Kenh14
-- Retrieved Date: 2026-04-29

-- BLOG_POST_LOOKUP
-- 1: Kinh nghiệm du lịch Đà Nẵng 2024 tự túc
-- 2: Kinh nghiệm phượt Giếng trời Đà Nẵng
-- 3: Khám phá thiên đường ẩm thực chợ Cồn
-- ...

INSERT INTO blog_posts (id, title, slug, excerpt, content, featured_image, author_id, view_count, status, published_at, created_at, updated_at) VALUES
(1, 'Kinh nghiệm du lịch Đà Nẵng 2024 tự túc, tiết kiệm', 'kinh-nghiem-du-lich-da-nang-2024', 'Đà Nẵng được mệnh danh là thành phố đáng sống nhất ở Việt Nam với nhiều địa điểm tham quan, vui chơi giải trí và các khu nghỉ dưỡng sang trọng.', 'Đà Nẵng là điểm đến lý tưởng với sự kết hợp hài hòa giữa biển xanh, núi non và các công trình hiện đại. Thời điểm du lịch đẹp nhất là từ tháng 4 đến tháng 8 khi thời tiết khô ráo, nắng ấm, rất thuận lợi cho việc tắm biển và tham quan.\n\nNhững địa điểm không thể bỏ qua bao gồm Biển Mỹ Khê, Bà Nà Hills với Cầu Vàng, và Bán đảo Sơn Trà. Du khách cũng nên trải nghiệm ẩm thực phong phú với các món đặc sản như Bánh tráng cuốn thịt heo và Mì Quảng.\n\nĐể tiết kiệm chi phí, bạn nên đặt vé máy bay và phòng khách sạn trước 1-2 tháng. Sử dụng xe máy làm phương tiện di chuyển chính sẽ giúp chuyến đi linh hoạt và thú vị hơn.', 'https://dulich9.com/wp-content/uploads/2018/11/kinh-nghiem-du-lich-da-nang.jpg', 1, 1500, 'published', NOW(), NOW(), NOW()),
(2, 'Kinh nghiệm phượt Giếng trời Đà Nẵng 2 ngày 1 đêm an toàn', 'kinh-nghiem-phuot-gieng-troi-da-nang', 'Giếng Trời là một địa điểm du lịch Đà Nẵng hoang sơ, lý tưởng cho những chuyến trekking và cắm trại giữa thiên nhiên đại ngàn.', 'Nằm sâu trong rừng già xã Hòa Ninh, Giếng Trời sở hữu một hồ nước xanh ngắt bao quanh bởi vách đá và thác nước cao. Để đến được đây, du khách phải trải qua một hành trình trekking xuyên rừng đầy thử thách nhưng cực kỳ xứng đáng.\n\nThời điểm lý tưởng nhất để phượt Giếng Trời là mùa hè (tháng 6 - tháng 9), khi nước hồ trong xanh nhất và đường rừng khô ráo. Các hoạt động chính tại đây gồm tắm hồ, câu cá, bắt ốc đá và cắm trại qua đêm.\n\nLưu ý quan trọng là bạn cần chuẩn bị đầy đủ đồ ăn, nước uống và dụng cụ y tế vì khu vực này hoàn toàn tách biệt. Việc giữ gìn vệ sinh và không xả rác là bắt buộc để bảo tồn vẻ đẹp hoang sơ nơi đây.', 'https://dulich9.com/wp-content/uploads/2016/05/kinh-nghiem-phuot-gieng-troi-da-nang.jpg', 2, 850, 'published', NOW(), NOW(), NOW()),
(3, 'Khám phá thiên đường ẩm thực chợ Cồn khi đi Đà Nẵng', 'kham-pha-am-thuc-cho-con-da-nang', 'Chợ Cồn được coi là "thánh địa" ẩm thực của Đà Nẵng với hàng trăm món ăn ngon, bổ, rẻ thu hút mọi tín đồ ăn uống.', 'Chợ Cồn không chỉ là trung tâm mua sắm lớn mà còn là nơi tập trung tinh hoa ẩm thực miền Trung. Khu ẩm thực được chia làm hai phần: Food Court (trong nhà) và Street Food (ngoài trời) với không khí cực kỳ nhộn nhịp.\n\nTại đây, bạn có thể thưởng thức đủ loại bánh bèo, bánh lọc, bánh xèo cho đến bún mắm nêm với giá chỉ từ 5.000đ - 20.000đ mỗi món. Sự đa dạng và hương vị đậm đà tại các gánh hàng rong luôn để lại ấn tượng khó quên.\n\nKinh nghiệm là bạn nên thử mỗi thứ một chút để có thể ăn được nhiều món nhất. Cuối chợ còn có khu bán đồ khô như mực rim, chả bò - rất thích hợp để mua về làm quà.', 'https://dulich9.com/wp-content/uploads/2018/11/thien-duong-am-thuc-cho-con-da-nang.jpg', 1, 2200, 'published', NOW(), NOW(), NOW()),
(4, 'Top 7 trải nghiệm không thể bỏ lỡ khi du lịch Đà Nẵng hè 2024', 'top-7-trai-nghiem-du-lich-da-nang-he-2024', 'Đà Nẵng hè 2024 hứa hẹn bùng nổ với nhiều sự kiện quốc tế và những trải nghiệm nghỉ dưỡng đẳng cấp ven biển.', 'Một trong những điểm nhấn của năm 2024 là Lễ hội pháo hoa quốc tế (DIFF) diễn ra vào tháng 6-7, mang đến những màn trình diễn ánh sáng mãn nhãn trên sông Hàn. Đây là sự kiện quy quy tụ nhiều đội thi quốc tế nổi tiếng.\n\nNgoài ra, việc check-in tại Cầu Vàng (Bà Nà Hills) hay khám phá Bán đảo Sơn Trà vẫn luôn là những trải nghiệm hàng đầu. Du khách cũng có thể tham gia các trò chơi thể thao nước tại bãi biển Mỹ Khê trong những ngày hè nắng rực rỡ.\n\nĐà Nẵng luôn đổi mới với các sản phẩm du lịch chất lượng, từ các quán cà phê view biển đến các khu nghỉ dưỡng xanh, đảm bảo một kỳ nghỉ trọn vẹn cho mọi gia đình.', 'https://cdn.ivivu.com/2024/04/Top-7-trai-nghiem-khong-the-bo-lo-khu-du-lich-da-nang-he-2024-ivivu-1.jpg', 2, 3100, 'published', NOW(), NOW(), NOW()),
(5, 'Cẩm nang du lịch Đà Nẵng (Cập nhật 2024)', 'cam-nang-du-lich-da-nang-2024', 'Đà Nẵng - thành phố của những cây cầu - thu hút du khách bởi sự kết hợp hoàn hảo giữa thiên nhiên, hạ tầng hiện đại và con người thân thiện.', 'Nằm ở tâm điểm của 3 di sản thế giới (Huế, Hội An, Mỹ Sơn), Đà Nẵng sở hữu vị trí đắc địa và bãi biển Mỹ Khê - một trong những bãi biển quyến rũ nhất hành tinh. Thành phố được trang bị hệ thống hạ tầng du lịch tốt nhất Việt Nam hiện nay.\n\nDu khách không nên bỏ lỡ các biểu tượng như Cầu Rồng phun lửa, Cầu Quay Sông Hàn hay vẻ đẹp huyền bí của Ngũ Hành Sơn. Bán đảo Sơn Trà với chùa Linh Ứng cũng là nơi mang lại sự bình an và tầm nhìn tuyệt đẹp bao quát thành phố.\n\nVề ẩm thực, mì Quảng và bánh tráng cuốn thịt heo là hai món "phải thử". Thành phố cũng nổi tiếng với các khu chợ truyền thống như chợ Hàn, nơi bạn có thể tìm thấy mọi đặc sản miền Trung với chất lượng đảm bảo.', 'https://i1-dulich.vnecdn.net/2022/06/03/CauVang-1654247842.jpg', 1, 5000, 'published', NOW(), NOW(), NOW());

-- BLOG_POST_CATEGORIES (Mapping posts to categories from 03_tour_blog_categories.sql)
INSERT INTO blog_post_categories (post_id, blog_category_id) VALUES
(1, 5), -- Kinh nghiệm du lịch -> Cẩm nang
(2, 5), -- Kinh nghiệm phượt -> Cẩm nang
(2, 1), -- Kinh nghiệm phượt -> Điểm đến
(3, 2), -- Chợ Cồn -> Ẩm thực
(4, 1), -- Top trải nghiệm -> Điểm đến
(4, 7), -- Top trải nghiệm -> Check-in
(5, 5); -- Cẩm nang du lịch -> Cẩm nang
