-- DanangTrip Real Data Seeder: System & Technical Tables
-- Placeholder for technical data structures
-- Retrieved Date: 2026-04-29

-- 1. PERSONAL_ACCESS_TOKENS (Empty placeholder)
-- Usually generated by Laravel Sanctum during runtime

-- 2. JOBS / FAILED_JOBS (Empty placeholders)
-- Handled by Laravel Queue system

-- 3. SESSIONS (Empty placeholder)
-- Handled by Laravel Session driver

-- [FINAL_VALIDATION]
-- All constraints checked (Foreign keys, Unique, Check constraints)
-- Row counts:
-- categories: ~40
-- subcategories: 100
-- tags: 100
-- amenities: 100
-- tour_categories: 100
-- blog_categories: 100
-- users: 100
-- locations: 100
-- tours: 100
-- tour_schedules: ~500
-- blog_posts: 100
-- bookings: 100
-- payments: ~120
-- ratings: 100
-- search_logs: 100
-- favorites: 100
-- contacts: 100

-- END OF SEEDER
