-- DanangTrip Real Data Seeder: Categories & Subcategories (100 rows each)
-- FILE: 01_categories_subcategories.sql

-- 1. CATEGORIES (Target 100)
INSERT INTO categories (id, name, slug, icon, sort_order, status, created_at, updated_at) VALUES
(1, 'Ẩm thực địa phương', 'am-thuc-dia-phuong', 'local-dining', 1, 'active', NOW(), NOW()),
(2, 'Nhà hàng quốc tế', 'nha-hang-quoc-te', 'international-dining', 2, 'active', NOW(), NOW()),
(3, 'Cà phê & Trà sữa', 'ca-phe-tra-sua', 'cafe-tea', 3, 'active', NOW(), NOW()),
(4, 'Bar & Pub', 'bar-pub', 'nightlife', 4, 'active', NOW(), NOW()),
(5, 'Resort & Villa', 'resort-villa', 'luxury-stay', 5, 'active', NOW(), NOW()),
(6, 'Khách sạn & Homestay', 'khach-san-homestay', 'accommodation', 6, 'active', NOW(), NOW()),
(7, 'Điểm check-in nổi tiếng', 'check-in-noi-tieng', 'camera', 7, 'active', NOW(), NOW()),
(8, 'Bảo tàng & Di tích', 'bao-tang-di-tich', 'museum', 8, 'active', NOW(), NOW()),
(9, 'Hang động & Núi non', 'hang-dong-nui-non', 'nature', 9, 'active', NOW(), NOW()),
(10, 'Công viên & Vườn hoa', 'cong-vien-vuon-hoa', 'park', 10, 'active', NOW(), NOW()),
(11, 'Điểm du lịch tâm linh', 'du-lich-tam-linh', 'temple', 11, 'active', NOW(), NOW()),
(12, 'Làng nghề truyền thống', 'lang-nghe-truyen-thong', 'craft', 12, 'active', NOW(), NOW()),
(13, 'Trung tâm thương mại', 'trung-tam-thuong-mai', 'shopping-mall', 13, 'active', NOW(), NOW()),
(14, 'Chợ địa phương', 'cho-dia-phuong', 'local-market', 14, 'active', NOW(), NOW()),
(15, 'Cửa hàng đặc sản', 'cua-hang-dac-san', 'gift', 15, 'active', NOW(), NOW()),
(16, 'Công viên nước & Vui chơi', 'cong-vien-nuoc', 'water-park', 16, 'active', NOW(), NOW()),
(17, 'Sân Golf & Tennis', 'san-golf-tennis', 'sport', 17, 'active', NOW(), NOW()),
(18, 'Phòng Gym & Yoga', 'gym-yoga', 'fitness', 18, 'active', NOW(), NOW()),
(19, 'Spa & Massage', 'spa-massage', 'wellness', 19, 'active', NOW(), NOW()),
(20, 'Bệnh viện & Phòng khám', 'benh-vien-phong-kham', 'hospital', 20, 'active', NOW(), NOW()),
(21, 'Nha khoa & Thẩm mỹ', 'nha-khoa-tham-my', 'dentist', 21, 'active', NOW(), NOW()),
(22, 'Trường học & Trung tâm', 'truong-hoc-trung-tam', 'education', 22, 'active', NOW(), NOW()),
(23, 'Ngân hàng & ATM', 'ngan-hang-atm', 'bank', 23, 'active', NOW(), NOW()),
(24, 'Sân bay & Ga tàu', 'san-bay-ga-tau', 'transport', 24, 'active', NOW(), NOW()),
(25, 'Thuê xe & Sửa xe', 'thue-xe-sua-xe', 'car-rental', 25, 'active', NOW(), NOW()),
(26, 'Vận chuyển & Giao hàng', 'van-chuyen-giao-hang', 'delivery', 26, 'active', NOW(), NOW()),
(27, 'Cơ quan hành chính', 'co-quan-hanh-chinh', 'government', 27, 'active', NOW(), NOW()),
(28, 'Bưu điện & Viễn thông', 'buu-dien-vien-thong', 'post', 28, 'active', NOW(), NOW()),
(29, 'Điện máy & Công nghệ', 'dien-may-cong-nghe', 'electronics', 29, 'active', NOW(), NOW()),
(30, 'Bất động sản', 'bat-dong-san', 'real-estate', 30, 'active', NOW(), NOW()),
(31, 'Luật sư & Công chứng', 'luat-su-cong-chung', 'legal', 31, 'active', NOW(), NOW()),
(32, 'Xăng dầu & Năng lượng', 'xang-dau-nang-luong', 'gas', 32, 'active', NOW(), NOW()),
(33, 'Giặt ủi & Vệ sinh', 'giat-ui-ve-sinh', 'laundry', 33, 'active', NOW(), NOW()),
(34, 'Thú y & Chăm sóc thú cưng', 'thu-y-thu-cung', 'pet', 34, 'active', NOW(), NOW()),
(35, 'Studio & Phim trường', 'studio-phim-truong', 'studio', 35, 'active', NOW(), NOW()),
(36, 'Hải sản tươi sống', 'hai-san-tuoi-song', 'seafood', 36, 'active', NOW(), NOW()),
(37, 'Hoa tươi & Quà tặng', 'hoa-tuoi-qua-tang', 'flower', 37, 'active', NOW(), NOW()),
(38, 'Sách & Văn phòng phẩm', 'sach-van-phong-pham', 'book', 38, 'active', NOW(), NOW()),
(39, 'Thời trang & Phụ kiện', 'thoi-trang-phu-kien', 'fashion', 39, 'active', NOW(), NOW()),
(40, 'Mỹ phẩm & Làm đẹp', 'my-pham-lam-dep', 'beauty', 40, 'active', NOW(), NOW()),
(41, 'Đồ gia dụng & Nội thất', 'gia-dung-noi-that', 'furniture', 41, 'active', NOW(), NOW()),
(42, 'Xây dựng & Vật liệu', 'xay-dung-vat-lieu', 'construction', 42, 'active', NOW(), NOW()),
(43, 'Tổ chức sự kiện', 'to-chuc-su-kien', 'event', 43, 'active', NOW(), NOW()),
(44, 'Dịch vụ tang lễ', 'dich-vu-tang-le', 'funeral', 44, 'active', NOW(), NOW()),
(45, 'Quảng cáo & In ấn', 'quang-cao-in-an', 'printing', 45, 'active', NOW(), NOW()),
(46, 'Bảo vệ & An ninh', 'bao-ve-an-ninh', 'security', 46, 'active', NOW(), NOW()),
(47, 'Tài chính & Bảo hiểm', 'tai-chinh-bao-hiem', 'finance', 47, 'active', NOW(), NOW()),
(48, 'Du lịch lữ hành', 'du-lich-lu-hanh', 'travel-agency', 48, 'active', NOW(), NOW()),
(49, 'Dịch thuật & Visa', 'dich-thuat-visa', 'translation', 49, 'active', NOW(), NOW()),
(50, 'Coworking Space', 'coworking-space', 'work', 50, 'active', NOW(), NOW()),
-- Adding 50 more generic/specific categories to reach 100
(51, 'Nghệ thuật & Triển lãm', 'nghe-thuat-trien-lam', 'art', 51, 'active', NOW(), NOW()),
(52, 'Nhà hát & Rạp phim', 'nha-hat-rap-phim', 'cinema', 52, 'active', NOW(), NOW()),
(53, 'Thư viện & Không gian đọc', 'thu-vien-doc-sach', 'library', 53, 'active', NOW(), NOW()),
(54, 'Sân khấu & Ca nhạc', 'san-khau-ca-nhac', 'music', 54, 'active', NOW(), NOW()),
(55, 'Trung tâm hội nghị', 'trung-tam-hoi-nghi', 'convention', 55, 'active', NOW(), NOW()),
(56, 'Dịch vụ lưu trú cao cấp', 'stay-luxury', 'stars', 56, 'active', NOW(), NOW()),
(57, 'Cắm trại & Dã ngoại', 'camping-picnic', 'tent', 57, 'active', NOW(), NOW()),
(58, 'Leo núi & Khám phá', 'hiking-exploration', 'boot', 58, 'active', NOW(), NOW()),
(59, 'Lặn biển & Thể thao nước', 'diving-water-sport', 'swim', 59, 'active', NOW(), NOW()),
(60, 'Bay khinh khí cầu/Dù lượn', 'air-sport', 'wind', 60, 'active', NOW(), NOW()),
(61, 'Trải nghiệm nông nghiệp', 'agritourism', 'leaf', 61, 'active', NOW(), NOW()),
(62, 'Lớp học nấu ăn', 'cooking-class', 'pot', 62, 'active', NOW(), NOW()),
(63, 'Thưởng thức trà đạo', 'tea-ceremony', 'tea', 63, 'active', NOW(), NOW()),
(64, 'Khám phá phố cổ', 'old-town-walk', 'walk', 64, 'active', NOW(), NOW()),
(65, 'Chợ đêm & Phố đi bộ', 'night-market-walk', 'moon', 65, 'active', NOW(), NOW()),
(66, 'Dịch vụ xe điện', 'electric-vehicle', 'bolt', 66, 'active', NOW(), NOW()),
(67, 'Tour trực thăng', 'helicopter-tour', 'air', 67, 'active', NOW(), NOW()),
(68, 'Chụp ảnh cưới', 'wedding-photography', 'heart', 68, 'active', NOW(), NOW()),
(69, 'Dịch vụ trông trẻ', 'babysitting', 'baby', 69, 'active', NOW(), NOW()),
(70, 'Hỗ trợ người khuyết tật', 'disability-support', 'wheelchair', 70, 'active', NOW(), NOW()),
(71, 'Thông tin du khách', 'tourist-info', 'info', 71, 'active', NOW(), NOW()),
(72, 'Đổi ngoại tệ', 'currency-exchange', 'dollar', 72, 'active', NOW(), NOW()),
(73, 'Vé tham quan & Show', 'ticket-show', 'ticket', 73, 'active', NOW(), NOW()),
(74, 'Trang trí nội thất', 'interior-decor', 'home', 74, 'active', NOW(), NOW()),
(75, 'Cửa hàng tiện lợi 24/7', 'convenience-store-247', 'clock', 75, 'active', NOW(), NOW()),
(76, 'Hiệu thuốc & Dược phẩm', 'pharmacy-medical', 'pill', 76, 'active', NOW(), NOW()),
(77, 'Phòng thí nghiệm', 'laboratory', 'test-tube', 77, 'active', NOW(), NOW()),
(78, 'Chăm sóc người già', 'elderly-care', 'user', 78, 'active', NOW(), NOW()),
(79, 'Công ty phần mềm', 'it-software', 'code', 79, 'active', NOW(), NOW()),
(80, 'Khởi nghiệp & Tech hub', 'startup-tech-hub', 'rocket', 80, 'active', NOW(), NOW()),
(81, 'Thiết kế đồ họa', 'graphic-design', 'pen', 81, 'active', NOW(), NOW()),
(82, 'Văn phòng đại diện', 'representative-office', 'building', 82, 'active', NOW(), NOW()),
(83, 'Khu công nghiệp', 'industrial-zone', 'factory', 83, 'active', NOW(), NOW()),
(84, 'Kho bãi & Logistic', 'warehouse-logistic', 'box', 84, 'active', NOW(), NOW()),
(85, 'Dịch vụ hải quan', 'customs-service', 'ship', 85, 'active', NOW(), NOW()),
(86, 'Nông sản sạch', 'clean-agriculture', 'carrot', 86, 'active', NOW(), NOW()),
(87, 'Thực phẩm chức năng', 'supplement-store', 'shield', 87, 'active', NOW(), NOW()),
(88, 'Rượu vang & Đồ uống cao cấp', 'wine-premium-drink', 'glass', 88, 'active', NOW(), NOW()),
(89, 'Sửa chữa điện tử', 'repair-electronic', 'tool', 89, 'active', NOW(), NOW()),
(90, 'Phát triển bền vững', 'sustainable-development', 'globe', 90, 'active', NOW(), NOW()),
(91, 'Hoạt động cộng đồng', 'community-activity', 'users', 91, 'active', NOW(), NOW()),
(92, 'Tổ chức phi lợi nhuận', 'ngo-non-profit', 'heart', 92, 'active', NOW(), NOW()),
(93, 'Nghiên cứu văn hóa', 'cultural-research', 'archive', 93, 'active', NOW(), NOW()),
(94, 'Khảo cổ học', 'archaeology', 'mountain', 94, 'active', NOW(), NOW()),
(95, 'Khí tượng thủy văn', 'weather-service', 'cloud', 95, 'active', NOW(), NOW()),
(96, 'Dịch vụ cứu hộ', 'rescue-service', 'ambulance', 96, 'active', NOW(), NOW()),
(97, 'Phòng cháy chữa cháy', 'fire-service', 'flame', 97, 'active', NOW(), NOW()),
(98, 'An toàn lao động', 'occupational-safety', 'hard-hat', 98, 'active', NOW(), NOW()),
(99, 'Kiểm toán & Kế toán', 'audit-accounting', 'file-text', 99, 'active', NOW(), NOW()),
(100, 'Tư vấn quản trị', 'management-consulting', 'briefcase', 100, 'active', NOW(), NOW());

-- 2. SUBCATEGORIES (Target 100)
INSERT INTO subcategories (id, category_id, name, slug, status, created_at, updated_at) VALUES
-- Local Dining (Cat 1)
(1, 1, 'Mì Quảng', 'mi-quang', 'active', NOW(), NOW()),
(2, 1, 'Bánh tráng cuốn thịt heo', 'banh-trang-cuon-thit-heo', 'active', NOW(), NOW()),
(3, 1, 'Bún chả cá', 'bun-cha-ca', 'active', NOW(), NOW()),
(4, 1, 'Bánh xèo & Nem lụi', 'banh-xeo-nem-lui', 'active', NOW(), NOW()),
(5, 1, 'Cơm gà', 'com-ga', 'active', NOW(), NOW()),
(6, 1, 'Bún mắm', 'bun-mam', 'active', NOW(), NOW()),
(7, 1, 'Gỏi cá Nam Ô', 'goi-ca-nam-o', 'active', NOW(), NOW()),
(8, 1, 'Bê thui Cầu Mống', 'be-thui-cau-mong', 'active', NOW(), NOW()),
-- International Dining (Cat 2)
(9, 2, 'Nhà hàng Hàn Quốc', 'nha-hang-han-quoc', 'active', NOW(), NOW()),
(10, 2, 'Nhà hàng Nhật Bản', 'nha-hang-nhat-ban', 'active', NOW(), NOW()),
(11, 2, 'Nhà hàng Âu', 'nha-hang-au', 'active', NOW(), NOW()),
(12, 2, 'Nhà hàng Thái Lan', 'nha-hang-thai', 'active', NOW(), NOW()),
(13, 2, 'Pizza & Pasta', 'pizza-pasta', 'active', NOW(), NOW()),
-- Cafe & Tea (Cat 3)
(14, 3, 'Cà phê đặc sản', 'ca-phe-dac-san', 'active', NOW(), NOW()),
(15, 3, 'Trà sữa trân châu', 'tra-sua-tran-chau', 'active', NOW(), NOW()),
(16, 3, 'Trà thảo mộc', 'tra-thao-moc', 'active', NOW(), NOW()),
(17, 3, 'Tiệm bánh & Cà phê', 'bakery-cafe', 'active', NOW(), NOW()),
-- Nightlife (Cat 4)
(18, 4, 'Rooftop Bar', 'rooftop-bar', 'active', NOW(), NOW()),
(19, 4, 'Pub & Lounge', 'pub-lounge', 'active', NOW(), NOW()),
(20, 4, 'Bia hơi & Nhậu', 'bia-hoi-nhau', 'active', NOW(), NOW()),
-- Luxury Stay (Cat 5)
(21, 5, 'Resort 5 sao ven biển', 'resort-5-sao-ven-bien', 'active', NOW(), NOW()),
(22, 5, 'Villa nguyên căn', 'villa-nguyen-can', 'active', NOW(), NOW()),
-- Accommodation (Cat 6)
(23, 6, 'Khách sạn trung tâm', 'khach-san-trung-tam', 'active', NOW(), NOW()),
(24, 6, 'Homestay phong cách', 'homestay-phong-cach', 'active', NOW(), NOW()),
(25, 6, 'Căn hộ dịch vụ', 'serviced-apartment', 'active', NOW(), NOW()),
-- Nature (Cat 9)
(26, 9, 'Hang động đá vôi', 'hang-dong-da-voi', 'active', NOW(), NOW()),
(27, 9, 'Đỉnh núi & Ngắm cảnh', 'dinh-nui-ngam-canh', 'active', NOW(), NOW()),
-- Temple (Cat 11)
(28, 11, 'Chùa & Tự viện', 'chua-tu-vien', 'active', NOW(), NOW()),
(29, 11, 'Nhà thờ & Giáo xứ', 'nha-tho-giao-xu', 'active', NOW(), NOW()),
(30, 11, 'Thánh thất & Đền miếu', 'thanh-that-den-mieu', 'active', NOW(), NOW()),
-- Local Market (Cat 14)
(31, 14, 'Chợ hải sản sáng sớm', 'cho-hai-san-sang-som', 'active', NOW(), NOW()),
(32, 14, 'Chợ đêm ẩm thực', 'cho-dem-am-thuc', 'active', NOW(), NOW()),
-- ... Adding more to reach 100
(33, 20, 'Bệnh viện Đa khoa', 'benh-vien-da-khoa', 'active', NOW(), NOW()),
(34, 20, 'Phòng khám chuyên khoa', 'phong-kham-chuyen-khoa', 'active', NOW(), NOW()),
(35, 23, 'ATM 24/7', 'atm-247', 'active', NOW(), NOW()),
(36, 23, 'Phòng giao dịch ngân hàng', 'phong-giao-dich-ngan-hang', 'active', NOW(), NOW()),
(37, 24, 'Ga tàu hỏa', 'ga-tau-hoa', 'active', NOW(), NOW()),
(38, 24, 'Bến xe khách', 'ben-xe-khach', 'active', NOW(), NOW()),
(39, 19, 'Massage chân', 'massage-chan', 'active', NOW(), NOW()),
(40, 19, 'Xông hơi đá nóng', 'xong-hoi-da-nong', 'active', NOW(), NOW()),
-- Education
(41, 22, 'Trường đại học', 'truong-dai-hoc', 'active', NOW(), NOW()),
(42, 22, 'Trung tâm ngoại ngữ', 'trung-tam-ngoai-ngu', 'active', NOW(), NOW()),
-- Public Services
(43, 27, 'Ủy ban nhân dân', 'ubnd', 'active', NOW(), NOW()),
(44, 27, 'Công an phường', 'cong-an-phuong', 'active', NOW(), NOW()),
-- Specialty Stores
(45, 15, 'Cửa hàng quà lưu niệm', 'souvenir-shop', 'active', NOW(), NOW()),
(46, 15, 'Tiệm đồ thủ công mỹ nghệ', 'handicraft-shop', 'active', NOW(), NOW()),
-- Sports
(47, 17, 'Sân tập Golf', 'golf-driving-range', 'active', NOW(), NOW()),
(48, 17, 'Sân Tennis', 'tennis-court', 'active', NOW(), NOW()),
-- Logistics
(49, 26, 'Chuyển phát nhanh', 'express-delivery', 'active', NOW(), NOW()),
(50, 26, 'Vận chuyển hàng hóa quốc tế', 'international-shipping', 'active', NOW(), NOW()),
-- Adding 50 more to reach 100
(51, 10, 'Công viên bách thảo', 'botanical-garden', 'active', NOW(), NOW()),
(52, 10, 'Vườn thú & Safari', 'zoo-safari', 'active', NOW(), NOW()),
(53, 52, 'Rạp chiếu phim hiện đại', 'modern-cinema', 'active', NOW(), NOW()),
(54, 52, 'Nhà hát kịch/Tuồng', 'theater-drama', 'active', NOW(), NOW()),
(55, 32, 'Trạm xăng dầu', 'gas-station', 'active', NOW(), NOW()),
(56, 32, 'Trạm sạc xe điện', 'ev-charging-station', 'active', NOW(), NOW()),
(57, 57, 'Khu cắm trại ven hồ', 'lake-camping', 'active', NOW(), NOW()),
(58, 57, 'Khu dã ngoại gia đình', 'family-picnic-area', 'active', NOW(), NOW()),
(59, 13, 'Siêu thị tổng hợp', 'hypermarket', 'active', NOW(), NOW()),
(60, 13, 'Cửa hàng thời trang hiệu', 'brand-fashion-store', 'active', NOW(), NOW()),
(61, 41, 'Cửa hàng nội thất gỗ', 'wooden-furniture-store', 'active', NOW(), NOW()),
(62, 41, 'Điện gia dụng thông minh', 'smart-home-appliance', 'active', NOW(), NOW()),
(63, 76, 'Hiệu thuốc đông y', 'herbal-pharmacy', 'active', NOW(), NOW()),
(64, 76, 'Nhà thuốc tây chuẩn GPP', 'gpp-pharmacy', 'active', NOW(), NOW()),
(65, 8, 'Di tích lịch sử cấp quốc gia', 'national-historical-site', 'active', NOW(), NOW()),
(66, 8, 'Bảo tàng nghệ thuật', 'art-museum', 'active', NOW(), NOW()),
(67, 39, 'Thời trang thiết kế', 'designer-fashion', 'active', NOW(), NOW()),
(68, 39, 'Giày dép & Túi xách', 'shoes-bags', 'active', NOW(), NOW()),
(69, 36, 'Hải sản nướng/Lẩu', 'grilled-hotpot-seafood', 'active', NOW(), NOW()),
(70, 36, 'Vựa hải sản tươi sống', 'fresh-seafood-market', 'active', NOW(), NOW()),
(71, 3, 'Tiệm trà đạo/Thiền', 'tea-meditation-house', 'active', NOW(), NOW()),
(72, 3, 'Cà phê sách', 'book-cafe', 'active', NOW(), NOW()),
(73, 4, 'Beer Garden', 'beer-garden', 'active', NOW(), NOW()),
(74, 4, 'Cocktail Bar', 'cocktail-bar', 'active', NOW(), NOW()),
(75, 25, 'Thuê xe máy tự lái', 'motorbike-rental', 'active', NOW(), NOW()),
(76, 25, 'Thuê ô tô du lịch', 'car-rental-service', 'active', NOW(), NOW()),
(77, 28, 'Bưu điện trung tâm', 'main-post-office', 'active', NOW(), NOW()),
(78, 28, 'Đại lý mạng viễn thông', 'telecom-agency', 'active', NOW(), NOW()),
(79, 43, 'Trung tâm hội nghị quốc tế', 'intl-convention-center', 'active', NOW(), NOW()),
(80, 43, 'Công ty tổ chức sự kiện/Tiệc cưới', 'event-wedding-planner', 'active', NOW(), NOW()),
(81, 16, 'Công viên giải trí Sun World', 'sun-world-park', 'active', NOW(), NOW()),
(82, 16, 'Khu vui chơi trẻ em trong nhà', 'indoor-kids-playground', 'active', NOW(), NOW()),
(83, 7, 'Cầu du lịch nổi tiếng', 'famous-bridge', 'active', NOW(), NOW()),
(84, 7, 'Điểm ngắm hoàng hôn', 'sunset-point', 'active', NOW(), NOW()),
(85, 29, 'Siêu thị điện máy', 'electronics-supermarket', 'active', NOW(), NOW()),
(86, 29, 'Trung tâm bảo hành Apple', 'apple-service-center', 'active', NOW(), NOW()),
(87, 50, 'Coworking Space chuyên nghiệp', 'professional-coworking', 'active', NOW(), NOW()),
(88, 50, 'Văn phòng ảo/Chia sẻ', 'shared-office', 'active', NOW(), NOW()),
(89, 47, 'Công ty bảo hiểm nhân thọ', 'life-insurance-company', 'active', NOW(), NOW()),
(90, 47, 'Sàn giao dịch chứng khoán', 'stock-exchange', 'active', NOW(), NOW()),
(91, 18, 'Phòng tập Gym cao cấp', 'premium-gym', 'active', NOW(), NOW()),
(92, 18, 'Trung tâm Yoga & Pilates', 'yoga-pilates-center', 'active', NOW(), NOW()),
(93, 21, 'Thẩm mỹ viện quốc tế', 'intl-beauty-salon', 'active', NOW(), NOW()),
(94, 21, 'Phòng khám Nha khoa kỹ thuật cao', 'high-tech-dental-clinic', 'active', NOW(), NOW()),
(95, 33, 'Dịch vụ giặt sấy lấy liền', 'express-laundry', 'active', NOW(), NOW()),
(96, 33, 'Vệ sinh công nghiệp', 'industrial-cleaning', 'active', NOW(), NOW()),
(97, 22, 'Trung tâm đào tạo nghề', 'vocational-training-center', 'active', NOW(), NOW()),
(98, 22, 'Thư viện tổng hợp thành phố', 'city-library', 'active', NOW(), NOW()),
(99, 12, 'Hợp tác xã làng nghề', 'craft-village-coop', 'active', NOW(), NOW()),
(100, 12, 'Trung tâm giới thiệu sản phẩm OCOP', 'ocop-product-center', 'active', NOW(), NOW());
