-- DanangTrip Real Data Seeder: Categories & Subcategories (100 rows each)
-- FILE: 01_categories_subcategories.sql

-- 1. CATEGORIES (Target 100)
INSERT INTO categories (id, name, slug, icon, sort_order, status, created_at, updated_at) VALUES
(1, 'Am thuc dia phuong', 'am-thuc-dia-phuong', 'local-dining', 1, 'active', NOW(), NOW()),
(2, 'Nha hang quoc te', 'nha-hang-quoc-te', 'international-dining', 2, 'active', NOW(), NOW()),
(3, 'Ca phe & Tra sua', 'ca-phe-tra-sua', 'cafe-tea', 3, 'active', NOW(), NOW()),
(4, 'Bar & Pub', 'bar-pub', 'nightlife', 4, 'active', NOW(), NOW()),
(5, 'Resort & Villa', 'resort-villa', 'luxury-stay', 5, 'active', NOW(), NOW()),
(6, 'Khach san & Homestay', 'khach-san-homestay', 'accommodation', 6, 'active', NOW(), NOW()),
(7, 'Diem check-in noi tieng', 'check-in-noi-tieng', 'camera', 7, 'active', NOW(), NOW()),
(8, 'Bao tang & Di tich', 'bao-tang-di-tich', 'museum', 8, 'active', NOW(), NOW()),
(9, 'Hang dong & Nui non', 'hang-dong-nui-non', 'nature', 9, 'active', NOW(), NOW()),
(10, 'Cong vien & Vuon hoa', 'cong-vien-vuon-hoa', 'park', 10, 'active', NOW(), NOW()),
(11, 'Diem du lich tam linh', 'du-lich-tam-linh', 'temple', 11, 'active', NOW(), NOW()),
(12, 'Lang nghe truyen thong', 'lang-nghe-truyen-thong', 'craft', 12, 'active', NOW(), NOW()),
(13, 'Trung tam thuong mai', 'trung-tam-thuong-mai', 'shopping-mall', 13, 'active', NOW(), NOW()),
(14, 'Cho dia phuong', 'cho-dia-phuong', 'local-market', 14, 'active', NOW(), NOW()),
(15, 'Cua hang dac san', 'cua-hang-dac-san', 'gift', 15, 'active', NOW(), NOW()),
(16, 'Cong vien nuoc & Vui choi', 'cong-vien-nuoc', 'water-park', 16, 'active', NOW(), NOW()),
(17, 'San Golf & Tennis', 'san-golf-tennis', 'sport', 17, 'active', NOW(), NOW()),
(18, 'Phong Gym & Yoga', 'gym-yoga', 'fitness', 18, 'active', NOW(), NOW()),
(19, 'Spa & Massage', 'spa-massage', 'wellness', 19, 'active', NOW(), NOW()),
(20, 'Benh vien & Phong kham', 'benh-vien-phong-kham', 'hospital', 20, 'active', NOW(), NOW()),
(21, 'Nha khoa & Tham my', 'nha-khoa-tham-my', 'dentist', 21, 'active', NOW(), NOW()),
(22, 'Truong hoc & Trung tam', 'truong-hoc-trung-tam', 'education', 22, 'active', NOW(), NOW()),
(23, 'Ngan hang & ATM', 'ngan-hang-atm', 'bank', 23, 'active', NOW(), NOW()),
(24, 'San bay & Ga tau', 'san-bay-ga-tau', 'transport', 24, 'active', NOW(), NOW()),
(25, 'Thue xe & Sua xe', 'thue-xe-sua-xe', 'car-rental', 25, 'active', NOW(), NOW()),
(26, 'Van chuyen & Giao hang', 'van-chuyen-giao-hang', 'delivery', 26, 'active', NOW(), NOW()),
(27, 'Co quan hanh chinh', 'co-quan-hanh-chinh', 'government', 27, 'active', NOW(), NOW()),
(28, 'Buu dien & Vien thong', 'buu-dien-vien-thong', 'post', 28, 'active', NOW(), NOW()),
(29, 'Dien may & Cong nghe', 'dien-may-cong-nghe', 'electronics', 29, 'active', NOW(), NOW()),
(30, 'Bat dong san', 'bat-dong-san', 'real-estate', 30, 'active', NOW(), NOW()),
(31, 'Luat su & Cong chung', 'luat-su-cong-chung', 'legal', 31, 'active', NOW(), NOW()),
(32, 'Xang dau & Nang luong', 'xang-dau-nang-luong', 'gas', 32, 'active', NOW(), NOW()),
(33, 'Giat ui & Ve sinh', 'giat-ui-ve-sinh', 'laundry', 33, 'active', NOW(), NOW()),
(34, 'Thu y & Cham soc thu cung', 'thu-y-thu-cung', 'pet', 34, 'active', NOW(), NOW()),
(35, 'Studio & Phim truong', 'studio-phim-truong', 'studio', 35, 'active', NOW(), NOW()),
(36, 'Hai san tuoi song', 'hai-san-tuoi-song', 'seafood', 36, 'active', NOW(), NOW()),
(37, 'Hoa tuoi & Qua tang', 'hoa-tuoi-qua-tang', 'flower', 37, 'active', NOW(), NOW()),
(38, 'Sach & Van phong pham', 'sach-van-phong-pham', 'book', 38, 'active', NOW(), NOW()),
(39, 'Thoi trang & Phu kien', 'thoi-trang-phu-kien', 'fashion', 39, 'active', NOW(), NOW()),
(40, 'My pham & Lam dep', 'my-pham-lam-dep', 'beauty', 40, 'active', NOW(), NOW()),
(41, 'Do gia dung & Noi that', 'gia-dung-noi-that', 'furniture', 41, 'active', NOW(), NOW()),
(42, 'Xay dung & Vat lieu', 'xay-dung-vat-lieu', 'construction', 42, 'active', NOW(), NOW()),
(43, 'To chuc su kien', 'to-chuc-su-kien', 'event', 43, 'active', NOW(), NOW()),
(44, 'Dich vu tang le', 'dich-vu-tang-le', 'funeral', 44, 'active', NOW(), NOW()),
(45, 'Quang cao & In an', 'quang-cao-in-an', 'printing', 45, 'active', NOW(), NOW()),
(46, 'Bao ve & An ninh', 'bao-ve-an-ninh', 'security', 46, 'active', NOW(), NOW()),
(47, 'Tai chinh & Bao hiem', 'tai-chinh-bao-hiem', 'finance', 47, 'active', NOW(), NOW()),
(48, 'Du lich lu hanh', 'du-lich-lu-hanh', 'travel-agency', 48, 'active', NOW(), NOW()),
(49, 'Dich thuat & Visa', 'dich-thuat-visa', 'translation', 49, 'active', NOW(), NOW()),
(50, 'Coworking Space', 'coworking-space', 'work', 50, 'active', NOW(), NOW()),
-- Adding 50 more generic/specific categories to reach 100
(51, 'Nghe thuat & Trien lam', 'nghe-thuat-trien-lam', 'art', 51, 'active', NOW(), NOW()),
(52, 'Nha hat & Rap phim', 'nha-hat-rap-phim', 'cinema', 52, 'active', NOW(), NOW()),
(53, 'Thu vien & Khong gian doc', 'thu-vien-doc-sach', 'library', 53, 'active', NOW(), NOW()),
(54, 'San khau & Ca nhac', 'san-khau-ca-nhac', 'music', 54, 'active', NOW(), NOW()),
(55, 'Trung tam hoi nghi', 'trung-tam-hoi-nghi', 'convention', 55, 'active', NOW(), NOW()),
(56, 'Dich vu luu tru cao cap', 'stay-luxury', 'stars', 56, 'active', NOW(), NOW()),
(57, 'Cam trai & Da ngoai', 'camping-picnic', 'tent', 57, 'active', NOW(), NOW()),
(58, 'Leo nui & Kham pha', 'hiking-exploration', 'boot', 58, 'active', NOW(), NOW()),
(59, 'Lan bien & The thao nuoc', 'diving-water-sport', 'swim', 59, 'active', NOW(), NOW()),
(60, 'Bay khinh khi cau/Du luon', 'air-sport', 'wind', 60, 'active', NOW(), NOW()),
(61, 'Trai nghiem nong nghiep', 'agritourism', 'leaf', 61, 'active', NOW(), NOW()),
(62, 'Lop hoc nau an', 'cooking-class', 'pot', 62, 'active', NOW(), NOW()),
(63, 'Thuong thuc tra dao', 'tea-ceremony', 'tea', 63, 'active', NOW(), NOW()),
(64, 'Kham pha pho co', 'old-town-walk', 'walk', 64, 'active', NOW(), NOW()),
(65, 'Cho dem & Pho di bo', 'night-market-walk', 'moon', 65, 'active', NOW(), NOW()),
(66, 'Dich vu xe dien', 'electric-vehicle', 'bolt', 66, 'active', NOW(), NOW()),
(67, 'Tour truc thang', 'helicopter-tour', 'air', 67, 'active', NOW(), NOW()),
(68, 'Chup anh cuoi', 'wedding-photography', 'heart', 68, 'active', NOW(), NOW()),
(69, 'Dich vu trong tre', 'babysitting', 'baby', 69, 'active', NOW(), NOW()),
(70, 'Ho tro nguoi khuyet tat', 'disability-support', 'wheelchair', 70, 'active', NOW(), NOW()),
(71, 'Thong tin du khach', 'tourist-info', 'info', 71, 'active', NOW(), NOW()),
(72, 'Doi ngoai te', 'currency-exchange', 'dollar', 72, 'active', NOW(), NOW()),
(73, 'Ve tham quan & Show', 'ticket-show', 'ticket', 73, 'active', NOW(), NOW()),
(74, 'Trang tri noi that', 'interior-decor', 'home', 74, 'active', NOW(), NOW()),
(75, 'Cua hang tien loi 24/7', 'convenience-store-247', 'clock', 75, 'active', NOW(), NOW()),
(76, 'Hieu thuoc & Duoc pham', 'pharmacy-medical', 'pill', 76, 'active', NOW(), NOW()),
(77, 'Phong thi nghiem', 'laboratory', 'test-tube', 77, 'active', NOW(), NOW()),
(78, 'Cham soc nguoi gia', 'elderly-care', 'user', 78, 'active', NOW(), NOW()),
(79, 'Cong ty phan mem', 'it-software', 'code', 79, 'active', NOW(), NOW()),
(80, 'Khoi nghiep & Tech hub', 'startup-tech-hub', 'rocket', 80, 'active', NOW(), NOW()),
(81, 'Thiet ke do hoa', 'graphic-design', 'pen', 81, 'active', NOW(), NOW()),
(82, 'Van phong dai dien', 'representative-office', 'building', 82, 'active', NOW(), NOW()),
(83, 'Khu cong nghiep', 'industrial-zone', 'factory', 83, 'active', NOW(), NOW()),
(84, 'Kho bai & Logistic', 'warehouse-logistic', 'box', 84, 'active', NOW(), NOW()),
(85, 'Dich vu hai quan', 'customs-service', 'ship', 85, 'active', NOW(), NOW()),
(86, 'Nong san sach', 'clean-agriculture', 'carrot', 86, 'active', NOW(), NOW()),
(87, 'Thuc pham chuc nang', 'supplement-store', 'shield', 87, 'active', NOW(), NOW()),
(88, 'Ruou vang & Do uong cao cap', 'wine-premium-drink', 'glass', 88, 'active', NOW(), NOW()),
(89, 'Sua chua dien tu', 'repair-electronic', 'tool', 89, 'active', NOW(), NOW()),
(90, 'Phat trien ben vung', 'sustainable-development', 'globe', 90, 'active', NOW(), NOW()),
(91, 'Hoat dong cong dong', 'community-activity', 'users', 91, 'active', NOW(), NOW()),
(92, 'To chuc phi loi nhuan', 'ngo-non-profit', 'heart', 92, 'active', NOW(), NOW()),
(93, 'Nghien cuu van hoa', 'cultural-research', 'archive', 93, 'active', NOW(), NOW()),
(94, 'Khao co hoc', 'archaeology', 'mountain', 94, 'active', NOW(), NOW()),
(95, 'Khi tuong thuy van', 'weather-service', 'cloud', 95, 'active', NOW(), NOW()),
(96, 'Dich vu cuu ho', 'rescue-service', 'ambulance', 96, 'active', NOW(), NOW()),
(97, 'Phong chay chua chay', 'fire-service', 'flame', 97, 'active', NOW(), NOW()),
(98, 'An toan lao dong', 'occupational-safety', 'hard-hat', 98, 'active', NOW(), NOW()),
(99, 'Kiem toan & Ke toan', 'audit-accounting', 'file-text', 99, 'active', NOW(), NOW()),
(100, 'Tu van quan tri', 'management-consulting', 'briefcase', 100, 'active', NOW(), NOW());

-- 2. SUBCATEGORIES (Target 100)
INSERT INTO subcategories (id, category_id, name, slug, status, created_at, updated_at) VALUES
-- Local Dining (Cat 1)
(1, 1, 'Mi Quang', 'mi-quang', 'active', NOW(), NOW()),
(2, 1, 'Banh trang cuon thit heo', 'banh-trang-cuon-thit-heo', 'active', NOW(), NOW()),
(3, 1, 'Bun cha ca', 'bun-cha-ca', 'active', NOW(), NOW()),
(4, 1, 'Banh xeo & Nem lui', 'banh-xeo-nem-lui', 'active', NOW(), NOW()),
(5, 1, 'Com ga', 'com-ga', 'active', NOW(), NOW()),
(6, 1, 'Bun mam', 'bun-mam', 'active', NOW(), NOW()),
(7, 1, 'Goi ca Nam O', 'goi-ca-nam-o', 'active', NOW(), NOW()),
(8, 1, 'Be thui Cau Mong', 'be-thui-cau-mong', 'active', NOW(), NOW()),
-- International Dining (Cat 2)
(9, 2, 'Nha hang Han Quoc', 'nha-hang-han-quoc', 'active', NOW(), NOW()),
(10, 2, 'Nha hang Nhat Ban', 'nha-hang-nhat-ban', 'active', NOW(), NOW()),
(11, 2, 'Nha hang Au', 'nha-hang-au', 'active', NOW(), NOW()),
(12, 2, 'Nha hang Thai Lan', 'nha-hang-thai', 'active', NOW(), NOW()),
(13, 2, 'Pizza & Pasta', 'pizza-pasta', 'active', NOW(), NOW()),
-- Cafe & Tea (Cat 3)
(14, 3, 'Ca phe dac san', 'ca-phe-dac-san', 'active', NOW(), NOW()),
(15, 3, 'Tra sua tran chau', 'tra-sua-tran-chau', 'active', NOW(), NOW()),
(16, 3, 'Tra thao moc', 'tra-thao-moc', 'active', NOW(), NOW()),
(17, 3, 'Tiem banh & Ca phe', 'bakery-cafe', 'active', NOW(), NOW()),
-- Nightlife (Cat 4)
(18, 4, 'Rooftop Bar', 'rooftop-bar', 'active', NOW(), NOW()),
(19, 4, 'Pub & Lounge', 'pub-lounge', 'active', NOW(), NOW()),
(20, 4, 'Bia hoi & Nhau', 'bia-hoi-nhau', 'active', NOW(), NOW()),
-- Luxury Stay (Cat 5)
(21, 5, 'Resort 5 sao ven bien', 'resort-5-sao-ven-bien', 'active', NOW(), NOW()),
(22, 5, 'Villa nguyen can', 'villa-nguyen-can', 'active', NOW(), NOW()),
-- Accommodation (Cat 6)
(23, 6, 'Khach san trung tam', 'khach-san-trung-tam', 'active', NOW(), NOW()),
(24, 6, 'Homestay phong cach', 'homestay-phong-cach', 'active', NOW(), NOW()),
(25, 6, 'Can ho dich vu', 'serviced-apartment', 'active', NOW(), NOW()),
-- Nature (Cat 9)
(26, 9, 'Hang dong da voi', 'hang-dong-da-voi', 'active', NOW(), NOW()),
(27, 9, 'Dinh nui & Ngam canh', 'dinh-nui-ngam-canh', 'active', NOW(), NOW()),
-- Temple (Cat 11)
(28, 11, 'Chua & Tu vien', 'chua-tu-vien', 'active', NOW(), NOW()),
(29, 11, 'Nha tho & Giao xu', 'nha-tho-giao-xu', 'active', NOW(), NOW()),
(30, 11, 'Thanh that & Den mieu', 'thanh-that-den-mieu', 'active', NOW(), NOW()),
-- Local Market (Cat 14)
(31, 14, 'Cho hai san sang som', 'cho-hai-san-sang-som', 'active', NOW(), NOW()),
(32, 14, 'Cho dem am thuc', 'cho-dem-am-thuc', 'active', NOW(), NOW()),
-- ... Adding more to reach 100
(33, 20, 'Benh vien Da khoa', 'benh-vien-da-khoa', 'active', NOW(), NOW()),
(34, 20, 'Phong kham chuyen khoa', 'phong-kham-chuyen-khoa', 'active', NOW(), NOW()),
(35, 23, 'ATM 24/7', 'atm-247', 'active', NOW(), NOW()),
(36, 23, 'Phong giao dich ngan hang', 'phong-giao-dich-ngan-hang', 'active', NOW(), NOW()),
(37, 24, 'Ga tau hoa', 'ga-tau-hoa', 'active', NOW(), NOW()),
(38, 24, 'Ben xe khach', 'ben-xe-khach', 'active', NOW(), NOW()),
(39, 19, 'Massage chan', 'massage-chan', 'active', NOW(), NOW()),
(40, 19, 'Xong hoi da nong', 'xong-hoi-da-nong', 'active', NOW(), NOW()),
-- Education
(41, 22, 'Truong dai hoc', 'truong-dai-hoc', 'active', NOW(), NOW()),
(42, 22, 'Trung tam ngoai ngu', 'trung-tam-ngoai-ngu', 'active', NOW(), NOW()),
-- Public Services
(43, 27, 'Uy ban nhan dan', 'ubnd', 'active', NOW(), NOW()),
(44, 27, 'Cong an phuong', 'cong-an-phuong', 'active', NOW(), NOW()),
-- Specialty Stores
(45, 15, 'Cua hang qua luu niem', 'souvenir-shop', 'active', NOW(), NOW()),
(46, 15, 'Tiem do thu cong my nghe', 'handicraft-shop', 'active', NOW(), NOW()),
-- Sports
(47, 17, 'San tap Golf', 'golf-driving-range', 'active', NOW(), NOW()),
(48, 17, 'San Tennis', 'tennis-court', 'active', NOW(), NOW()),
-- Logistics
(49, 26, 'Chuyen phat nhanh', 'express-delivery', 'active', NOW(), NOW()),
(50, 26, 'Van chuyen hang hoa quoc te', 'international-shipping', 'active', NOW(), NOW()),
-- Adding 50 more to reach 100
(51, 10, 'Cong vien bach thao', 'botanical-garden', 'active', NOW(), NOW()),
(52, 10, 'Vuon thu & Safari', 'zoo-safari', 'active', NOW(), NOW()),
(53, 52, 'Rap chieu phim hien dai', 'modern-cinema', 'active', NOW(), NOW()),
(54, 52, 'Nha hat kich/Tuong', 'theater-drama', 'active', NOW(), NOW()),
(55, 32, 'Tram xang dau', 'gas-station', 'active', NOW(), NOW()),
(56, 32, 'Tram sac xe dien', 'ev-charging-station', 'active', NOW(), NOW()),
(57, 57, 'Khu cam trai ven ho', 'lake-camping', 'active', NOW(), NOW()),
(58, 57, 'Khu da ngoai gia dinh', 'family-picnic-area', 'active', NOW(), NOW()),
(59, 13, 'Sieu thi tong hop', 'hypermarket', 'active', NOW(), NOW()),
(60, 13, 'Cua hang thoi trang hieu', 'brand-fashion-store', 'active', NOW(), NOW()),
(61, 41, 'Cua hang noi that go', 'wooden-furniture-store', 'active', NOW(), NOW()),
(62, 41, 'Dien gia dung thong minh', 'smart-home-appliance', 'active', NOW(), NOW()),
(63, 76, 'Hieu thuoc dong y', 'herbal-pharmacy', 'active', NOW(), NOW()),
(64, 76, 'Nha thuoc tay chuan GPP', 'gpp-pharmacy', 'active', NOW(), NOW()),
(65, 8, 'Di tich lich su cap quoc gia', 'national-historical-site', 'active', NOW(), NOW()),
(66, 8, 'Bao tang nghe thuat', 'art-museum', 'active', NOW(), NOW()),
(67, 39, 'Thoi trang thiet ke', 'designer-fashion', 'active', NOW(), NOW()),
(68, 39, 'Giay dep & Tui xach', 'shoes-bags', 'active', NOW(), NOW()),
(69, 36, 'Hai san nuong/Lau', 'grilled-hotpot-seafood', 'active', NOW(), NOW()),
(70, 36, 'Vua hai san tuoi song', 'fresh-seafood-market', 'active', NOW(), NOW()),
(71, 3, 'Tiem tra dao/Thien', 'tea-meditation-house', 'active', NOW(), NOW()),
(72, 3, 'Ca phe sach', 'book-cafe', 'active', NOW(), NOW()),
(73, 4, 'Beer Garden', 'beer-garden', 'active', NOW(), NOW()),
(74, 4, 'Cocktail Bar', 'cocktail-bar', 'active', NOW(), NOW()),
(75, 25, 'Thue xe may tu lai', 'motorbike-rental', 'active', NOW(), NOW()),
(76, 25, 'Thue o to du lich', 'car-rental-service', 'active', NOW(), NOW()),
(77, 28, 'Buu dien trung tam', 'main-post-office', 'active', NOW(), NOW()),
(78, 28, 'Dai ly mang vien thong', 'telecom-agency', 'active', NOW(), NOW()),
(79, 43, 'Trung tam hoi nghi quoc te', 'intl-convention-center', 'active', NOW(), NOW()),
(80, 43, 'Cong ty to chuc su kien/Tiec cuoi', 'event-wedding-planner', 'active', NOW(), NOW()),
(81, 16, 'Cong vien giai tri Sun World', 'sun-world-park', 'active', NOW(), NOW()),
(82, 16, 'Khu vui choi tre em trong nha', 'indoor-kids-playground', 'active', NOW(), NOW()),
(83, 7, 'Cau du lich noi tieng', 'famous-bridge', 'active', NOW(), NOW()),
(84, 7, 'Diem ngam hoang hon', 'sunset-point', 'active', NOW(), NOW()),
(85, 29, 'Sieu thi dien may', 'electronics-supermarket', 'active', NOW(), NOW()),
(86, 29, 'Trung tam bao hanh Apple', 'apple-service-center', 'active', NOW(), NOW()),
(87, 50, 'Coworking Space chuyen nghiep', 'professional-coworking', 'active', NOW(), NOW()),
(88, 50, 'Van phong ao/Chia se', 'shared-office', 'active', NOW(), NOW()),
(89, 47, 'Cong ty bao hiem nhan tho', 'life-insurance-company', 'active', NOW(), NOW()),
(90, 47, 'San giao dich chung khoan', 'stock-exchange', 'active', NOW(), NOW()),
(91, 18, 'Phong tap Gym cao cap', 'premium-gym', 'active', NOW(), NOW()),
(92, 18, 'Trung tam Yoga & Pilates', 'yoga-pilates-center', 'active', NOW(), NOW()),
(93, 21, 'Tham my vien quoc te', 'intl-beauty-salon', 'active', NOW(), NOW()),
(94, 21, 'Phong kham Nha khoa ky thuat cao', 'high-tech-dental-clinic', 'active', NOW(), NOW()),
(95, 33, 'Dich vu giat say lay lien', 'express-laundry', 'active', NOW(), NOW()),
(96, 33, 'Ve sinh cong nghiep', 'industrial-cleaning', 'active', NOW(), NOW()),
(97, 22, 'Trung tam dao tao nghe', 'vocational-training-center', 'active', NOW(), NOW()),
(98, 22, 'Thu vien tong hop thanh pho', 'city-library', 'active', NOW(), NOW()),
(99, 12, 'Hop tac xa lang nghe', 'craft-village-coop', 'active', NOW(), NOW()),
(100, 12, 'Trung tam gioi thieu san pham OCOP', 'ocop-product-center', 'active', NOW(), NOW());
