-- DanangTrip Real Data Seeder: Tour & Blog Categories (100 rows each)
-- FILE: 03_tour_blog_categories.sql

-- 1. TOUR_CATEGORIES (Target 100)
INSERT INTO tour_categories (id, name, slug, description, icon, sort_order, status, created_at, updated_at) VALUES
(1, 'Tour Ba Na Hills', 'tour-ba-na-hills', 'Kham pha dinh nui Chua, Cau Vang va lang Phap.', NULL, 1, 'active', NOW(), NOW()),
(2, 'Tour Pho Co Hoi An', 'tour-hoi-an', 'Tim ve net hoai co cua thuong cang sam uat.', NULL, 2, 'active', NOW(), NOW()),
(3, 'Tour Co Do Hue', 'tour-hue', 'Hanh trinh di san qua cac lang tam va cung dien.', NULL, 3, 'active', NOW(), NOW()),
(4, 'Tour Bien & Dao', 'tour-bien-dao', 'Lan ngam san ho tai Cu Lao Cham, Ban dao Son Tra.', NULL, 4, 'active', NOW(), NOW()),
(5, 'Tour Kham Pha Thien Nhien', 'tour-thien-nhien', 'Trekking rung Son Tra, suoi khoang nong.', NULL, 5, 'active', NOW(), NOW()),
(6, 'Tour Am Thuc', 'tour-am-thuc', 'Thuong thuc dac san duong pho va lop hoc nau an.', NULL, 6, 'active', NOW(), NOW()),
(7, 'Tour Mao Hiem', 'tour-mao-hiem', 'Leo nui, du day zipline, cheo thuyen kayak.', NULL, 7, 'active', NOW(), NOW()),
(8, 'Tour Nghi Duong', 'tour-nghi-duong', 'Thu gian tai cac resort cao cap va tam khoang.', NULL, 8, 'active', NOW(), NOW()),
(9, 'Tour Trong Ngay', 'tour-trong-ngay', 'Cac tour khoi hanh va ket thuc trong ngay.', NULL, 9, 'active', NOW(), NOW()),
(10, 'Tour Dai Ngay (Xuyen Viet)', 'tour-dai-ngay', 'Hanh trinh kham pha nhieu tinh thanh.', NULL, 10, 'active', NOW(), NOW()),
-- Adding 90 more tour categories to reach 100
(11, 'Tour Ghep Doan', 'tour-ghep-doan', 'Tiet kiem chi phi khi di cung nhom khach khac.', NULL, 11, 'active', NOW(), NOW()),
(12, 'Tour Rieng Cho Gia Dinh', 'tour-gia-dinh', 'Lich trinh linh hoat, khong gian rieng tu.', NULL, 12, 'active', NOW(), NOW()),
(13, 'Tour Trang Mat', 'tour-trang-mat', 'Danh rieng cho cac cap doi moi cuoi.', NULL, 13, 'active', NOW(), NOW()),
(14, 'Tour Nhiep Anh', 'tour-nhiep-anh', 'San anh tai cac diem dep nhat mien Trung.', NULL, 14, 'active', NOW(), NOW()),
(15, 'Tour Lang Nghe', 'tour-lang-nghe', 'Tham lang da Non Nuoc, lang gom Thanh Ha.', NULL, 15, 'active', NOW(), NOW()),
(16, 'Tour Tam Linh', 'tour-tam-linh', 'Vieng chua Linh Ung, Thanh dia My Son.', NULL, 16, 'active', NOW(), NOW()),
(17, 'Tour Giao Duc (Study Tour)', 'tour-giao-duc', 'Ket hop hoc tap va trai nghiem thuc te.', NULL, 17, 'active', NOW(), NOW()),
(18, 'Tour MICE (Su kien/Hoi thao)', 'tour-mice', 'To chuc su kien ket hop nghi duong cong ty.', NULL, 18, 'active', NOW(), NOW()),
(19, 'Tour Team Building', 'tour-team-building', 'Hoat dong gan ket doi ngu tren bai bien.', NULL, 19, 'active', NOW(), NOW()),
(20, 'Tour Luxury (Hang Sang)', 'tour-luxury', 'Dich vu dang cap nhat, xe sang, resort 5+.', NULL, 20, 'active', NOW(), NOW()),
(21, 'Tour Bang Xe Jeep', 'tour-xe-jeep', 'Trai nghiem mao hiem tren deo Hai Van.', NULL, 21, 'active', NOW(), NOW()),
(22, 'Tour Du Thuyen Song Han', 'tour-du-thuyen', 'Ngam cau Rong phun lua tu tren song.', NULL, 22, 'active', NOW(), NOW()),
(23, 'Tour Truc Thang Ngam Canh', 'tour-truc-thang', 'Goc nhin toan canh Da Nang tu tren cao.', NULL, 23, 'active', NOW(), NOW()),
(24, 'Tour Dap Xe Lang Que', 'tour-dap-xe', 'Kham pha cuoc song binh yen vung ven Hoi An.', NULL, 24, 'active', NOW(), NOW()),
(25, 'Tour Cheo Thung Rung Dua', 'tour-rung-dua', 'Trai nghiem van hoa song nuoc Cam Thanh.', NULL, 25, 'active', NOW(), NOW()),
(26, 'Tour Ngam Hoang Hon', 'tour-hoang-hon', 'Thuong thuc tra chieu va ngam mat troi lan.', NULL, 26, 'active', NOW(), NOW()),
(27, 'Tour Binh Minh Tren Bien', 'tour-binh-minh', 'Don ngay moi va xem keo luoi cua ngu dan.', NULL, 27, 'active', NOW(), NOW()),
(28, 'Tour Cho Dem & Mua Sam', 'tour-cho-dem', 'Kham pha cho Con, cho Han ve dem.', NULL, 28, 'active', NOW(), NOW()),
(29, 'Tour Xe May Ban Dia', 'tour-xe-may', 'Di sau vao ngo ngach cung huong dan vien ban dia.', NULL, 29, 'active', NOW(), NOW()),
(30, 'Tour Golf Nghi Duong', 'tour-golf', 'Choi golf tai cac san dang cap quoc te.', NULL, 30, 'active', NOW(), NOW()),
(31, 'Tour Cham Soc Suc Khoe', 'tour-wellness', 'Yoga bai bien va tri lieu thao moc.', NULL, 31, 'active', NOW(), NOW()),
(32, 'Tour Kham Pha Hang Dong', 'tour-hang-dong', 'Tham dong Phong Nha, Thien Duong (Quang Binh).', NULL, 32, 'active', NOW(), NOW()),
(33, 'Tour Sinh Thai Ganh Ban', 'tour-ganh-ban', 'Lan bien ngam san ho hoang so.', NULL, 33, 'active', NOW(), NOW()),
(34, 'Tour Dao Ly Son (Quang Ngai)', 'tour-ly-son', 'Kham pha vuong quoc toi va nui lua.', NULL, 34, 'active', NOW(), NOW()),
(35, 'Tour Quy Nhon - Phu Yen', 'tour-quy-nhon', 'Con duong di san va bien xanh.', NULL, 35, 'active', NOW(), NOW()),
(36, 'Tour Tay Nguyen (Kon Tum/Gia Lai)', 'tour-tay-nguyen', 'Tim ve dai ngan tu Da Nang.', NULL, 36, 'active', NOW(), NOW()),
(37, 'Tour Mua Phao Hoa (DIFF)', 'tour-phao-hoa', 'Vi tri xem phao hoa dep nhat.', NULL, 37, 'active', NOW(), NOW()),
(38, 'Tour Tet Nguyen Dan', 'tour-tet', 'Trai nghiem tet co truyen mien Trung.', NULL, 38, 'active', NOW(), NOW()),
(39, 'Tour Le 30/4 & 1/5', 'tour-le-304', 'Lich trinh dac biet cho ky nghi le.', NULL, 39, 'active', NOW(), NOW()),
(40, 'Tour Mua He Ruc Ro', 'tour-mua-he', 'Cac hoat dong bien soi dong nhat.', NULL, 40, 'active', NOW(), NOW()),
(41, 'Tour Thu Vang Mien Trung', 'tour-mua-thu', 'Cam nhan tiet troi diu mat cua Hue va Hoi An.', NULL, 41, 'active', NOW(), NOW()),
(42, 'Tour Dong Am Ap', 'tour-mua-dong', 'Thuong thuc am thuc nong hoi va pho vang.', NULL, 42, 'active', NOW(), NOW()),
(43, 'Tour Tinh Nguyen', 'tour-tinh-nguyen', 'Ket hop du lich va ho tro cong dong dia phuong.', NULL, 43, 'active', NOW(), NOW()),
(44, 'Tour Ve Tranh Ngoai Troi', 'tour-drawing', 'Ghi lai ve dep pho co qua net ve.', NULL, 44, 'active', NOW(), NOW()),
(45, 'Tour Than Tai & Suoi Khoang', 'tour-suoi-khoang', 'Nghi duong suoi khoang nong Nui Than Tai.', NULL, 45, 'active', NOW(), NOW()),
(46, 'Tour Cong Vien Nuoc Holand', 'tour-holand', 'Vui choi tai khu phuc hop giai tri moi.', NULL, 46, 'active', NOW(), NOW()),
(47, 'Tour Bao Tang 3D TrickEye', 'tour-3d-museum', 'The gioi ao anh day thu vi.', NULL, 47, 'active', NOW(), NOW()),
(48, 'Tour Nguoc Dong Song Thu Bon', 'tour-song-thu-bon', 'Tim hieu van hoa ven song.', NULL, 48, 'active', NOW(), NOW()),
(49, 'Tour Tham Nha Vuon Hue', 'tour-nha-vuon', 'Kien truc dac sac cua gioi quy toc xua.', NULL, 49, 'active', NOW(), NOW()),
(50, 'Tour Ca Phe & Chuyen Ke', 'tour-story-cafe', 'Nghe nhung cau chuyen lich su ben tach ca phe.', NULL, 50, 'active', NOW(), NOW()),
-- Synthetic categories 51-100 to meet volume
(51, 'Tour Chay Bo (Running Tour)', 'tour-running', 'Kham pha thanh pho buoi som qua cac cung duong chay.', NULL, 51, 'active', NOW(), NOW()),
(52, 'Tour Yoga Don Binh Minh', 'tour-sunrise-yoga', 'Tai tao nang luong tren bai bien My Khe.', NULL, 52, 'active', NOW(), NOW()),
(53, 'Tour Workshop Thu Cong', 'tour-workshop', 'Hoc lam long den, lam gom trong 1 buoi.', NULL, 53, 'active', NOW(), NOW()),
(54, 'Tour Kham Pha Cho Ca', 'tour-fish-market', 'Trai nghiem nhip song ngu dan luc 4h sang.', NULL, 54, 'active', NOW(), NOW()),
(55, 'Tour Tim Hieu Cao Lau', 'tour-cao-lau', 'Di sau vao quy trinh lam mon dac san Hoi An.', NULL, 55, 'active', NOW(), NOW()),
(56, 'Tour San Vuon & Cay Canh', 'tour-garden', 'Tham cac khu vuon nghe thuat tai Hoa Vang.', NULL, 56, 'active', NOW(), NOW()),
(57, 'Tour Hanh Trinh Di San Mien Trung', 'tour-heritage-path', 'Chuoi tour Hue - Da Nang - Hoi An - My Son.', NULL, 57, 'active', NOW(), NOW()),
(58, 'Tour Xe Buyt 2 Tang', 'tour-coco-bus', 'Ngam nhin thanh pho tu xe buyt mui tran.', NULL, 58, 'active', NOW(), NOW()),
(59, 'Tour Tau Hoa Da Nang - Hue', 'tour-train-hue', 'Hanh trinh ngam deo Hai Van dep nhat.', NULL, 59, 'active', NOW(), NOW()),
(60, 'Tour Kham Pha Ho Hoa Trung', 'tour-lake-camp', 'Cam trai va cheo SUP tai ho.', NULL, 60, 'active', NOW(), NOW()),
(61, 'Tour Dinh Ban Co', 'tour-ban-co', 'Len dinh Son Tra choi co cung tien ong.', NULL, 61, 'active', NOW(), NOW()),
(62, 'Tour Cay Da Ngan Nam', 'tour-cay-da', 'Tim hieu he sinh thai rung Son Tra.', NULL, 62, 'active', NOW(), NOW()),
(63, 'Tour Ghenh Bang Trekking', 'tour-ghenh-bang', 'Chuyen di bo doc bo bien hoang so.', NULL, 63, 'active', NOW(), NOW()),
(64, 'Tour Bai But - Bai Rang', 'tour-bai-but', 'Thuong thuc hai san ben ghenh da.', NULL, 64, 'active', NOW(), NOW()),
(65, 'Tour Truot Thac Hoa Phu Thanh', 'tour-truot-thac', 'Thu thach cam giac manh tren suoi.', NULL, 65, 'active', NOW(), NOW()),
(66, 'Tour Mikazuki Water Park', 'tour-mikazuki', 'Cong vien nuoc phong cach Nhat Ban.', NULL, 66, 'active', NOW(), NOW()),
(67, 'Tour Helio Center', 'tour-helio', 'Thien duong giai tri ban dem.', NULL, 67, 'active', NOW(), NOW()),
(68, 'Tour VinWonders Nam Hoi An', 'tour-vinwonders', 'Khu vui choi dang cap quoc te.', NULL, 68, 'active', NOW(), NOW()),
(69, 'Tour Rung Dua Bay Mau', 'tour-bay-mau', 'Cheo thung va mua thung dac sac.', NULL, 69, 'active', NOW(), NOW()),
(70, 'Tour Lang Gom Thanh Ha', 'tour-thanh-ha', 'Trai nghiem tu tay lam gom.', NULL, 70, 'active', NOW(), NOW()),
(71, 'Tour Lang Rau Tra Que', 'tour-tra-que', 'Mot ngay lam nong dan thuc thu.', NULL, 71, 'active', NOW(), NOW()),
(72, 'Tour Kim Bong Moc Nghe', 'tour-kim-bong', 'Tham lang nghe dong tau va cham khac go.', NULL, 72, 'active', NOW(), NOW()),
(73, 'Tour Lang Duc Dong Phuoc Kieu', 'tour-phuoc-kieu', 'Tim hieu nghe thuat duc dong lau doi.', NULL, 73, 'active', NOW(), NOW()),
(74, 'Tour Hoi Quan Phuc Kien', 'tour-phuc-kien', 'Kien truc Trung Hoa dac sac tai Hoi An.', NULL, 74, 'active', NOW(), NOW()),
(75, 'Tour Chua Cau Hoi An', 'tour-chua-cau', 'Bieu tuong lich su cua pho co.', NULL, 75, 'active', NOW(), NOW()),
(76, 'Tour Dai Noi Hue', 'tour-dai-noi', 'Kham pha hoang cung trieu Nguyen.', NULL, 76, 'active', NOW(), NOW()),
(77, 'Tour Lang Khai Dinh', 'tour-khai-dinh', 'Kien truc giao thoa Dong - Tay.', NULL, 77, 'active', NOW(), NOW()),
(78, 'Tour Lang Minh Mang', 'tour-minh-mang', 'Net dep uy nghiem va tho mong.', NULL, 78, 'active', NOW(), NOW()),
(79, 'Tour Lang Tu Duc', 'tour-tu-duc', 'Ve dep u tich va tinh te.', NULL, 79, 'active', NOW(), NOW()),
(80, 'Tour Chua Thien Mu', 'tour-thien-mu', 'Ngoi chua co nhat co do.', NULL, 80, 'active', NOW(), NOW()),
(81, 'Tour Ca Hue Tren Song Huong', 'tour-ca-hue', 'Thuong thuc nha nhac cung dinh.', NULL, 81, 'active', NOW(), NOW()),
(82, 'Tour Lang Huong Thuy Xuan', 'tour-thuy-xuan', 'Check-in cung nhung bo huong ruc ro.', NULL, 82, 'active', NOW(), NOW()),
(83, 'Tour Bach Ma Village', 'tour-bach-ma-vlg', 'Vung dat cua nhung chu lun Hobbit.', NULL, 83, 'active', NOW(), NOW()),
(84, 'Tour Dam Lap An', 'tour-lap-an', 'Tuyet tinh coc cua mien Trung.', NULL, 84, 'active', NOW(), NOW()),
(85, 'Tour Bien Lang Co', 'tour-lang-co', 'Mot trong nhung vinh bien dep nhat the gioi.', NULL, 85, 'active', NOW(), NOW()),
(86, 'Tour Pha Tam Giang', 'tour-tam-giang', 'Trai nghiem cuoc song ngu dan vung dam pha.', NULL, 86, 'active', NOW(), NOW()),
(87, 'Tour Suoi Voi', 'tour-suoi-voi', 'Tam suoi va thuong thuc ga nuong.', NULL, 87, 'active', NOW(), NOW()),
(88, 'Tour Ho Truoi - Thien Vien', 'tour-ho-truoi', 'Ve dep thanh tinh giua nui rung.', NULL, 88, 'active', NOW(), NOW()),
(89, 'Tour Lang Co - Hai Van', 'tour-lang-co-hai-van', 'Hanh trinh chinh phuc thien ha de nhat hung quan.', NULL, 89, 'active', NOW(), NOW()),
(90, 'Tour Suoi Mo Da Nang', 'tour-suoi-mo', 'Nghi mat ben dong suoi trong xanh.', NULL, 90, 'active', NOW(), NOW()),
(91, 'Tour Deo Hai Van Xe May', 'tour-hai-van-motor', 'Thu thach tay lai qua nhung cung duong deo.', NULL, 91, 'active', NOW(), NOW()),
(92, 'Tour Cu Lao Cham 2 Ngay 1 Dem', 'tour-cu-lao-2d1n', 'Trai nghiem dem tren dao hoang so.', NULL, 92, 'active', NOW(), NOW()),
(93, 'Tour Cau Muc Dem Da Nang', 'tour-cau-muc', 'Trai nghiem lam ngu dan thuc thu ban dem.', NULL, 93, 'active', NOW(), NOW()),
(94, 'Tour Ngam San Ho Hon Seo', 'tour-hon-seo', 'Diem lan bien moi la tai Da Nang.', NULL, 94, 'active', NOW(), NOW()),
(95, 'Tour Lang Co Phong Nam', 'tour-phong-nam', 'Net dep lang que Viet giua long thanh pho.', NULL, 95, 'active', NOW(), NOW()),
(96, 'Tour Tham Lang Ba Thu Bon', 'tour-lang-ba', 'Le hoi van hoa tin nguong doc dao.', NULL, 96, 'active', NOW(), NOW()),
(97, 'Tour Kham Pha Rung Dua Hoi An', 'tour-coconut-forest', 'Trai nghiem cheo thung thu vi.', NULL, 97, 'active', NOW(), NOW()),
(98, 'Tour Tham Cac Hoi Quan Hoi An', 'tour-guildhall', 'Tim hieu van hoa cac bang hoi Hoa kieu.', NULL, 98, 'active', NOW(), NOW()),
(99, 'Tour May Do Lay Lien Hoi An', 'tour-tailor', 'Trai nghiem dich vu may do noi tieng the gioi.', NULL, 99, 'active', NOW(), NOW()),
(100, 'Tour Kham Pha Hang Gio', 'tour-hang-gio', 'Thu thach mao hiem tai danh thang moi.', NULL, 100, 'active', NOW(), NOW());

-- 2. BLOG_CATEGORIES (Target 100)
INSERT INTO blog_categories (id, name, slug, description, created_at, updated_at) VALUES
(1, 'Cam Nang Du Lich', 'cam-nang-du-lich', 'Kinh nghiem tu A-Z cho chuyen di cua ban.', NOW(), NOW()),
(2, 'Review Am Thuc', 'review-am-thuc', 'Nhung quan an ngon nuc tieng khong the bo qua.', NOW(), NOW()),
(3, 'Dia Diem Check-in', 'dia-diem-check-in', 'Tong hop nhung toa do song ao cuc chat.', NOW(), NOW()),
(4, 'Tin Tuc Du Lich', 'tin-tuc-du-lich', 'Cap nhat cac su kien, le hoi moi nhat.', NOW(), NOW()),
(5, 'Lich Trinh Goi Y', 'lich-trinh-goi-y', 'Goi y lich trinh 3 ngay 2 dem, 4 ngay 3 dem.', NOW(), NOW()),
(6, 'Van Hoa & Lich Su', 'van-hoa-lich-su', 'Tim hieu ve nguon goc va truyen thong dia phuong.', NOW(), NOW()),
(7, 'Meo Tiet Kiem', 'meo-tiet-kiem', 'Cach du lich Da Nang voi chi phi thap nhat.', NOW(), NOW()),
(8, 'Review Khach San', 'review-khach-san', 'Danh gia chan thuc ve noi luu tru.', NOW(), NOW()),
(9, 'Kinh Nghiem Phuot', 'kinh-nghiem-phuot', 'Danh cho nhung tam hon thich xe dich bang xe may.', NOW(), NOW()),
(10, 'Qua Tang Dac San', 'qua-tang-dac-san', 'Mua gi ve lam qua khi du lich mien Trung?', NOW(), NOW()),
-- Adding 90 more blog categories to reach 100
(11, 'Du Lich Theo Mua', 'du-lich-theo-mua', 'Nen di Da Nang thang may la dep nhat?', NOW(), NOW()),
(12, 'Review Tour Thuc Te', 'review-tour', 'Cam nhan cua khach hang sau khi trai nghiem tour.', NOW(), NOW()),
(13, 'Anh Dep Du Khach', 'anh-dep-du-khach', 'Goc nhin du lich qua ong kinh khach hang.', NOW(), NOW()),
(14, 'Huong Dan Thu Tuc', 'huong-dan-thu-tuc', 'Visa, ve may bay, bao hiem du lich.', NOW(), NOW()),
(15, 'Goc Anh Nghe Thuat', 'art-corner', 'Ve dep Da Nang qua con mat nhiep anh gia.', NOW(), NOW()),
(16, 'Du Lich Gia Dinh', 'family-travel-tips', 'Meo nho khi co tre em va nguoi gia di cung.', NOW(), NOW()),
(17, 'Hen Ho Lang Man', 'romantic-date', 'Nhung diem den danh rieng cho cac cap doi.', NOW(), NOW()),
(18, 'Du Lich Mot Minh (Solo)', 'solo-travel', 'An toan va tu do kham pha theo cach cua ban.', NOW(), NOW()),
(19, 'Team Building Ideas', 'team-building-ideas', 'Cac tro choi va dia diem to chuc gan ket.', NOW(), NOW()),
(20, 'Vlog Du Lich', 'travel-vlog', 'Review qua video sinh dong.', NOW(), NOW()),
(21, 'Podcast Du Lich', 'travel-podcast', 'Nghe nhung cau chuyen xe dich truyen cam hung.', NOW(), NOW()),
(22, 'Cam Nang Hoi An', 'hoi-an-guide', 'Chuyen sau ve pho co va vung ven.', NOW(), NOW()),
(23, 'Cam Nang Hue', 'hue-guide', 'Chuyen sau ve co do va cac lang tam.', NOW(), NOW()),
(24, 'Cam Nang Da Nang', 'danang-guide', 'Chuyen sau ve thanh pho dang song nhat.', NOW(), NOW()),
(25, 'Kham Pha Quang Binh', 'quang-binh-guide', 'Hanh trinh hang dong va bien Nhat Le.', NOW(), NOW()),
(26, 'Kham Pha Quang Nam', 'quang-nam-guide', 'Ben ngoai Hoi An con gi thu vi?', NOW(), NOW()),
(27, 'Kham Pha Quang Ngai', 'quang-ngai-guide', 'Dao Ly Son va bien My Khe (Quang Ngai).', NOW(), NOW()),
(28, 'Kham Pha Binh Dinh', 'binh-dinh-guide', 'Quy Nhon - Thanh pho thi ca.', NOW(), NOW()),
(29, 'Kham Pha Phu Yen', 'phu-yen-guide', 'Xu so hoa vang tren co xanh.', NOW(), NOW()),
(30, 'Phuong Tien Di Chuyen', 'transport-guide', 'Thue xe may, Grab hay xe buyt?', NOW(), NOW()),
(31, 'Du Lich Ben Vung', 'sustainable-travel', 'Han che rac thai nhua khi di du lich.', NOW(), NOW()),
(32, 'Cong Nghe Du Lich', 'travel-tech', 'Ung dung can thiet cho chuyen di cua ban.', NOW(), NOW()),
(33, 'Phong Van Nguoi Ban Dia', 'local-interview', 'Lang nghe nhung cau chuyen chua ke.', NOW(), NOW()),
(34, 'Top 10 Da Nang', 'top-10-danang', 'Bang xep hang cac dich vu tot nhat.', NOW(), NOW()),
(35, 'Goc Khuat Da Nang', 'hidden-danang', 'Nhung diem den it nguoi biet nhung cuc dep.', NOW(), NOW()),
(36, 'Chup Anh Duong Pho', 'street-photography', 'Bat tron khoanh khac doi thuong.', NOW(), NOW()),
(37, 'Thoi Trang Du Lich', 'travel-fashion', 'Mac gi de co nhung buc anh lung linh?', NOW(), NOW()),
(38, 'Suc Khoe Chuyen Di', 'travel-health', 'Phong tranh say nang va cac benh thuong gap.', NOW(), NOW()),
(39, 'Am Thuc Chay', 'vegan-food-guide', 'Nhung dia chi an chay ngon tai mien Trung.', NOW(), NOW()),
(40, 'Do Uong & Cafe', 'drink-cafe-review', 'Tiem cafe dep, quan bar soi dong.', NOW(), NOW()),
(41, 'Cho & Mua Sam', 'market-shopping', 'Trai nghiem mua sam tai cho truyen thong.', NOW(), NOW()),
(42, 'Le Hoi Phao Hoa', 'diff-news', 'Cap nhat thong tin DIFF hang nam.', NOW(), NOW()),
(43, 'Su Kien The Thao', 'sports-events', 'Marathon, Ironman va cac giai dau lon.', NOW(), NOW()),
(44, 'Nghe Thuat Bieu Dien', 'performance-art', 'Ky uc Hoi An, Show Charming Danang.', NOW(), NOW()),
(45, 'Kien Truc & Do Thi', 'architecture-urban', 'Su phat trien cua cac cay cau va toa nha.', NOW(), NOW()),
(46, 'Doi Song Cu Dan', 'local-life', 'Tim hieu phong tuc tap quan nguoi mien Trung.', NOW(), NOW()),
(47, 'Goc Review Homestay', 'homestay-review', 'Am cung nhu o nha.', NOW(), NOW()),
(48, 'Goc Review Resort', 'resort-review', 'Xung tam dang cap quoc te.', NOW(), NOW()),
(49, 'Goc Review Villa', 'villa-review', 'Khong gian nghi duong gia dinh hoan hao.', NOW(), NOW()),
(50, 'Goc Review Hostel', 'hostel-review', 'Danh cho dan du lich bui (Backpackers).', NOW(), NOW()),
-- Synthetic categories 51-100 to meet volume
(51, 'Kinh Nghiem San Ve Re', 'cheap-flight-tips', 'Meo san ve may bay gia hoi.', NOW(), NOW()),
(52, 'Du Lich Tam Linh Cam Nang', 'spiritual-guide', 'Huong dan hanh huong tai cac ngoi chua lon.', NOW(), NOW()),
(53, 'Kham Pha Song Han', 'song-han-exploration', 'Ve dep dong song bieu tuong thanh pho.', NOW(), NOW()),
(54, 'Review Spa & Wellness', 'spa-wellness-review', 'Dia chi thu gian tot nhat.', NOW(), NOW()),
(55, 'Huong Dan Di Ba Na Hills', 'ba-na-hills-tips', 'Lam sao de khong bi lac va choi het cac tro?', NOW(), NOW()),
(56, 'Huong Dan Di Hoi An', 'hoi-an-tips', 'Goc chup anh dep va quan an ngon.', NOW(), NOW()),
(57, 'Huong Dan Di Co Do Hue', 'hue-tips', 'Lich trinh tham quan cac lang tam hieu qua.', NOW(), NOW()),
(58, 'Kham Pha Deo Hai Van', 'hai-van-tips', 'Nhung diem dung chan khong the bo qua.', NOW(), NOW()),
(59, 'Kham Pha Ban Dao Son Tra', 'son-tra-tips', 'Tim hieu ve Vooc cha va chan nau.', NOW(), NOW()),
(60, 'Review Nha Hang Hai San', 'seafood-restaurant-review', 'Tuoi ngon va gia ca phai chang.', NOW(), NOW()),
(61, 'Cam Nang Qua Luu Niem', 'souvenir-guide', 'Nhung mon do y nghia nen mua.', NOW(), NOW()),
(62, 'Review Quan Cafe Lam Viec', 'work-cafe-review', 'Khong gian yen tinh, wifi manh.', NOW(), NOW()),
(63, 'Kinh Nghiem Di Cu Lao Cham', 'cu-lao-cham-tips', 'Luu y ve moi truong va an toan bien.', NOW(), NOW()),
(64, 'Review Cac Bai Bien', 'beach-review', 'My Khe, Non Nuoc hay Thanh Khe?', NOW(), NOW()),
(65, 'Review Cho Con', 'cho-con-review', 'Thien duong an vat lon nhat Da Nang.', NOW(), NOW()),
(66, 'Review Cho Han', 'cho-han-review', 'Dia diem mua sam dac san lam qua.', NOW(), NOW()),
(67, 'Review Cho Dem Helio', 'helio-market-review', 'Khong khi soi dong va am thuc da dang.', NOW(), NOW()),
(68, 'Review Cho Dem Son Tra', 'son-tra-market-review', 'Mua sam va dao pho dem.', NOW(), NOW()),
(69, 'Kham Pha Cong Vien APEC', 'apec-park-review', 'Kien truc canh dieu doc dao.', NOW(), NOW()),
(70, 'Kham Pha Cau Vang', 'golden-bridge-review', 'Bieu tuong du lich moi cua Viet Nam.', NOW(), NOW()),
(71, 'Kham Pha Cau Rong', 'dragon-bridge-review', 'Lich phun lua va phun nuoc.', NOW(), NOW()),
(72, 'Kham Pha Cau Song Han', 'song-han-bridge-review', 'Lich quay cua cay cau doc nhat.', NOW(), NOW()),
(73, 'Kham Pha Cau Thuan Phuoc', 'thuan-phuoc-bridge-review', 'Cay cau day vang dai nhat Viet Nam.', NOW(), NOW()),
(74, 'Kham Pha Cau Tran Thi Ly', 'tran-thi-ly-bridge-review', 'Hinh dang canh buom vuon ra bien lon.', NOW(), NOW()),
(75, 'Review Bao Tang Cham', 'cham-museum-review', 'Noi luu giu tinh hoa van hoa Cham Pa.', NOW(), NOW()),
(76, 'Review Bao Tang Da Nang', 'danang-museum-review', 'Tim hieu lich su hinh thanh thanh pho.', NOW(), NOW()),
(77, 'Review Bao Tang My Thuat', 'art-museum-review', 'Khong gian nghe thuat duong dai.', NOW(), NOW()),
(78, 'Review Nha Trung Bay Hoang Sa', 'hoang-sa-museum-review', 'Minh chung chu quyen bien dao.', NOW(), NOW()),
(79, 'Kinh Nghiem Di Ngu Hanh Son', 'marble-mountain-tips', 'Tham quan hang dong va chua chien.', NOW(), NOW()),
(80, 'Review Lang Da Non Nuoc', 'non-nuoc-stone-review', 'Nghe thuat dieu khac da tinh xao.', NOW(), NOW()),
(81, 'Kinh Nghiem Di Thanh Dia My Son', 'my-son-tips', 'Hanh trinh tim ve qua khu.', NOW(), NOW()),
(82, 'Review Vinpearl River Safari', 'river-safari-review', 'Tham quan thu bang thuyen doc dao.', NOW(), NOW()),
(83, 'Review VinWonders Games', 'vinwonders-games-review', 'Cac tro choi cam giac manh hap dan.', NOW(), NOW()),
(84, 'Kinh Nghiem Di Nui Than Tai', 'than-tai-mountain-tips', 'Tam khoang nong va vui choi.', NOW(), NOW()),
(85, 'Review Tam Bun Galina', 'galina-mud-bath-review', 'Thu gian ngay trong long thanh pho.', NOW(), NOW()),
(86, 'Review Tam Bun Phuoc Nhon', 'phuoc-nhon-mud-bath-review', 'Suoi khoang nong tu nhien.', NOW(), NOW()),
(87, 'Review Asian Park (Cong Vien Chau A)', 'asian-park-review', 'Vong quay mat troi va cac khu van hoa.', NOW(), NOW()),
(88, 'Kinh Nghiem Di Hoa Phu Thanh', 'hoa-phu-thanh-tips', 'Truot thac va massage ca.', NOW(), NOW()),
(89, 'Review Suoi Hoa', 'suoi-hoa-review', 'Ve dep thien nhien moc mac.', NOW(), NOW()),
(90, 'Review Ngam Doi', 'ngam-doi-review', 'Diem da ngoai ly tuong mua he.', NOW(), NOW()),
(91, 'Cam Nang An Sang Da Nang', 'breakfast-danang-guide', 'Mi quang, bun cha ca, xoi ga.', NOW(), NOW()),
(92, 'Cam Nang An Trua Da Nang', 'lunch-danang-guide', 'Com nieu, banh trang cuon thit heo.', NOW(), NOW()),
(93, 'Cam Nang An Toi Da Nang', 'dinner-danang-guide', 'Hai san, lau, do nuong.', NOW(), NOW()),
(94, 'Cam Nang An Dem Da Nang', 'late-night-danang-guide', 'Bun xuong, banh canh ruong.', NOW(), NOW()),
(95, 'Review Quan Banh Mi Da Nang', 'banh-mi-danang-review', 'Banh mi ba Lan, banh mi ga.', NOW(), NOW()),
(96, 'Review Quan Che Da Nang', 'che-danang-review', 'Che Lien, che Xuan Trang.', NOW(), NOW()),
(97, 'Review Quan Kem Da Nang', 'kem-danang-review', 'Kem bo co Van cho Bac My An.', NOW(), NOW()),
(98, 'Review Quan Nhau Da Nang', 'nhau-danang-review', 'Binh dan va ven bien.', NOW(), NOW()),
(99, 'Review Quan Bar Rooftop', 'rooftop-bar-review', 'Sky36, Brilliant Top Bar.', NOW(), NOW()),
(100, 'Review Quan Cafe View Song', 'river-view-cafe-review', 'Goc nhin lung linh ve dem.', NOW(), NOW());



