-- DanangTrip polish generic tour slugs
-- FILE: 43_polish_generic_tour_slugs_seed.sql
-- Purpose: replace tour-real-variant-* slugs and clean repeated Tour wording.

WITH tour_updates(id, name, slug) AS (
    VALUES
        (21, 'Tour Tiết Kiệm Phố Cổ Hội An & Rừng Dừa Bảy Mẫu', 'tour-tiet-kiem-pho-co-hoi-an-rung-dua-bay-mau'),
        (22, 'Tour Khám Phá Ngũ Hành Sơn & Chùa Linh Ứng Sơn Trà', 'tour-kham-pha-ngu-hanh-son-chua-linh-ung-son-tra'),
        (23, 'Tour Khám Phá Cù Lao Chàm Lặn Ngắm San Hô', 'tour-kham-pha-cu-lao-cham-lan-ngam-san-ho'),
        (24, 'Tour Khám Phá Cố Đô Huế 1 Ngày từ Đà Nẵng', 'tour-kham-pha-co-do-hue-1-ngay-tu-da-nang'),
        (25, 'Tour Cao Cấp Thánh Địa Mỹ Sơn nửa ngày', 'tour-cao-cap-thanh-dia-my-son-nua-ngay'),
        (26, 'Tour Tiết Kiệm Đà Nẵng City - Những Cây Cầu', 'tour-tiet-kiem-da-nang-city-nhung-cay-cau'),
        (27, 'Tour Khám Phá Đèo Hải Vân & Lăng Cô - Ô tô', 'tour-kham-pha-deo-hai-van-lang-co-o-to'),
        (28, 'Tour Khám Phá Đêm Phố Cổ Hội An & Ăn Tối', 'tour-kham-pha-dem-pho-co-hoi-an-an-toi'),
        (29, 'Tour Khám Phá Bà Nà Hills Đêm (Sun World Night)', 'tour-kham-pha-ba-na-hills-dem-sun-world-night'),
        (30, 'Tour Cao Cấp VinWonders Nam Hội An Full Day', 'tour-cao-cap-vinwonders-nam-hoi-an-full-day'),
        (31, 'Tour Tiết Kiệm Suối Khoáng Nóng Thần Tài Relax', 'tour-tiet-kiem-suoi-khoang-nong-than-tai-relax'),
        (32, 'Tour Khám Phá Trekking Bán Đảo Sơn Trà', 'tour-kham-pha-trekking-ban-dao-son-tra'),
        (33, 'Tour Khám Phá Khám Phá Bạch Mã National Park', 'tour-kham-pha-kham-pha-bach-ma-national-park'),
        (34, 'Tour Khám Phá Street Food Đà Nẵng bằng Xe Máy', 'tour-kham-pha-street-food-da-nang-bang-xe-may'),
        (35, 'Tour Cao Cấp Làm Nông Dân Làng Rau Trà Quế', 'tour-cao-cap-lam-nong-dan-lang-rau-tra-que'),
        (36, 'Tour Tiết Kiệm Du Thuyền Sông Hàn & Xem Rồng Phun Lửa', 'tour-tiet-kiem-du-thuyen-song-han-xem-rong-phun-lua'),
        (37, 'Tour Khám Phá Đầm Phá Tam Giang & Sunset', 'tour-kham-pha-dam-pha-tam-giang-sunset'),
        (38, 'Tour Khám Phá Ca Huế Trên Sông Hương & Ngắm Thành Phố', 'tour-kham-pha-ca-hue-tren-song-huong-ngam-thanh-pho'),
        (39, 'Tour Khám Phá Snorkeling Bán Đảo Sơn Trà', 'tour-kham-pha-snorkeling-ban-dao-son-tra'),
        (40, 'Tour Cao Cấp Bà Nà Hills 1 Ngày (Buffet Trưa)', 'tour-cao-cap-ba-na-hills-1-ngay-buffet-trua'),
        (41, 'Tour Tiết Kiệm Phố Cổ Hội An & Rừng Dừa Bảy Mẫu', 'tour-tiet-kiem-pho-co-hoi-an-rung-dua-bay-mau-goi-41'),
        (42, 'Tour Khám Phá Ngũ Hành Sơn & Chùa Linh Ứng Sơn Trà', 'tour-kham-pha-ngu-hanh-son-chua-linh-ung-son-tra-goi-42'),
        (43, 'Tour Khám Phá Cù Lao Chàm Lặn Ngắm San Hô', 'tour-kham-pha-cu-lao-cham-lan-ngam-san-ho-goi-43'),
        (44, 'Tour Khám Phá Cố Đô Huế 1 Ngày từ Đà Nẵng', 'tour-kham-pha-co-do-hue-1-ngay-tu-da-nang-goi-44'),
        (45, 'Tour Cao Cấp Thánh Địa Mỹ Sơn nửa ngày', 'tour-cao-cap-thanh-dia-my-son-nua-ngay-goi-45'),
        (46, 'Tour Tiết Kiệm Đà Nẵng City - Những Cây Cầu', 'tour-tiet-kiem-da-nang-city-nhung-cay-cau-goi-46'),
        (47, 'Tour Khám Phá Đèo Hải Vân & Lăng Cô - Ô tô', 'tour-kham-pha-deo-hai-van-lang-co-o-to-goi-47'),
        (48, 'Tour Khám Phá Đêm Phố Cổ Hội An & Ăn Tối', 'tour-kham-pha-dem-pho-co-hoi-an-an-toi-goi-48'),
        (49, 'Tour Khám Phá Bà Nà Hills Đêm (Sun World Night)', 'tour-kham-pha-ba-na-hills-dem-sun-world-night-goi-49'),
        (50, 'Tour Cao Cấp VinWonders Nam Hội An Full Day', 'tour-cao-cap-vinwonders-nam-hoi-an-full-day-goi-50'),
        (51, 'Tour Tiết Kiệm Suối Khoáng Nóng Thần Tài Relax', 'tour-tiet-kiem-suoi-khoang-nong-than-tai-relax-goi-51'),
        (52, 'Tour Khám Phá Trekking Bán Đảo Sơn Trà', 'tour-kham-pha-trekking-ban-dao-son-tra-goi-52'),
        (53, 'Tour Khám Phá Khám Phá Bạch Mã National Park', 'tour-kham-pha-kham-pha-bach-ma-national-park-goi-53'),
        (54, 'Tour Khám Phá Street Food Đà Nẵng bằng Xe Máy', 'tour-kham-pha-street-food-da-nang-bang-xe-may-goi-54'),
        (55, 'Tour Cao Cấp Làm Nông Dân Làng Rau Trà Quế', 'tour-cao-cap-lam-nong-dan-lang-rau-tra-que-goi-55'),
        (56, 'Tour Tiết Kiệm Du Thuyền Sông Hàn & Xem Rồng Phun Lửa', 'tour-tiet-kiem-du-thuyen-song-han-xem-rong-phun-lua-goi-56'),
        (57, 'Tour Khám Phá Đầm Phá Tam Giang & Sunset', 'tour-kham-pha-dam-pha-tam-giang-sunset-goi-57'),
        (58, 'Tour Khám Phá Ca Huế Trên Sông Hương & Ngắm Thành Phố', 'tour-kham-pha-ca-hue-tren-song-huong-ngam-thanh-pho-goi-58'),
        (59, 'Tour Khám Phá Snorkeling Bán Đảo Sơn Trà', 'tour-kham-pha-snorkeling-ban-dao-son-tra-goi-59'),
        (60, 'Tour Cao Cấp Bà Nà Hills 1 Ngày (Buffet Trưa)', 'tour-cao-cap-ba-na-hills-1-ngay-buffet-trua-goi-60'),
        (61, 'Tour Tiết Kiệm Phố Cổ Hội An & Rừng Dừa Bảy Mẫu', 'tour-tiet-kiem-pho-co-hoi-an-rung-dua-bay-mau-goi-61'),
        (62, 'Tour Khám Phá Ngũ Hành Sơn & Chùa Linh Ứng Sơn Trà', 'tour-kham-pha-ngu-hanh-son-chua-linh-ung-son-tra-goi-62'),
        (63, 'Tour Khám Phá Cù Lao Chàm Lặn Ngắm San Hô', 'tour-kham-pha-cu-lao-cham-lan-ngam-san-ho-goi-63'),
        (64, 'Tour Khám Phá Cố Đô Huế 1 Ngày từ Đà Nẵng', 'tour-kham-pha-co-do-hue-1-ngay-tu-da-nang-goi-64'),
        (65, 'Tour Cao Cấp Thánh Địa Mỹ Sơn nửa ngày', 'tour-cao-cap-thanh-dia-my-son-nua-ngay-goi-65'),
        (66, 'Tour Tiết Kiệm Đà Nẵng City - Những Cây Cầu', 'tour-tiet-kiem-da-nang-city-nhung-cay-cau-goi-66'),
        (67, 'Tour Khám Phá Đèo Hải Vân & Lăng Cô - Ô tô', 'tour-kham-pha-deo-hai-van-lang-co-o-to-goi-67'),
        (68, 'Tour Khám Phá Đêm Phố Cổ Hội An & Ăn Tối', 'tour-kham-pha-dem-pho-co-hoi-an-an-toi-goi-68'),
        (69, 'Tour Khám Phá Bà Nà Hills Đêm (Sun World Night)', 'tour-kham-pha-ba-na-hills-dem-sun-world-night-goi-69'),
        (70, 'Tour Cao Cấp VinWonders Nam Hội An Full Day', 'tour-cao-cap-vinwonders-nam-hoi-an-full-day-goi-70'),
        (71, 'Tour Tiết Kiệm Suối Khoáng Nóng Thần Tài Relax', 'tour-tiet-kiem-suoi-khoang-nong-than-tai-relax-goi-71'),
        (72, 'Tour Khám Phá Trekking Bán Đảo Sơn Trà', 'tour-kham-pha-trekking-ban-dao-son-tra-goi-72'),
        (73, 'Tour Khám Phá Khám Phá Bạch Mã National Park', 'tour-kham-pha-kham-pha-bach-ma-national-park-goi-73'),
        (74, 'Tour Khám Phá Street Food Đà Nẵng bằng Xe Máy', 'tour-kham-pha-street-food-da-nang-bang-xe-may-goi-74'),
        (75, 'Tour Cao Cấp Làm Nông Dân Làng Rau Trà Quế', 'tour-cao-cap-lam-nong-dan-lang-rau-tra-que-goi-75'),
        (76, 'Tour Tiết Kiệm Du Thuyền Sông Hàn & Xem Rồng Phun Lửa', 'tour-tiet-kiem-du-thuyen-song-han-xem-rong-phun-lua-goi-76'),
        (77, 'Tour Khám Phá Đầm Phá Tam Giang & Sunset', 'tour-kham-pha-dam-pha-tam-giang-sunset-goi-77'),
        (78, 'Tour Khám Phá Ca Huế Trên Sông Hương & Ngắm Thành Phố', 'tour-kham-pha-ca-hue-tren-song-huong-ngam-thanh-pho-goi-78'),
        (79, 'Tour Khám Phá Snorkeling Bán Đảo Sơn Trà', 'tour-kham-pha-snorkeling-ban-dao-son-tra-goi-79'),
        (80, 'Tour Cao Cấp Bà Nà Hills 1 Ngày (Buffet Trưa)', 'tour-cao-cap-ba-na-hills-1-ngay-buffet-trua-goi-80'),
        (81, 'Tour Tiết Kiệm Phố Cổ Hội An & Rừng Dừa Bảy Mẫu', 'tour-tiet-kiem-pho-co-hoi-an-rung-dua-bay-mau-goi-81'),
        (82, 'Tour Khám Phá Ngũ Hành Sơn & Chùa Linh Ứng Sơn Trà', 'tour-kham-pha-ngu-hanh-son-chua-linh-ung-son-tra-goi-82'),
        (83, 'Tour Khám Phá Cù Lao Chàm Lặn Ngắm San Hô', 'tour-kham-pha-cu-lao-cham-lan-ngam-san-ho-goi-83'),
        (84, 'Tour Khám Phá Cố Đô Huế 1 Ngày từ Đà Nẵng', 'tour-kham-pha-co-do-hue-1-ngay-tu-da-nang-goi-84'),
        (85, 'Tour Cao Cấp Thánh Địa Mỹ Sơn nửa ngày', 'tour-cao-cap-thanh-dia-my-son-nua-ngay-goi-85'),
        (86, 'Tour Tiết Kiệm Đà Nẵng City - Những Cây Cầu', 'tour-tiet-kiem-da-nang-city-nhung-cay-cau-goi-86'),
        (87, 'Tour Khám Phá Đèo Hải Vân & Lăng Cô - Ô tô', 'tour-kham-pha-deo-hai-van-lang-co-o-to-goi-87'),
        (88, 'Tour Khám Phá Đêm Phố Cổ Hội An & Ăn Tối', 'tour-kham-pha-dem-pho-co-hoi-an-an-toi-goi-88'),
        (89, 'Tour Khám Phá Bà Nà Hills Đêm (Sun World Night)', 'tour-kham-pha-ba-na-hills-dem-sun-world-night-goi-89'),
        (90, 'Tour Cao Cấp VinWonders Nam Hội An Full Day', 'tour-cao-cap-vinwonders-nam-hoi-an-full-day-goi-90'),
        (91, 'Tour Tiết Kiệm Suối Khoáng Nóng Thần Tài Relax', 'tour-tiet-kiem-suoi-khoang-nong-than-tai-relax-goi-91'),
        (92, 'Tour Khám Phá Trekking Bán Đảo Sơn Trà', 'tour-kham-pha-trekking-ban-dao-son-tra-goi-92'),
        (93, 'Tour Khám Phá Khám Phá Bạch Mã National Park', 'tour-kham-pha-kham-pha-bach-ma-national-park-goi-93'),
        (94, 'Tour Khám Phá Street Food Đà Nẵng bằng Xe Máy', 'tour-kham-pha-street-food-da-nang-bang-xe-may-goi-94'),
        (95, 'Tour Cao Cấp Làm Nông Dân Làng Rau Trà Quế', 'tour-cao-cap-lam-nong-dan-lang-rau-tra-que-goi-95'),
        (96, 'Tour Tiết Kiệm Du Thuyền Sông Hàn & Xem Rồng Phun Lửa', 'tour-tiet-kiem-du-thuyen-song-han-xem-rong-phun-lua-goi-96'),
        (97, 'Tour Khám Phá Đầm Phá Tam Giang & Sunset', 'tour-kham-pha-dam-pha-tam-giang-sunset-goi-97'),
        (98, 'Tour Khám Phá Ca Huế Trên Sông Hương & Ngắm Thành Phố', 'tour-kham-pha-ca-hue-tren-song-huong-ngam-thanh-pho-goi-98'),
        (99, 'Tour Khám Phá Snorkeling Bán Đảo Sơn Trà', 'tour-kham-pha-snorkeling-ban-dao-son-tra-goi-99'),
        (100, 'Tour Cao Cấp Bà Nà Hills 1 Ngày (Buffet Trưa)', 'tour-cao-cap-ba-na-hills-1-ngay-buffet-trua-goi-100')
)
UPDATE tours t
SET name = tour_updates.name,
    slug = tour_updates.slug,
    updated_at = NOW()
FROM tour_updates
WHERE t.id = tour_updates.id
  AND (t.slug LIKE 'tour-real-variant-%' OR t.name LIKE '%Variant%');
