BEGIN;
INSERT INTO "landing_pages" ("id", "slug", "title", "page_type", "intro", "hero_image", "seo_title", "seo_description", "og_image", "filters", "content_blocks", "status", "created_at", "updated_at") VALUES
(1, 'du-lich-da-nang', 'Trang giới thiệu du lịch Đà Nẵng', 'destination', 'Khám phá điểm đến, tour, ưu đãi và kinh nghiệm du lịch Đà Nẵng bằng nội dung tiếng Việt có dấu.', NULL, 'Du lịch Đà Nẵng | DanangTrip', 'Cẩm nang du lịch Đà Nẵng, Hội An, Huế và miền Trung với tour, địa điểm, lịch trình và ưu đãi được chuẩn hóa tiếng Việt.', NULL, '{"sort": "featured", "destination": "da-nang", "tour_category_slugs": ["tour-da-nang", "tour-ba-na", "tour-son-tra"]}', '[{"type":"section","title":"Nội dung đã chuẩn hóa","body":"Khối nội dung này được chuẩn hóa tiếng Việt có dấu để dùng cho landing page DanangTrip."}]', 'published', '2026-06-13 10:19:55', '2026-06-13 10:21:02'),
(2, 'tour-ba-na-hills', 'Trang giới thiệu du lịch Đà Nẵng', 'tour_line', 'Khám phá điểm đến, tour, ưu đãi và kinh nghiệm du lịch Đà Nẵng bằng nội dung tiếng Việt có dấu.', NULL, 'Du lịch Đà Nẵng | DanangTrip', 'Cẩm nang du lịch Đà Nẵng, Hội An, Huế và miền Trung với tour, địa điểm, lịch trình và ưu đãi được chuẩn hóa tiếng Việt.', NULL, '{"sort": "popular", "keywords": ["ba na hills", "cau vang", "cap treo"], "tour_category_slugs": ["tour-ba-na"]}', '[{"type":"section","title":"Nội dung đã chuẩn hóa","body":"Khối nội dung này được chuẩn hóa tiếng Việt có dấu để dùng cho landing page DanangTrip."}]', 'published', '2026-06-13 10:19:55', '2026-06-13 10:21:02'),
(3, 'tour-son-tra-ngu-hanh-son', 'Trang giới thiệu du lịch Đà Nẵng', 'tour_line', 'Khám phá điểm đến, tour, ưu đãi và kinh nghiệm du lịch Đà Nẵng bằng nội dung tiếng Việt có dấu.', NULL, 'Du lịch Đà Nẵng | DanangTrip', 'Cẩm nang du lịch Đà Nẵng, Hội An, Huế và miền Trung với tour, địa điểm, lịch trình và ưu đãi được chuẩn hóa tiếng Việt.', NULL, '{"sort": "featured", "keywords": ["son tra", "ngu hanh son", "linh ung"], "tour_category_slugs": ["tour-son-tra", "tour-ngu-hanh-son"]}', '[{"type":"section","title":"Nội dung đã chuẩn hóa","body":"Khối nội dung này được chuẩn hóa tiếng Việt có dấu để dùng cho landing page DanangTrip."}]', 'published', '2026-06-13 10:19:55', '2026-06-13 10:21:02'),
(4, 'khuyen-mai-tour-da-nang', 'Trang giới thiệu du lịch Đà Nẵng', 'promotion', 'Khám phá điểm đến, tour, ưu đãi và kinh nghiệm du lịch Đà Nẵng bằng nội dung tiếng Việt có dấu.', NULL, 'Du lịch Đà Nẵng | DanangTrip', 'Cẩm nang du lịch Đà Nẵng, Hội An, Huế và miền Trung với tour, địa điểm, lịch trình và ưu đãi được chuẩn hóa tiếng Việt.', NULL, '{"sort": "newest", "promotion_codes": ["DANANG10", "CENTRAL15", "FAMILY200K", "BANAHILLS300K"]}', '[{"type":"section","title":"Nội dung đã chuẩn hóa","body":"Khối nội dung này được chuẩn hóa tiếng Việt có dấu để dùng cho landing page DanangTrip."}]', 'published', '2026-06-13 10:19:55', '2026-06-13 10:21:02'),
(5, 'cam-nang-du-lich-mien-trung', 'Trang giới thiệu du lịch Đà Nẵng', 'destination', 'Khám phá điểm đến, tour, ưu đãi và kinh nghiệm du lịch Đà Nẵng bằng nội dung tiếng Việt có dấu.', NULL, 'Du lịch Đà Nẵng | DanangTrip', 'Cẩm nang du lịch Đà Nẵng, Hội An, Huế và miền Trung với tour, địa điểm, lịch trình và ưu đãi được chuẩn hóa tiếng Việt.', NULL, '{"sort": "recommended", "keywords": ["da nang", "hoi an", "hue"], "destination": "central-vietnam"}', '[{"type":"section","title":"Nội dung đã chuẩn hóa","body":"Khối nội dung này được chuẩn hóa tiếng Việt có dấu để dùng cho landing page DanangTrip."}]', 'draft', '2026-06-13 10:19:55', '2026-06-13 10:21:02')
ON CONFLICT (id) DO NOTHING;

COMMIT;
