-- DanangTrip Real Data Seeder: Tags & Amenities (100 rows each)
-- FILE: 02_tags_amenities.sql

-- 1. TAGS (Target 100)
INSERT INTO tags (id, name, slug, type, created_at, updated_at) VALUES
(1, 'Gan bien', 'gan-bien', 'location', NOW(), NOW()),
(2, 'Trung tam thanh pho', 'trung-tam-thanh-pho', 'location', NOW(), NOW()),
(3, 'View song', 'view-song', 'location', NOW(), NOW()),
(4, 'Yen tinh', 'yen-tinh', 'atmosphere', NOW(), NOW()),
(5, 'Soi dong', 'soi-dong', 'atmosphere', NOW(), NOW()),
(6, 'Sang trong', 'sang-trong', 'style', NOW(), NOW()),
(7, 'Binh dan', 'binh-dan', 'style', NOW(), NOW()),
(8, 'Hien dai', 'hien-dai', 'style', NOW(), NOW()),
(9, 'Co dien', 'co-dien', 'style', NOW(), NOW()),
(10, 'Lang man', 'lang-man', 'atmosphere', NOW(), NOW()),
(11, 'Gia dinh', 'gia-dinh', 'audience', NOW(), NOW()),
(12, 'Cap doi', 'cap-doi', 'audience', NOW(), NOW()),
(13, 'Nhom ban', 'nhom-ban', 'audience', NOW(), NOW()),
(14, 'Cong tac', 'cong-tac', 'audience', NOW(), NOW()),
(15, 'Gia re', 'gia-re', 'price', NOW(), NOW()),
(16, 'Cao cap', 'cao-cap', 'price', NOW(), NOW()),
(17, 'Am thuc bien', 'am-thuc-bien', 'food', NOW(), NOW()),
(18, 'Mon an dac san', 'mon-an-dac-san', 'food', NOW(), NOW()),
(19, 'Check-in dep', 'check-in-dep', 'feature', NOW(), NOW()),
(20, 'View dep', 'view-dep', 'feature', NOW(), NOW()),
(21, 'Than thien moi truong', 'eco-friendly', 'style', NOW(), NOW()),
(22, 'Van hoa ban dia', 'local-culture', 'theme', NOW(), NOW()),
(23, 'Lich su', 'history', 'theme', NOW(), NOW()),
(24, 'Nghe thuat', 'art', 'theme', NOW(), NOW()),
(25, 'Kham pha', 'adventure', 'theme', NOW(), NOW()),
(26, 'Nghi duong', 'relaxation', 'theme', NOW(), NOW()),
(27, 'Mua sam', 'shopping', 'theme', NOW(), NOW()),
(28, 'Giai tri', 'entertainment', 'theme', NOW(), NOW()),
(29, 'Vui choi tre em', 'kids-friendly', 'audience', NOW(), NOW()),
(30, 'Thu cung', 'pet-friendly', 'feature', NOW(), NOW()),
-- Adding 70 more tags to reach 100
(31, 'Outdoor seating', 'outdoor-seating', 'feature', NOW(), NOW()),
(32, 'Indoor seating', 'indoor-seating', 'feature', NOW(), NOW()),
(33, 'Phong rieng', 'private-room', 'feature', NOW(), NOW()),
(34, 'Wifi manh', 'strong-wifi', 'feature', NOW(), NOW()),
(35, 'Cho dau xe', 'parking', 'feature', NOW(), NOW()),
(36, 'Thanh toan the', 'card-payment', 'feature', NOW(), NOW()),
(37, 'Mo cua 24/7', 'open-247', 'feature', NOW(), NOW()),
(38, 'Giao hang tan noi', 'delivery', 'feature', NOW(), NOW()),
(39, 'Mua mang ve', 'takeaway', 'feature', NOW(), NOW()),
(40, 'Dat ban truoc', 'reservation', 'feature', NOW(), NOW()),
(41, 'Nhac song', 'live-music', 'atmosphere', NOW(), NOW()),
(42, 'DJ show', 'dj-show', 'atmosphere', NOW(), NOW()),
(43, 'View bien', 'ocean-view', 'location', NOW(), NOW()),
(44, 'Gan san bay', 'near-airport', 'location', NOW(), NOW()),
(45, 'Gan ga tau', 'near-station', 'location', NOW(), NOW()),
(46, 'Gan ben xe', 'near-bus-stop', 'location', NOW(), NOW()),
(47, 'Gan cho', 'near-market', 'location', NOW(), NOW()),
(48, 'Vung ngoai o', 'suburban', 'location', NOW(), NOW()),
(49, 'Khu du lich', 'tourist-area', 'location', NOW(), NOW()),
(50, 'Khu dan cu', 'residential-area', 'location', NOW(), NOW()),
(51, 'Song ao', 'instagrammable', 'style', NOW(), NOW()),
(52, 'Vintage', 'vintage-style', 'style', NOW(), NOW()),
(53, 'Indochine', 'indochine-style', 'style', NOW(), NOW()),
(54, 'Minimalist', 'minimalist-style', 'style', NOW(), NOW()),
(55, 'Industrial', 'industrial-style', 'style', NOW(), NOW()),
(56, 'Tropical', 'tropical-style', 'style', NOW(), NOW()),
(57, 'Bohemian', 'bohemian-style', 'style', NOW(), NOW()),
(58, 'Moc mac', 'rustic-style', 'style', NOW(), NOW()),
(59, 'Truyen thong', 'traditional-style', 'style', NOW(), NOW()),
(60, 'Sang tao', 'creative-style', 'style', NOW(), NOW()),
(61, 'An sang', 'breakfast', 'food', NOW(), NOW()),
(62, 'An trua', 'lunch', 'food', NOW(), NOW()),
(63, 'An toi', 'dinner', 'food', NOW(), NOW()),
(64, 'An dem', 'late-night-food', 'food', NOW(), NOW()),
(65, 'Do uong co con', 'alcohol', 'food', NOW(), NOW()),
(66, 'Ruou vang', 'wine', 'food', NOW(), NOW()),
(67, 'Bia thu cong', 'craft-beer', 'food', NOW(), NOW()),
(68, 'Nuoc trai cay', 'juice-smoothie', 'food', NOW(), NOW()),
(69, 'Tra chieu', 'afternoon-tea', 'food', NOW(), NOW()),
(70, 'Trang mieng', 'dessert', 'food', NOW(), NOW()),
(71, 'Suc khoe', 'health', 'wellness', NOW(), NOW()),
(72, 'Tri lieu', 'therapy', 'wellness', NOW(), NOW()),
(73, 'Thu gian', 'relaxation-well', 'wellness', NOW(), NOW()),
(74, 'Lam dep', 'beauty-care', 'wellness', NOW(), NOW()),
(75, 'Tap luyen', 'workout', 'wellness', NOW(), NOW()),
(76, 'Hoc tap', 'learning', 'education', NOW(), NOW()),
(77, 'Ky nang', 'skills', 'education', NOW(), NOW()),
(78, 'Ngoai ngu', 'languages', 'education', NOW(), NOW()),
(79, 'Phat trien ban than', 'self-development', 'education', NOW(), NOW()),
(80, 'Huong nghiep', 'career-guidance', 'education', NOW(), NOW()),
(81, 'Tech & Gadgets', 'tech-gadgets', 'shopping', NOW(), NOW()),
(82, 'Quan ao', 'clothing', 'shopping', NOW(), NOW()),
(83, 'Phu kien', 'accessories-shop', 'shopping', NOW(), NOW()),
(84, 'Qua tang', 'gift-shop', 'shopping', NOW(), NOW()),
(85, 'Gia dung', 'home-appliances', 'shopping', NOW(), NOW()),
(86, 'Xe may', 'motorbike', 'transport', NOW(), NOW()),
(87, 'O to', 'car', 'transport', NOW(), NOW()),
(88, 'Xe dap', 'bicycle', 'transport', NOW(), NOW()),
(89, 'Di bo', 'walking', 'transport', NOW(), NOW()),
(90, 'Phuong tien cong cong', 'public-transport', 'transport', NOW(), NOW()),
(91, 'Su kien', 'events', 'business', NOW(), NOW()),
(92, 'Hoi thao', 'seminar', 'business', NOW(), NOW()),
(93, 'Giao thuong', 'trade', 'business', NOW(), NOW()),
(94, 'Khoi nghiep', 'startup', 'business', NOW(), NOW()),
(95, 'Dau tu', 'investment', 'business', NOW(), NOW()),
(96, 'Cong dong', 'community', 'social', NOW(), NOW()),
(97, 'Thien nguyen', 'charity', 'social', NOW(), NOW()),
(98, 'Ket noi', 'networking', 'social', NOW(), NOW()),
(99, 'Ben vung', 'sustainability', 'social', NOW(), NOW()),
(100, 'Doi moi', 'innovation', 'social', NOW(), NOW());

-- 2. AMENITIES (Target 100)
INSERT INTO amenities (id, name, icon, category, created_at, updated_at) VALUES
(1, 'Wifi mien phi', 'free-wifi', 'wifi', NOW(), NOW()),
(2, 'Ho boi', 'swimming-pool', 'pool', NOW(), NOW()),
(3, 'Cho dau xe mien phi', 'free-parking', 'parking', NOW(), NOW()),
(4, 'Phong Gym', 'gym-fitness', 'fitness', NOW(), NOW()),
(5, 'Spa', 'spa-wellness', 'spa', NOW(), NOW()),
(6, 'Nha hang', 'on-site-restaurant', 'restaurant', NOW(), NOW()),
(7, 'Bar', 'on-site-bar', 'bar', NOW(), NOW()),
(8, 'Dieu hoa nhiet do', 'air-conditioning', 'ac', NOW(), NOW()),
(9, 'Tivi', 'television', 'tv', NOW(), NOW()),
(10, 'Tu lanh mini', 'mini-bar', 'fridge', NOW(), NOW()),
(11, 'May pha ca phe', 'coffee-maker', 'coffee', NOW(), NOW()),
(12, 'Ban cong', 'balcony', 'outdoor', NOW(), NOW()),
(13, 'Ban lam viec', 'work-desk', 'desk', NOW(), NOW()),
(14, 'Ket sat', 'safety-box', 'safe', NOW(), NOW()),
(15, 'May say toc', 'hair-dryer', 'dryer', NOW(), NOW()),
(16, 'Dich vu phong 24/7', 'room-service-247', 'bell', NOW(), NOW()),
(17, 'Dich vu giat la', 'laundry-service', 'washing', NOW(), NOW()),
(18, 'Dua don san bay', 'airport-shuttle', 'shuttle', NOW(), NOW()),
(19, 'Le tan 24h', 'reception-24h', 'user', NOW(), NOW()),
(20, 'Thang may', 'elevator', 'arrow-up', NOW(), NOW()),
(21, 'Phong hop/Hoi nghi', 'meeting-room', 'users', NOW(), NOW()),
(22, 'San vuon', 'garden', 'leaf', NOW(), NOW()),
(23, 'Khu vui choi tre em', 'kids-club', 'baby', NOW(), NOW()),
(24, 'Cho phep thu cung', 'pets-allowed', 'dog', NOW(), NOW()),
(25, 'Bai bien rieng', 'private-beach', 'sun', NOW(), NOW()),
(26, 'Phong khong hut thuoc', 'non-smoking-room', 'smoke-free', NOW(), NOW()),
(27, 'Bon tam', 'bathtub', 'bath', NOW(), NOW()),
(28, 'Voi hoa sen', 'shower', 'water', NOW(), NOW()),
(29, 'Ao choang tam', 'bathrobe', 'shirt', NOW(), NOW()),
(30, 'Dep di trong phong', 'slippers', 'foot', NOW(), NOW()),
-- Adding 70 more amenities to reach 100
(31, 'Am dun nuoc dien', 'electric-kettle', 'bolt', NOW(), NOW()),
(32, 'Ban la & Cau la', 'iron-board', 'iron', NOW(), NOW()),
(33, 'Nuoc dong chai mien phi', 'free-bottled-water', 'bottle', NOW(), NOW()),
(34, 'Dung cu nha bep', 'kitchenware', 'pot', NOW(), NOW()),
(35, 'Lo vi song', 'microwave', 'oven', NOW(), NOW()),
(36, 'Bep nau', 'stovetop', 'flame', NOW(), NOW()),
(37, 'Ban an', 'dining-table', 'table', NOW(), NOW()),
(38, 'Ghe sofa', 'sofa', 'couch', NOW(), NOW()),
(39, 'Tu quan ao', 'wardrobe', 'cabinet', NOW(), NOW()),
(40, 'Guong soi toan than', 'full-length-mirror', 'user', NOW(), NOW()),
(41, 'Den ngu', 'night-lamp', 'light', NOW(), NOW()),
(42, 'Rem can sang', 'blackout-curtains', 'window', NOW(), NOW()),
(43, 'He thong bao chay', 'fire-alarm', 'bell', NOW(), NOW()),
(44, 'He thong phun nuoc tu dong', 'sprinkler-system', 'water', NOW(), NOW()),
(45, 'Khoa cua thong minh/The tu', 'smart-lock', 'key', NOW(), NOW()),
(46, 'Dien thoai noi bo', 'intercom', 'phone', NOW(), NOW()),
(47, 'O cam USB', 'usb-outlet', 'usb', NOW(), NOW()),
(48, 'Sac khong day', 'wireless-charging', 'bolt', NOW(), NOW()),
(49, 'Kenh truyen hinh cap', 'cable-tv', 'tv', NOW(), NOW()),
(50, 'Netflix/Smart TV', 'smart-tv', 'monitor', NOW(), NOW()),
(51, 'Bao chi hang ngay', 'daily-newspaper', 'file-text', NOW(), NOW()),
(52, 'Ban do du lich', 'tourist-map', 'map', NOW(), NOW()),
(53, 'Ho tro dat tour', 'tour-desk', 'globe', NOW(), NOW()),
(54, 'Doi tien te tai quay', 'currency-exchange-desk', 'dollar', NOW(), NOW()),
(55, 'Dich vu gui do', 'luggage-storage', 'briefcase', NOW(), NOW()),
(56, 'Dich vu trong xe ho (Valet)', 'valet-parking', 'key', NOW(), NOW()),
(57, 'Tram sac xe dien', 'ev-charging', 'bolt', NOW(), NOW()),
(58, 'Cho thue xe dap', 'bicycle-rental', 'bike', NOW(), NOW()),
(59, 'Cho thue xe may', 'motorbike-rental-amenity', 'motorcycle', NOW(), NOW()),
(60, 'Dich vu thu ky', 'secretarial-service', 'file', NOW(), NOW()),
(61, 'Trung tam dich vu khach hang', 'business-center', 'laptop', NOW(), NOW()),
(62, 'May photocopy & In an', 'photocopy-print', 'printer', NOW(), NOW()),
(63, 'Wifi toc do cao', 'high-speed-wifi', 'zap', NOW(), NOW()),
(64, 'Bua sang mien phi', 'free-breakfast', 'coffee', NOW(), NOW()),
(65, 'Bua sang buffet', 'buffet-breakfast', 'restaurant', NOW(), NOW()),
(66, 'Dich vu don phong hang ngay', 'daily-housekeeping', 'clean', NOW(), NOW()),
(67, 'Dich vu danh giay', 'shoe-shine', 'star', NOW(), NOW()),
(68, 'Dich vu may do/Sua do', 'tailoring-service', 'scissors', NOW(), NOW()),
(69, 'Phong xong hoi kho (Sauna)', 'sauna', 'cloud', NOW(), NOW()),
(70, 'Phong xong hoi uot (Steam)', 'steam-room', 'droplet', NOW(), NOW()),
(71, 'Be suc Jacuzzi', 'jacuzzi', 'waves', NOW(), NOW()),
(72, 'Salon lam toc', 'hair-salon', 'scissors', NOW(), NOW()),
(73, 'Tiem lam mong (Nail)', 'nail-salon', 'pen', NOW(), NOW()),
(74, 'Cua hang tien loi trong resort', 'resort-shop', 'shopping-bag', NOW(), NOW()),
(75, 'May rut tien ATM', 'atm-machine', 'dollar', NOW(), NOW()),
(76, 'Khu vuc hut thuoc rieng', 'smoking-area', 'smoke', NOW(), NOW()),
(77, 'Camera an ninh 24/7', 'cctv', 'eye', NOW(), NOW()),
(78, 'Bao ve chuyen nghiep', 'professional-security', 'shield', NOW(), NOW()),
(79, 'Loi di cho nguoi khuyet tat', 'wheelchair-access', 'wheelchair', NOW(), NOW()),
(80, 'Thang may uu tien', 'priority-elevator', 'arrow-up-circle', NOW(), NOW()),
(81, 'Ghe cao cho tre em', 'high-chair', 'user-check', NOW(), NOW()),
(82, 'Noi em be (Crib)', 'crib', 'home', NOW(), NOW()),
(83, 'Dich vu bao mau', 'babysitting-service', 'users', NOW(), NOW()),
(84, 'Khu vuc BBQ ngoai troi', 'bbq-area', 'flame', NOW(), NOW()),
(85, 'San hien phoi nang', 'sun-terrace', 'sun', NOW(), NOW()),
(86, 'Ghe tam nang (Sunbed)', 'sunbed', 'armchair', NOW(), NOW()),
(87, 'O che nang bien', 'beach-umbrella', 'umbrella', NOW(), NOW()),
(88, 'Khan tam bien mien phi', 'free-beach-towels', 'towel', NOW(), NOW()),
(89, 'Thiet bi tap the duc ngoai troi', 'outdoor-gym', 'activity', NOW(), NOW()),
(90, 'Thu vien trong nha', 'indoor-library', 'book-open', NOW(), NOW()),
(91, 'Phong choi game/Bida', 'games-room', 'play', NOW(), NOW()),
(92, 'Dan Karaoke', 'karaoke-system', 'mic', NOW(), NOW()),
(93, 'Rap chieu phim mini', 'mini-cinema', 'film', NOW(), NOW()),
(94, 'May loc nuoc', 'water-purifier', 'droplet', NOW(), NOW()),
(95, 'May loc khong khi', 'air-purifier', 'wind', NOW(), NOW()),
(96, 'Dem cao cap/Memory foam', 'premium-bedding', 'bed', NOW(), NOW()),
(97, 'Lua chon goi (Pillow menu)', 'pillow-menu', 'archive', NOW(), NOW()),
(98, 'Dich vu danh thuc (Wake-up call)', 'wake-up-call', 'clock', NOW(), NOW()),
(99, 'Hop so cuu (First aid kit)', 'first-aid', 'plus', NOW(), NOW()),
(100, 'May khu khuan tay', 'hand-sanitizer', 'sparkles', NOW(), NOW());

