-- DanangTrip Seed: Promotions
-- FILE: 17_promotions_seed.sql
-- Purpose: Provide real-looking promotion data for admin, booking and coupon validation flows.
-- Notes:
--   - No image data.
--   - Codes are uppercase and unique.
--   - Keep rows idempotent with ON CONFLICT (code).

INSERT INTO promotions (
  code,
  name,
  description,
  discount_type,
  discount_value,
  max_discount_amount,
  min_order_amount,
  usage_limit,
  usage_per_user,
  used_count,
  starts_at,
  ends_at,
  status,
  created_at,
  updated_at
) VALUES
(
  'DANANG10',
  'Giam 10% tour Da Nang',
  'Ap dung cho cac tour Da Nang, Son Tra, Ngu Hanh Son va tour bien. Phu hop de test coupon percent.',
  'percent',
  10.00,
  300000.00,
  1000000.00,
  500,
  1,
  0,
  NOW() - INTERVAL '7 days',
  NOW() + INTERVAL '90 days',
  'active',
  NOW(),
  NOW()
),
(
  'CENTRAL15',
  'Giam 15% hanh trinh mien Trung',
  'Ap dung cho tour lien tuyen Da Nang - Hoi An - Hue, dung de test dieu kien don hang cao.',
  'percent',
  15.00,
  500000.00,
  2500000.00,
  300,
  1,
  0,
  NOW() - INTERVAL '3 days',
  NOW() + INTERVAL '60 days',
  'active',
  NOW(),
  NOW()
),
(
  'FAMILY200K',
  'Giam 200K cho gia dinh',
  'Ma giam gia co dinh cho booking nhieu nguoi, phu hop test discount_type fixed.',
  'fixed',
  200000.00,
  NULL,
  1800000.00,
  250,
  1,
  0,
  NOW() - INTERVAL '1 day',
  NOW() + INTERVAL '45 days',
  'active',
  NOW(),
  NOW()
),
(
  'BANAHILLS300K',
  'Giam 300K tour Ba Na Hills',
  'Khuyen mai co dinh cho cac tour Ba Na Hills va Cau Vang.',
  'fixed',
  300000.00,
  NULL,
  3000000.00,
  200,
  1,
  0,
  NOW(),
  NOW() + INTERVAL '75 days',
  'active',
  NOW(),
  NOW()
),
(
  'EARLYBIRD8',
  'Uu dai dat som 8%',
  'Ap dung cho booking dat truoc ngay khoi hanh, dung de test khuyen mai theo thoi gian.',
  'percent',
  8.00,
  250000.00,
  900000.00,
  400,
  2,
  0,
  NOW() - INTERVAL '10 days',
  NOW() + INTERVAL '120 days',
  'active',
  NOW(),
  NOW()
),
(
  'WELCOME100K',
  'Giam 100K cho khach moi',
  'Ma welcome de test coupon co dinh voi don hang nho.',
  'fixed',
  100000.00,
  NULL,
  700000.00,
  1000,
  1,
  0,
  NOW() - INTERVAL '30 days',
  NOW() + INTERVAL '180 days',
  'active',
  NOW(),
  NOW()
),
(
  'SUMMER2026',
  'Uu dai he 2026',
  'Chuong trinh giam gia mua he cho cac tour bien, cong vien va nghi duong.',
  'percent',
  12.00,
  400000.00,
  1500000.00,
  600,
  1,
  0,
  TIMESTAMP '2026-06-01 00:00:00',
  TIMESTAMP '2026-08-31 23:59:59',
  'active',
  NOW(),
  NOW()
),
(
  'FLASH20',
  'Flash sale 20%',
  'Ma test trang thai inactive cho admin promotions.',
  'percent',
  20.00,
  600000.00,
  2000000.00,
  100,
  1,
  0,
  NOW() - INTERVAL '20 days',
  NOW() + INTERVAL '10 days',
  'inactive',
  NOW(),
  NOW()
),
(
  'EXPIRED50K',
  'Ma het han 50K',
  'Du lieu test trang thai expired va logic validate coupon het han.',
  'fixed',
  50000.00,
  NULL,
  500000.00,
  100,
  1,
  12,
  NOW() - INTERVAL '90 days',
  NOW() - INTERVAL '1 day',
  'expired',
  NOW(),
  NOW()
),
(
  'VIP25',
  'Uu dai VIP 25%',
  'Ma giam gia gia tri cao de test max discount va min order.',
  'percent',
  25.00,
  1000000.00,
  5000000.00,
  50,
  1,
  0,
  NOW(),
  NOW() + INTERVAL '30 days',
  'active',
  NOW(),
  NOW()
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  discount_type = EXCLUDED.discount_type,
  discount_value = EXCLUDED.discount_value,
  max_discount_amount = EXCLUDED.max_discount_amount,
  min_order_amount = EXCLUDED.min_order_amount,
  usage_limit = EXCLUDED.usage_limit,
  usage_per_user = EXCLUDED.usage_per_user,
  starts_at = EXCLUDED.starts_at,
  ends_at = EXCLUDED.ends_at,
  status = EXCLUDED.status,
  updated_at = NOW();
