-- DanangTrip approved source-backed blog guide seed
-- FILE: 22_approved_blog_guides_seed.sql
-- Source: danangtrip-crawler/data/blog-guides-staging.json
-- Policy: inserts only approved records without review flags; status remains draft.
-- Run after 03_tour_blog_categories.sql and 04_users.sql.

BEGIN;

INSERT INTO blog_posts (id, title, slug, excerpt, content, featured_image, author_id, view_count, status, published_at, created_at, updated_at) VALUES
(201, 'Da Nang', 'da-nang', 'Ban nhap cam nang ve cam nang va trai nghiem du lich Da Nang, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'Da Nang Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: cam nang va trai nghiem du lich Da Nang. - Nhom noi dung: cam-nang-da-nang. - Tu khoa goi y: da-nang, am-thuc, bien. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-da-nang Source URL: https://vietnam.travel/places-to-go/central-vietnam/da-nang Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(202, 'Hoi An', 'hoi-an', 'Ban nhap cam nang ve cam nang va trai nghiem du lich Hoi An, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'Hoi An Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: cam nang va trai nghiem du lich Hoi An. - Nhom noi dung: cam-nang-hoi-an. - Tu khoa goi y: da-nang, hoi-an, am-thuc, bien. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-hoi-an Source URL: https://vietnam.travel/places-to-go/central-vietnam/hoi-an Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(203, 'Hue', 'hue', 'Ban nhap cam nang ve cam nang va trai nghiem du lich Hue, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'Hue Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: cam nang va trai nghiem du lich Hue. - Nhom noi dung: cam-nang-hue. - Tu khoa goi y: hue. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-hue Source URL: https://vietnam.travel/places-to-go/central-vietnam/hue Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(204, '3 perfect days in Danang', '3-perfect-days-in-danang', 'Ban nhap cam nang ve lich trinh, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', '3 perfect days in Danang Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: lich trinh. - Nhom noi dung: lich-trinh. - Tu khoa goi y: da-nang, am-thuc, bien, van-hoa. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-da-nang-itinerary Source URL: https://vietnam.travel/things-to-do/da-nang-itinerary Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(205, 'Must-visit places in Da Nang', 'must-visit-places-in-da-nang', 'Ban nhap cam nang ve cam nang va trai nghiem du lich Da Nang, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'Must-visit places in Da Nang Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: cam nang va trai nghiem du lich Da Nang. - Nhom noi dung: cam-nang-da-nang. - Tu khoa goi y: da-nang, hoi-an, bien. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-da-nang-must-visit Source URL: https://vietnam.travel/things-to-do/must-visit-places-in-da-nang Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(206, 'How to explore and enjoy Ba Na Hills', 'how-to-explore-and-enjoy-ba-na-hills', 'Ban nhap cam nang ve trai nghiem Ba Na Hills va khu vuc Cau Vang, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'How to explore and enjoy Ba Na Hills Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: trai nghiem Ba Na Hills va khu vuc Cau Vang. - Nhom noi dung: diem-den. - Tu khoa goi y: da-nang. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-ba-na-hills Source URL: https://vietnam.travel/things-to-do/explore-ba-na-hills Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(207, 'A walk around Marble Mountains', 'a-walk-around-marble-mountains', 'Ban nhap cam nang ve tham quan Ngu Hanh Son va cac hang dong/chua, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'A walk around Marble Mountains Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: tham quan Ngu Hanh Son va cac hang dong/chua. - Nhom noi dung: diem-den. - Tu khoa goi y: da-nang, lich-trinh, bien. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-marble-mountains Source URL: https://vietnam.travel/things-to-do/around-marble-mountains Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(208, 'The mystic My Son', 'the-mystic-my-son', 'Ban nhap cam nang ve tham quan Thanh dia My Son va di san Cham, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'The mystic My Son Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: tham quan Thanh dia My Son va di san Cham. - Nhom noi dung: diem-den. - Tu khoa goi y: da-nang. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-my-son Source URL: https://vietnam.travel/things-to-do/mystic-my-son Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(209, 'Da Nang''s special pork rolls', 'da-nang-s-special-pork-rolls', 'Ban nhap cam nang ve cam nang va trai nghiem du lich Da Nang, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'Da Nang''s special pork rolls Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: cam nang va trai nghiem du lich Da Nang. - Nhom noi dung: am-thuc. - Tu khoa goi y: da-nang, am-thuc. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-da-nang-food Source URL: https://vietnam.travel/things-to-do/da-nangs-special-pork-rolls Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(210, 'Hai Van Pass', 'hai-van-pass', 'Ban nhap cam nang ve tham quan deo Hai Van va hanh trinh Da Nang - Hue, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'Hai Van Pass Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: tham quan deo Hai Van va hanh trinh Da Nang - Hue. - Nhom noi dung: diem-den. - Tu khoa goi y: da-nang, hue. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: danangfantasticity-hai-van-pass Source URL: https://danangfantasticity.com/hai-van-pass Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(211, 'The Son Tra Peninsula', 'the-son-tra-peninsula', 'Ban nhap cam nang ve tham quan ban dao Son Tra, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'The Son Tra Peninsula Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: tham quan ban dao Son Tra. - Nhom noi dung: diem-den. - Tu khoa goi y: da-nang. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: danangfantasticity-son-tra-peninsula Source URL: https://danangfantasticity.com/the-son-tra-peninsula Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(212, 'Da Nang Beaches', 'da-nang-beaches', 'Ban nhap cam nang ve cam nang va trai nghiem du lich Da Nang, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'Da Nang Beaches Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: cam nang va trai nghiem du lich Da Nang. - Nhom noi dung: bien. - Tu khoa goi y: da-nang, bien. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: danangfantasticity-da-nang-beaches Source URL: https://danangfantasticity.com/en/see-and-do/da-nang-beaches-2 Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(213, 'A traveller''s guide to Vietnam''s airports', 'a-traveller-s-guide-to-vietnam-s-airports', 'Ban nhap cam nang ve di chuyen, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'A traveller''s guide to Vietnam''s airports Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: di chuyen. - Nhom noi dung: di-chuyen. - Tu khoa goi y: da-nang. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-airports Source URL: https://vietnam.travel/node/887 Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(214, 'Transport within Vietnam', 'transport-within-vietnam', 'Ban nhap cam nang ve di chuyen, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'Transport within Vietnam Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: di chuyen. - Nhom noi dung: di-chuyen. - Tu khoa goi y: du lich mien Trung. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-transport-within-vietnam Source URL: https://vietnam.travel/plan-your-trip/transport-within-vietnam Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(215, 'Plan your trip', 'plan-your-trip', 'Ban nhap cam nang ve kinh nghiem, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'Plan your trip Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: kinh nghiem. - Nhom noi dung: kinh-nghiem. - Tu khoa goi y: lich-trinh. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-plan-your-trip Source URL: https://vietnam.travel/plan-your-trip Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(216, 'Motorbiking Hoi An to Hue over Hai Van Pass', 'motorbiking-hoi-an-to-hue-over-hai-van-pass', 'Ban nhap cam nang ve cam nang va trai nghiem du lich Hoi An, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'Motorbiking Hoi An to Hue over Hai Van Pass Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: cam nang va trai nghiem du lich Hoi An. - Nhom noi dung: di-chuyen. - Tu khoa goi y: hoi-an, hue, am-thuc, bien. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-motorbike-hoi-an-hue Source URL: https://vietnam.travel/node/705 Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(217, 'Must-do Da Nang: An insider list', 'must-do-da-nang-an-insider-list', 'Ban nhap cam nang ve cam nang va trai nghiem du lich Da Nang, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', 'Must-do Da Nang: An insider list Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: cam nang va trai nghiem du lich Da Nang. - Nhom noi dung: kinh-nghiem. - Tu khoa goi y: da-nang, am-thuc, bien, van-hoa. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-da-nang-insider-list Source URL: https://vietnam.travel/things-to-do/must-do-da-nang-an-insider-list Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW()),
(218, '4 Reasons Why Da Nang is Vietnam''s Most Livable City', '4-reasons-why-da-nang-is-vietnam-s-most-livable-city', 'Ban nhap cam nang ve cam nang va trai nghiem du lich Da Nang, duoc thu thap tu nguon cong khai va can bien tap truoc khi publish.', '4 Reasons Why Da Nang is Vietnam''s Most Livable City Ban nhap source-backed cho DanangTrip. Tom tat rewrite: - Chu de: cam nang va trai nghiem du lich Da Nang. - Nhom noi dung: kinh-nghiem. - Tu khoa goi y: da-nang, bien. - Noi dung nen bien tap thanh bai cam nang ngan gon, uu tien thong tin thuc te ve diem den, lich trinh, thoi diem tham quan, di chuyen va luu y cho du khach. - Khong publish truc tiep neu chua duoc bien tap lai bang giong van DanangTrip. Nguon tham chieu: vietnam-travel-da-nang-livable-city Source URL: https://vietnam.travel/things-to-do/4-reasons-da-nang-is-vietnam-most-livable-city Trang thai: draft. Can bien tap truoc khi published.', NULL, 2, 0, 'draft', NULL, NOW(), NOW())
ON CONFLICT (slug) DO NOTHING;

INSERT INTO blog_post_categories (post_id, blog_category_id) VALUES
(201, 24),
(202, 22),
(203, 23),
(204, 5),
(205, 24),
(206, 3),
(207, 3),
(208, 3),
(209, 2),
(210, 3),
(211, 3),
(212, 64),
(213, 30),
(214, 30),
(215, 1),
(216, 30),
(217, 1),
(218, 1)
ON CONFLICT (post_id, blog_category_id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('blog_posts', 'id'), GREATEST((SELECT MAX(id) FROM blog_posts), 1));

COMMIT;
