-- DanangTrip blog Cloudinary featured image update
-- FILE: 41_update_blog_featured_images_from_cloudinary_seed.sql
-- Purpose: update published blog_posts.featured_image from reviewed Cloudinary upload results.

WITH image_rows(blog_id, featured_image) AS (
    VALUES
        (1, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621734/danangtrip/blogs/central-vietnam-7-day-itinerary/blog-1__central-vietnam-7-day-itinerary__p01.jpg'),
        (2, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621737/danangtrip/blogs/why-visit-central-vietnam/blog-2__why-visit-central-vietnam__p01.jpg'),
        (3, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621740/danangtrip/blogs/unforgettable-things-to-do-central-vietnam/blog-3__unforgettable-things-to-do-central-vietnam__p01.jpg'),
        (4, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621743/danangtrip/blogs/where-to-stay-central-vietnam/blog-4__where-to-stay-central-vietnam__p01.jpg'),
        (5, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621745/danangtrip/blogs/5-day-central-vietnam-itinerary/blog-5__5-day-central-vietnam-itinerary__p01.jpg'),
        (6, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621748/danangtrip/blogs/vietnam-coastal-road-trip-guide/blog-6__vietnam-coastal-road-trip-guide__p01.jpg'),
        (7, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621751/danangtrip/blogs/transportation-guide-central-vietnam/blog-7__transportation-guide-central-vietnam__p01.jpg'),
        (8, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621754/danangtrip/blogs/why-visit-hue/blog-8__why-visit-hue__p01.jpg'),
        (9, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621757/danangtrip/blogs/first-timers-guide-central-vietnam/blog-9__first-timers-guide-central-vietnam__p01.jpg'),
        (10, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621760/danangtrip/blogs/hidden-gems-central-vietnam/blog-10__hidden-gems-central-vietnam__p01.jpg'),
        (11, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621763/danangtrip/blogs/love-letter-to-hoi-an/blog-11__love-letter-to-hoi-an__p01.jpg'),
        (12, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621767/danangtrip/blogs/best-things-to-do-hoi-an/blog-12__best-things-to-do-hoi-an__p01.jpg'),
        (13, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621769/danangtrip/blogs/hoi-an-lantern-streets/blog-13__hoi-an-lantern-streets__p01.jpg'),
        (14, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621772/danangtrip/blogs/48-hours-in-hoi-an/blog-14__48-hours-in-hoi-an__p01.jpg'),
        (15, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621774/danangtrip/blogs/hoi-an-tailoring-guide/blog-15__hoi-an-tailoring-guide__p01.jpg'),
        (16, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621777/danangtrip/blogs/cycling-hoi-an-countryside/blog-16__cycling-hoi-an-countryside__p01.jpg'),
        (17, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621780/danangtrip/blogs/hoi-an-food-guide/blog-17__hoi-an-food-guide__p01.jpg'),
        (18, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621783/danangtrip/blogs/best-cafes-hoi-an/blog-18__best-cafes-hoi-an__p01.jpg'),
        (19, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621786/danangtrip/blogs/hoi-an-lantern-festival-guide/blog-19__hoi-an-lantern-festival-guide__p01.jpg'),
        (20, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621789/danangtrip/blogs/photography-guide-hoi-an/blog-20__photography-guide-hoi-an__p01.jpg'),
        (21, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621792/danangtrip/blogs/hoi-an-beach-guide/blog-21__hoi-an-beach-guide__p01.jpg'),
        (22, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621795/danangtrip/blogs/where-to-stay-hoi-an/blog-22__where-to-stay-hoi-an__p01.jpg'),
        (23, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621799/danangtrip/blogs/lost-in-hoi-an/blog-23__lost-in-hoi-an__p01.jpg'),
        (24, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621801/danangtrip/blogs/hoi-an-craft-workshops/blog-24__hoi-an-craft-workshops__p01.jpg'),
        (25, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621804/danangtrip/blogs/budget-travel-hoi-an/blog-25__budget-travel-hoi-an__p01.jpg'),
        (26, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621807/danangtrip/blogs/da-nang-rising-star/blog-26__da-nang-rising-star__p01.jpg'),
        (27, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621809/danangtrip/blogs/da-nang-beach-guide/blog-27__da-nang-beach-guide__p01.jpg'),
        (28, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621812/danangtrip/blogs/dragon-bridge-guide/blog-28__dragon-bridge-guide__p01.jpg'),
        (29, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621815/danangtrip/blogs/da-nang-cafe-guide/blog-29__da-nang-cafe-guide__p01.jpg'),
        (30, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621818/danangtrip/blogs/ba-na-hills-golden-bridge-guide/blog-30__ba-na-hills-golden-bridge-guide__p01.jpg'),
        (31, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621820/danangtrip/blogs/marble-mountains-guide/blog-31__marble-mountains-guide__p01.jpg'),
        (32, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621823/danangtrip/blogs/da-nang-travel-base/blog-32__da-nang-travel-base__p01.jpg'),
        (33, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621826/danangtrip/blogs/da-nang-nightlife-guide/blog-33__da-nang-nightlife-guide__p01.jpg'),
        (34, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621829/danangtrip/blogs/da-nang-food-tour/blog-34__da-nang-food-tour__p01.jpg'),
        (35, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621831/danangtrip/blogs/da-nang-weekend-itinerary/blog-35__da-nang-weekend-itinerary__p01.jpg'),
        (36, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621834/danangtrip/blogs/son-tra-peninsula-guide/blog-36__son-tra-peninsula-guide__p01.jpg'),
        (37, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621836/danangtrip/blogs/da-nang-digital-nomad-guide/blog-37__da-nang-digital-nomad-guide__p01.jpg'),
        (38, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621839/danangtrip/blogs/da-nang-wellness-guide/blog-38__da-nang-wellness-guide__p01.jpg'),
        (39, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621841/danangtrip/blogs/luxury-hotels-da-nang/blog-39__luxury-hotels-da-nang__p01.jpg'),
        (40, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621844/danangtrip/blogs/da-nang-family-travel-guide/blog-40__da-nang-family-travel-guide__p01.jpg'),
        (41, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621847/danangtrip/blogs/surfing-da-nang-guide/blog-41__surfing-da-nang-guide__p01.jpg'),
        (42, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621850/danangtrip/blogs/hue-imperial-history/blog-42__hue-imperial-history__p01.jpg'),
        (43, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621853/danangtrip/blogs/hue-citadel-guide/blog-43__hue-citadel-guide__p01.jpg'),
        (44, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621856/danangtrip/blogs/hue-royal-tombs-guide/blog-44__hue-royal-tombs-guide__p01.jpg'),
        (45, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621859/danangtrip/blogs/perfume-river-guide/blog-45__perfume-river-guide__p01.jpg'),
        (46, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621863/danangtrip/blogs/hue-culinary-capital/blog-46__hue-culinary-capital__p01.jpg'),
        (47, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621866/danangtrip/blogs/bun-bo-hue-story/blog-47__bun-bo-hue-story__p01.jpg'),
        (48, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621869/danangtrip/blogs/thien-mu-pagoda-guide/blog-48__thien-mu-pagoda-guide__p01.jpg'),
        (49, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621871/danangtrip/blogs/hue-cafe-tea-guide/blog-49__hue-cafe-tea-guide__p01.jpg'),
        (50, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621874/danangtrip/blogs/2-days-in-hue-itinerary/blog-50__2-days-in-hue-itinerary__p01.jpg'),
        (51, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621887/danangtrip/blogs/hue-historical-significance/blog-51__hue-historical-significance__p01.jpg'),
        (52, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621890/danangtrip/blogs/hue-garden-houses-guide/blog-52__hue-garden-houses-guide__p01.jpg'),
        (53, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621893/danangtrip/blogs/hue-history-tour-itinerary/blog-53__hue-history-tour-itinerary__p01.jpg'),
        (54, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621896/danangtrip/blogs/rural-hue-guide/blog-54__rural-hue-guide__p01.jpg'),
        (55, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621898/danangtrip/blogs/where-to-stay-hue-guide/blog-55__where-to-stay-hue-guide__p01.jpg'),
        (56, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621901/danangtrip/blogs/central-vietnam-food-bucket-list/blog-56__central-vietnam-food-bucket-list__p01.jpg'),
        (57, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621904/danangtrip/blogs/vietnam-coffee-culture-guide/blog-57__vietnam-coffee-culture-guide__p01.jpg'),
        (58, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621907/danangtrip/blogs/my-quang-tasting-guide/blog-58__my-quang-tasting-guide__p01.jpg'),
        (59, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621910/danangtrip/blogs/hoi-an-cooking-class-guide/blog-59__hoi-an-cooking-class-guide__p01.jpg'),
        (60, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621912/danangtrip/blogs/where-to-eat-central-vietnam/blog-60__where-to-eat-central-vietnam__p01.jpg'),
        (61, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621915/danangtrip/blogs/central-vietnam-markets-guide/blog-61__central-vietnam-markets-guide__p01.jpg'),
        (62, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621918/danangtrip/blogs/fishing-village-tours-vietnam/blog-62__fishing-village-tours-vietnam__p01.jpg'),
        (63, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621920/danangtrip/blogs/central-vietnam-crafts-guide/blog-63__central-vietnam-crafts-guide__p01.jpg'),
        (64, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621923/danangtrip/blogs/local-transportation-guide-vietnam/blog-64__local-transportation-guide-vietnam__p01.jpg'),
        (65, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621926/danangtrip/blogs/common-travel-mistakes-central-vietnam/blog-65__common-travel-mistakes-central-vietnam__p01.jpg'),
        (66, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621929/danangtrip/blogs/central-vietnam-souvenir-guide/blog-66__central-vietnam-souvenir-guide__p01.jpg'),
        (67, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621931/danangtrip/blogs/vietnamese-etiquette-for-travelers/blog-67__vietnamese-etiquette-for-travelers__p01.jpg'),
        (68, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621934/danangtrip/blogs/travel-safety-guide-central-vietnam/blog-68__travel-safety-guide-central-vietnam__p01.jpg'),
        (69, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621937/danangtrip/blogs/best-time-to-visit-central-vietnam/blog-69__best-time-to-visit-central-vietnam__p01.jpg'),
        (70, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621939/danangtrip/blogs/da-nang-airport-to-hoi-an-guide/blog-70__da-nang-airport-to-hoi-an-guide__p01.jpg'),
        (71, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621942/danangtrip/blogs/hai-van-pass-travel-guide/blog-71__hai-van-pass-travel-guide__p01.jpg'),
        (72, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621945/danangtrip/blogs/3-days-in-da-nang-itinerary/blog-72__3-days-in-da-nang-itinerary__p01.jpg'),
        (73, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621948/danangtrip/blogs/2-days-in-hoi-an-itinerary/blog-73__2-days-in-hoi-an-itinerary__p01.jpg'),
        (74, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621950/danangtrip/blogs/2-days-in-hue-itinerary-guide/blog-74__2-days-in-hue-itinerary-guide__p01.jpg'),
        (75, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621953/danangtrip/blogs/1-week-central-vietnam-planner/blog-75__1-week-central-vietnam-planner__p01.jpg'),
        (76, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621956/danangtrip/blogs/budget-travel-guide-central-vietnam/blog-76__budget-travel-guide-central-vietnam__p01.jpg'),
        (77, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621958/danangtrip/blogs/luxury-travel-central-vietnam/blog-77__luxury-travel-central-vietnam__p01.jpg'),
        (78, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621961/danangtrip/blogs/family-travel-guide-vietnam/blog-78__family-travel-guide-vietnam__p01.jpg'),
        (79, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621963/danangtrip/blogs/motorbike-rental-guide-vietnam/blog-79__motorbike-rental-guide-vietnam__p01.jpg'),
        (80, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621966/danangtrip/blogs/best-travel-apps-vietnam/blog-80__best-travel-apps-vietnam__p01.jpg'),
        (81, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621968/danangtrip/blogs/solo-travel-central-vietnam/blog-81__solo-travel-central-vietnam__p01.jpg'),
        (82, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621971/danangtrip/blogs/vietnam-train-travel-guide/blog-82__vietnam-train-travel-guide__p01.jpg'),
        (83, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621974/danangtrip/blogs/my-son-sanctuary-tour-guide/blog-83__my-son-sanctuary-tour-guide__p01.jpg'),
        (84, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621977/danangtrip/blogs/vietnam-heat-survival-guide/blog-84__vietnam-heat-survival-guide__p01.jpg'),
        (85, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621979/danangtrip/blogs/vietnam-packing-list-guide/blog-85__vietnam-packing-list-guide__p01.jpg'),
        (86, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621982/danangtrip/blogs/falling-in-love-with-vietnam/blog-86__falling-in-love-with-vietnam__p01.jpg'),
        (87, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621984/danangtrip/blogs/travel-lessons-from-vietnam/blog-87__travel-lessons-from-vietnam__p01.jpg'),
        (88, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621987/danangtrip/blogs/instagram-guide-central-vietnam/blog-88__instagram-guide-central-vietnam__p01.jpg'),
        (89, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621990/danangtrip/blogs/comparing-vietnam-regions/blog-89__comparing-vietnam-regions__p01.jpg'),
        (90, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621992/danangtrip/blogs/central-vietnam-history-reflection/blog-90__central-vietnam-history-reflection__p01.jpg'),
        (91, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621995/danangtrip/blogs/heart-of-vietnam-da-nang-hoi-an-hue/blog-91__heart-of-vietnam-da-nang-hoi-an-hue__p01.jpg'),
        (92, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780621998/danangtrip/blogs/sunset-guide-central-vietnam/blog-92__sunset-guide-central-vietnam__p01.jpg'),
        (93, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780622000/danangtrip/blogs/romantic-travel-guide-vietnam/blog-93__romantic-travel-guide-vietnam__p01.jpg'),
        (94, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780622003/danangtrip/blogs/travel-memories-central-vietnam/blog-94__travel-memories-central-vietnam__p01.jpg'),
        (95, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780622005/danangtrip/blogs/vietnam-homestay-experience/blog-95__vietnam-homestay-experience__p01.jpg'),
        (96, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780622008/danangtrip/blogs/future-of-tourism-vietnam/blog-96__future-of-tourism-vietnam__p01.jpg'),
        (97, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780622011/danangtrip/blogs/authentic-travel-vietnam/blog-97__authentic-travel-vietnam__p01.jpg'),
        (98, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780622014/danangtrip/blogs/tribute-to-vietnamese-people/blog-98__tribute-to-vietnamese-people__p01.jpg'),
        (99, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780622016/danangtrip/blogs/surprising-central-vietnam/blog-99__surprising-central-vietnam__p01.jpg'),
        (100, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780622019/danangtrip/blogs/must-visit-central-vietnam-southeast-asia/blog-100__must-visit-central-vietnam-southeast-asia__p01.jpg'),
        (103, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780622033/danangtrip/blogs/top-50-toa-do-song-ao-dep-quen-loi-ve-tai-da-nang-nam-2026/blog-103__top-50-toa-do-song-ao-dep-quen-loi-ve-tai-da-nang-nam-2026__p01.jpg'),
        (105, 'https://res.cloudinary.com/dmukxquza/image/upload/v1780622036/danangtrip/blogs/top-50-toa-do-song-ao-dep-quen-loi-ve-tai-da-nang-nam-2026-copy/blog-105__top-50-toa-do-song-ao-dep-quen-loi-ve-tai-da-nang-nam-2026-copy__p01.jpg')
)
UPDATE blog_posts b
SET featured_image = image_rows.featured_image,
    updated_at = NOW()
FROM image_rows
WHERE b.id = image_rows.blog_id
  AND b.status = 'published'
  AND (b.featured_image IS NULL OR b.featured_image = '');
